version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: widen
    groups:
      pub:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "org.jetbrains.kotlin.plugin.serialization"
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-serialization-json"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-coroutines-android"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-coroutines-test"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
  - package-ecosystem: swift
    directory: /ios/stellar_flutter_sdk
    schedule:
      interval: monthly
    groups:
      swift:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: /tools/xdr-generator
    schedule:
      interval: monthly
    groups:
      bundler:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
