.PHONY: xdr-generate xdr-clean-generated xdr-clean-all xdr-update \
        xdr-generator-test xdr-generator-update-snapshots \
        xdr-generator-validate xdr-generate-tests sep51-generate-tests help

.DEFAULT_GOAL := help

XDRS = xdr/Stellar-SCP.x xdr/Stellar-ledger-entries.x xdr/Stellar-ledger.x \
       xdr/Stellar-overlay.x xdr/Stellar-transaction.x xdr/Stellar-types.x \
       xdr/Stellar-contract-env-meta.x xdr/Stellar-contract-meta.x \
       xdr/Stellar-contract-spec.x xdr/Stellar-contract.x \
       xdr/Stellar-internal.x xdr/Stellar-contract-config-setting.x \
       xdr/Stellar-exporter.x

XDR_COMMIT = 911c9356277468cb588481bd90b5d4b6eda395a7
RUBY_IMAGE = ruby:3.4

# The test emitters replace their output files rather than overwriting them, so a
# container running as root leaves root-owned files on a Linux bind mount and the
# host-side `dart format` below cannot rewrite them. Running as the invoking user
# keeps every emitted file owned by the caller. HOME is set because that uid has
# no entry in the image's passwd database and bundler needs a writable home.
DOCKER_RUN = docker run --rm --user $(shell id -u):$(shell id -g) -e HOME=/tmp \
	-v $(CURDIR):/wd -w /wd $(RUBY_IMAGE) /bin/bash -c

# `dart format` reports a file it cannot write but still exits 0, so a second pass
# re-reads the tree and fails the target if anything was left unformatted.
define dart_format
@if command -v dart >/dev/null 2>&1; then \
	dart format $(1) && dart format --output=none --set-exit-if-changed $(1); \
else \
	echo "Note: dart not found, skipping format. Run 'dart format $(1)' manually."; \
fi
endef

# Use CURDIR (always set by GNU Make) instead of PWD for portability
xdr/%.x: | xdr/
	curl -Lsf -o $@.tmp https://raw.githubusercontent.com/stellar/stellar-xdr/$(XDR_COMMIT)/$(@F) && mv $@.tmp $@

xdr/:
	mkdir -p xdr

XDR_GENERATED = lib/src/xdr/

xdr-generate: $(XDRS) ## Download .x files and generate Dart XDR classes
	$(DOCKER_RUN) '\
		cd tools/xdr-generator && \
		bundle config set --local path vendor/bundle && \
		bundle install --quiet && \
		bundle exec ruby generate.rb'
	$(call dart_format,$(XDR_GENERATED))

xdr-clean-generated: ## Remove only generated Dart files (preserves hand-maintained wrappers)
	@if grep -rl 'automatically generated by xdrgen' lib/src/xdr/ >/dev/null 2>&1; then \
		grep -rl 'automatically generated by xdrgen' lib/src/xdr/ | xargs rm -f; \
	else \
		echo "WARNING: No files with generated marker found."; \
		echo "If this is the first run, use 'make xdr-generate' directly."; \
	fi

xdr-clean-all: xdr-clean-generated ## Remove generated files AND downloaded .x definitions
	rm -f xdr/*.x

xdr-update: xdr-clean-all xdr-generate ## Re-download .x files and regenerate Dart XDR classes

xdr-generator-test: ## Run snapshot tests via Docker
	$(DOCKER_RUN) '\
		cd tools/xdr-generator && \
		bundle config set --local path vendor/bundle && \
		bundle install --quiet && \
		bundle exec ruby test/generator_snapshot_test.rb'

xdr-generator-update-snapshots: ## Regenerate golden snapshot files
	$(DOCKER_RUN) '\
		cd tools/xdr-generator && \
		bundle config set --local path vendor/bundle && \
		bundle install --quiet && \
		bundle exec ruby test/update_snapshots.rb'

xdr-generator-validate: ## Validate generated types against XDR definitions
	$(DOCKER_RUN) '\
		cd tools/xdr-generator && \
		bundle config set --local path vendor/bundle && \
		bundle install --quiet && \
		bundle exec ruby test/validate_generated_types.rb'

XDR_EMITTED_TESTS = test/unit/xdr/generated/

xdr-generate-tests: ## Regenerate XDR unit tests
	$(DOCKER_RUN) '\
		cd tools/xdr-generator && \
		bundle config set --local path vendor/bundle && \
		bundle install --quiet && \
		bundle exec ruby test/generate_tests.rb'
	$(call dart_format,$(XDR_EMITTED_TESTS))

SEP51_EMITTED = test/unit/xdr/json_generated/ test/unit/sep/sep51_corpus_data.dart

sep51-generate-tests: ## Regenerate the SEP-0051 emitted tests and corpus test data
	$(DOCKER_RUN) '\
		cd tools/xdr-generator && \
		bundle config set --local path vendor/bundle && \
		bundle install --quiet && \
		bundle exec ruby test/generate_json_tests.rb'
	python3 tools/sep-51-corpus/emit_dart_corpus.py
	$(call dart_format,$(SEP51_EMITTED))

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-35s\033[0m %s\n", $$1, $$2}'
