// AUTO-GENERATED - DO NOT EDIT
// Generated by tools/xdr-generator/test/generate_json_tests.rb

import 'package:flutter_test/flutter_test.dart';
import 'package:stellar_flutter_sdk/stellar_flutter_sdk.dart';

void main() {
  group('SEP-0051 contract_env_meta renderings', () {
    test(
      'XdrSCEnvMetaKind SC_ENV_META_KIND_INTERFACE_VERSION renders as sc_env_meta_kind_interface_version',
      () {
        var member = XdrSCEnvMetaKind.SC_ENV_META_KIND_INTERFACE_VERSION;
        expect(member.value, 0);
        expect(member.toXdrJsonValue(), 'sc_env_meta_kind_interface_version');
        expect(member.toXdrJson(), '"sc_env_meta_kind_interface_version"');
        var parsed = XdrSCEnvMetaKind.fromXdrJson(
          '"sc_env_meta_kind_interface_version"',
        );
        expect(parsed.value, 0);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(
          XdrSCEnvMetaKind.fromXdrJsonValue(
            'sc_env_meta_kind_interface_version',
          ).value,
          0,
        );
      },
    );
    test('XdrSCEnvMetaKind rejects an undeclared member name', () {
      expect(
        () => XdrSCEnvMetaKind.fromXdrJsonValue('xdr_json_undeclared_member'),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCEnvMetaKind rejects an undeclared value', () {
      expect(
        () => XdrSCEnvMetaKind(1).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCEnvMetaEntryInterfaceVersion round trip', () {
      var original = XdrSCEnvMetaEntryInterfaceVersion(
        XdrUint32(42),
        XdrUint32(42),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCEnvMetaEntryInterfaceVersion.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCEnvMetaEntryInterfaceVersion.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCEnvMetaEntryInterfaceVersion rejects an undeclared key', () {
      var original = XdrSCEnvMetaEntryInterfaceVersion(
        XdrUint32(42),
        XdrUint32(42),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCEnvMetaEntryInterfaceVersion.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test(
      'XdrSCEnvMetaEntry sc_env_meta_kind_interface_version arm round trip',
      () {
        var original = XdrSCEnvMetaEntry(
          XdrSCEnvMetaKind.SC_ENV_META_KIND_INTERFACE_VERSION,
        );
        original.interfaceVersion = XdrSCEnvMetaEntryInterfaceVersion(
          XdrUint32(42),
          XdrUint32(42),
        );
        expect(
          (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
          'sc_env_meta_kind_interface_version',
        );
        var json = original.toXdrJson();
        var fromDocument = XdrSCEnvMetaEntry.fromXdrJson(json);
        expect(fromDocument.toXdrJson(), json);
        expect(
          fromDocument.toBase64EncodedXdrString(),
          original.toBase64EncodedXdrString(),
        );
        var fromTree = XdrSCEnvMetaEntry.fromXdrJsonValue(
          original.toXdrJsonValue(),
        );
        expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
        expect(
          fromTree.toBase64EncodedXdrString(),
          original.toBase64EncodedXdrString(),
        );
      },
    );
    test('XdrSCEnvMetaEntry rejects an undeclared discriminant', () {
      expect(
        () => XdrSCEnvMetaEntry(XdrSCEnvMetaKind(1)).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCEnvMetaEntry rejects an undeclared arm key', () {
      expect(
        () => XdrSCEnvMetaEntry.fromXdrJsonValue(<String, Object?>{
          'xdr_json_undeclared_arm': null,
        }),
        throwsA(isA<FormatException>()),
      );
    });
  });
}
