// AUTO-GENERATED - DO NOT EDIT
// Generated by tools/xdr-generator/test/generate_json_tests.rb

import 'package:flutter_test/flutter_test.dart';
import 'package:stellar_flutter_sdk/stellar_flutter_sdk.dart';

void main() {
  group('SEP-0051 contract_meta renderings', () {
    test('XdrSCMetaV0 round trip', () {
      var original = XdrSCMetaV0('test_string', 'test_string');
      var json = original.toXdrJson();
      var fromDocument = XdrSCMetaV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCMetaV0.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCMetaV0 rejects an undeclared key', () {
      var original = XdrSCMetaV0('test_string', 'test_string');
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCMetaV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCMetaKind SC_META_V0 renders as sc_meta_v0', () {
      var member = XdrSCMetaKind.SC_META_V0;
      expect(member.value, 0);
      expect(member.toXdrJsonValue(), 'sc_meta_v0');
      expect(member.toXdrJson(), '"sc_meta_v0"');
      var parsed = XdrSCMetaKind.fromXdrJson('"sc_meta_v0"');
      expect(parsed.value, 0);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCMetaKind.fromXdrJsonValue('sc_meta_v0').value, 0);
    });
    test('XdrSCMetaKind rejects an undeclared member name', () {
      expect(
        () => XdrSCMetaKind.fromXdrJsonValue('xdr_json_undeclared_member'),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCMetaKind rejects an undeclared value', () {
      expect(
        () => XdrSCMetaKind(1).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCMetaEntry sc_meta_v0 arm round trip', () {
      var original = XdrSCMetaEntry(XdrSCMetaKind.SC_META_V0);
      original.v0 = XdrSCMetaV0('test_string', 'test_string');
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'sc_meta_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCMetaEntry.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCMetaEntry.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCMetaEntry rejects an undeclared discriminant', () {
      expect(
        () => XdrSCMetaEntry(XdrSCMetaKind(1)).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCMetaEntry rejects an undeclared arm key', () {
      expect(
        () => XdrSCMetaEntry.fromXdrJsonValue(<String, Object?>{
          'xdr_json_undeclared_arm': null,
        }),
        throwsA(isA<FormatException>()),
      );
    });
  });
}
