// AUTO-GENERATED - DO NOT EDIT
// Generated by tools/xdr-generator/test/generate_json_tests.rb

import 'package:flutter_test/flutter_test.dart';
import 'package:stellar_flutter_sdk/stellar_flutter_sdk.dart';

void main() {
  group('SEP-0051 contract_spec renderings', () {
    test('XdrSCSpecType SC_SPEC_TYPE_VAL renders as val', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_VAL;
      expect(member.value, 0);
      expect(member.toXdrJsonValue(), 'val');
      expect(member.toXdrJson(), '"val"');
      var parsed = XdrSCSpecType.fromXdrJson('"val"');
      expect(parsed.value, 0);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('val').value, 0);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_BOOL renders as bool', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_BOOL;
      expect(member.value, 1);
      expect(member.toXdrJsonValue(), 'bool');
      expect(member.toXdrJson(), '"bool"');
      var parsed = XdrSCSpecType.fromXdrJson('"bool"');
      expect(parsed.value, 1);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('bool').value, 1);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_VOID renders as void', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_VOID;
      expect(member.value, 2);
      expect(member.toXdrJsonValue(), 'void');
      expect(member.toXdrJson(), '"void"');
      var parsed = XdrSCSpecType.fromXdrJson('"void"');
      expect(parsed.value, 2);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('void').value, 2);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_ERROR renders as error', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_ERROR;
      expect(member.value, 3);
      expect(member.toXdrJsonValue(), 'error');
      expect(member.toXdrJson(), '"error"');
      var parsed = XdrSCSpecType.fromXdrJson('"error"');
      expect(parsed.value, 3);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('error').value, 3);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_U32 renders as u32', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_U32;
      expect(member.value, 4);
      expect(member.toXdrJsonValue(), 'u32');
      expect(member.toXdrJson(), '"u32"');
      var parsed = XdrSCSpecType.fromXdrJson('"u32"');
      expect(parsed.value, 4);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('u32').value, 4);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_I32 renders as i32', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_I32;
      expect(member.value, 5);
      expect(member.toXdrJsonValue(), 'i32');
      expect(member.toXdrJson(), '"i32"');
      var parsed = XdrSCSpecType.fromXdrJson('"i32"');
      expect(parsed.value, 5);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('i32').value, 5);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_U64 renders as u64', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_U64;
      expect(member.value, 6);
      expect(member.toXdrJsonValue(), 'u64');
      expect(member.toXdrJson(), '"u64"');
      var parsed = XdrSCSpecType.fromXdrJson('"u64"');
      expect(parsed.value, 6);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('u64').value, 6);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_I64 renders as i64', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_I64;
      expect(member.value, 7);
      expect(member.toXdrJsonValue(), 'i64');
      expect(member.toXdrJson(), '"i64"');
      var parsed = XdrSCSpecType.fromXdrJson('"i64"');
      expect(parsed.value, 7);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('i64').value, 7);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_TIMEPOINT renders as timepoint', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_TIMEPOINT;
      expect(member.value, 8);
      expect(member.toXdrJsonValue(), 'timepoint');
      expect(member.toXdrJson(), '"timepoint"');
      var parsed = XdrSCSpecType.fromXdrJson('"timepoint"');
      expect(parsed.value, 8);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('timepoint').value, 8);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_DURATION renders as duration', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_DURATION;
      expect(member.value, 9);
      expect(member.toXdrJsonValue(), 'duration');
      expect(member.toXdrJson(), '"duration"');
      var parsed = XdrSCSpecType.fromXdrJson('"duration"');
      expect(parsed.value, 9);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('duration').value, 9);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_U128 renders as u128', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_U128;
      expect(member.value, 10);
      expect(member.toXdrJsonValue(), 'u128');
      expect(member.toXdrJson(), '"u128"');
      var parsed = XdrSCSpecType.fromXdrJson('"u128"');
      expect(parsed.value, 10);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('u128').value, 10);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_I128 renders as i128', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_I128;
      expect(member.value, 11);
      expect(member.toXdrJsonValue(), 'i128');
      expect(member.toXdrJson(), '"i128"');
      var parsed = XdrSCSpecType.fromXdrJson('"i128"');
      expect(parsed.value, 11);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('i128').value, 11);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_U256 renders as u256', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_U256;
      expect(member.value, 12);
      expect(member.toXdrJsonValue(), 'u256');
      expect(member.toXdrJson(), '"u256"');
      var parsed = XdrSCSpecType.fromXdrJson('"u256"');
      expect(parsed.value, 12);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('u256').value, 12);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_I256 renders as i256', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_I256;
      expect(member.value, 13);
      expect(member.toXdrJsonValue(), 'i256');
      expect(member.toXdrJson(), '"i256"');
      var parsed = XdrSCSpecType.fromXdrJson('"i256"');
      expect(parsed.value, 13);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('i256').value, 13);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_BYTES renders as bytes', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_BYTES;
      expect(member.value, 14);
      expect(member.toXdrJsonValue(), 'bytes');
      expect(member.toXdrJson(), '"bytes"');
      var parsed = XdrSCSpecType.fromXdrJson('"bytes"');
      expect(parsed.value, 14);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('bytes').value, 14);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_STRING renders as string', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_STRING;
      expect(member.value, 16);
      expect(member.toXdrJsonValue(), 'string');
      expect(member.toXdrJson(), '"string"');
      var parsed = XdrSCSpecType.fromXdrJson('"string"');
      expect(parsed.value, 16);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('string').value, 16);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_SYMBOL renders as symbol', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_SYMBOL;
      expect(member.value, 17);
      expect(member.toXdrJsonValue(), 'symbol');
      expect(member.toXdrJson(), '"symbol"');
      var parsed = XdrSCSpecType.fromXdrJson('"symbol"');
      expect(parsed.value, 17);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('symbol').value, 17);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_ADDRESS renders as address', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_ADDRESS;
      expect(member.value, 19);
      expect(member.toXdrJsonValue(), 'address');
      expect(member.toXdrJson(), '"address"');
      var parsed = XdrSCSpecType.fromXdrJson('"address"');
      expect(parsed.value, 19);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('address').value, 19);
    });
    test(
      'XdrSCSpecType SC_SPEC_TYPE_MUXED_ADDRESS renders as muxed_address',
      () {
        var member = XdrSCSpecType.SC_SPEC_TYPE_MUXED_ADDRESS;
        expect(member.value, 20);
        expect(member.toXdrJsonValue(), 'muxed_address');
        expect(member.toXdrJson(), '"muxed_address"');
        var parsed = XdrSCSpecType.fromXdrJson('"muxed_address"');
        expect(parsed.value, 20);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecType.fromXdrJsonValue('muxed_address').value, 20);
      },
    );
    test('XdrSCSpecType SC_SPEC_TYPE_OPTION renders as option', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_OPTION;
      expect(member.value, 1000);
      expect(member.toXdrJsonValue(), 'option');
      expect(member.toXdrJson(), '"option"');
      var parsed = XdrSCSpecType.fromXdrJson('"option"');
      expect(parsed.value, 1000);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('option').value, 1000);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_RESULT renders as result', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_RESULT;
      expect(member.value, 1001);
      expect(member.toXdrJsonValue(), 'result');
      expect(member.toXdrJson(), '"result"');
      var parsed = XdrSCSpecType.fromXdrJson('"result"');
      expect(parsed.value, 1001);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('result').value, 1001);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_VEC renders as vec', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_VEC;
      expect(member.value, 1002);
      expect(member.toXdrJsonValue(), 'vec');
      expect(member.toXdrJson(), '"vec"');
      var parsed = XdrSCSpecType.fromXdrJson('"vec"');
      expect(parsed.value, 1002);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('vec').value, 1002);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_MAP renders as map', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_MAP;
      expect(member.value, 1004);
      expect(member.toXdrJsonValue(), 'map');
      expect(member.toXdrJson(), '"map"');
      var parsed = XdrSCSpecType.fromXdrJson('"map"');
      expect(parsed.value, 1004);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('map').value, 1004);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_TUPLE renders as tuple', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_TUPLE;
      expect(member.value, 1005);
      expect(member.toXdrJsonValue(), 'tuple');
      expect(member.toXdrJson(), '"tuple"');
      var parsed = XdrSCSpecType.fromXdrJson('"tuple"');
      expect(parsed.value, 1005);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('tuple').value, 1005);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_BYTES_N renders as bytes_n', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_BYTES_N;
      expect(member.value, 1006);
      expect(member.toXdrJsonValue(), 'bytes_n');
      expect(member.toXdrJson(), '"bytes_n"');
      var parsed = XdrSCSpecType.fromXdrJson('"bytes_n"');
      expect(parsed.value, 1006);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('bytes_n').value, 1006);
    });
    test('XdrSCSpecType SC_SPEC_TYPE_UDT renders as udt', () {
      var member = XdrSCSpecType.SC_SPEC_TYPE_UDT;
      expect(member.value, 2000);
      expect(member.toXdrJsonValue(), 'udt');
      expect(member.toXdrJson(), '"udt"');
      var parsed = XdrSCSpecType.fromXdrJson('"udt"');
      expect(parsed.value, 2000);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecType.fromXdrJsonValue('udt').value, 2000);
    });
    test('XdrSCSpecType rejects an undeclared member name', () {
      expect(
        () => XdrSCSpecType.fromXdrJsonValue('xdr_json_undeclared_member'),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecType rejects an undeclared value', () {
      expect(
        () => XdrSCSpecType(15).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeOption round trip', () {
      var original = XdrSCSpecTypeOption(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeOption.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeOption.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeOption rejects an undeclared key', () {
      var original = XdrSCSpecTypeOption(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecTypeOption.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeResult round trip', () {
      var original = XdrSCSpecTypeResult(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeResult.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeResult.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeResult rejects an undeclared key', () {
      var original = XdrSCSpecTypeResult(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecTypeResult.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeVec round trip', () {
      var original = XdrSCSpecTypeVec(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeVec.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeVec.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeVec rejects an undeclared key', () {
      var original = XdrSCSpecTypeVec(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecTypeVec.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeMap round trip', () {
      var original = XdrSCSpecTypeMap(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeMap.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeMap.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeMap rejects an undeclared key', () {
      var original = XdrSCSpecTypeMap(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecTypeMap.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeTuple round trip', () {
      var original = XdrSCSpecTypeTuple([
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      ]);
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeTuple.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeTuple.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeTuple rejects an undeclared key', () {
      var original = XdrSCSpecTypeTuple([
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      ]);
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecTypeTuple.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeBytesN round trip', () {
      var original = XdrSCSpecTypeBytesN(XdrUint32(42));
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeBytesN.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeBytesN.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeBytesN rejects an undeclared key', () {
      var original = XdrSCSpecTypeBytesN(XdrUint32(42));
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecTypeBytesN.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeUDT round trip', () {
      var original = XdrSCSpecTypeUDT('test_string');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeUDT.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeUDT.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeUDT rejects an undeclared key', () {
      var original = XdrSCSpecTypeUDT('test_string');
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecTypeUDT.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeDef val arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_VAL);
      expect(original.toXdrJsonValue(), 'val');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef bool arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL);
      expect(original.toXdrJsonValue(), 'bool');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef void arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_VOID);
      expect(original.toXdrJsonValue(), 'void');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef error arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_ERROR);
      expect(original.toXdrJsonValue(), 'error');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef u32 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_U32);
      expect(original.toXdrJsonValue(), 'u32');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef i32 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_I32);
      expect(original.toXdrJsonValue(), 'i32');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef u64 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_U64);
      expect(original.toXdrJsonValue(), 'u64');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef i64 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_I64);
      expect(original.toXdrJsonValue(), 'i64');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef timepoint arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_TIMEPOINT);
      expect(original.toXdrJsonValue(), 'timepoint');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef duration arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_DURATION);
      expect(original.toXdrJsonValue(), 'duration');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef u128 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_U128);
      expect(original.toXdrJsonValue(), 'u128');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef i128 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_I128);
      expect(original.toXdrJsonValue(), 'i128');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef u256 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_U256);
      expect(original.toXdrJsonValue(), 'u256');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef i256 arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_I256);
      expect(original.toXdrJsonValue(), 'i256');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef bytes arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BYTES);
      expect(original.toXdrJsonValue(), 'bytes');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef string arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_STRING);
      expect(original.toXdrJsonValue(), 'string');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef symbol arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_SYMBOL);
      expect(original.toXdrJsonValue(), 'symbol');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef address arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_ADDRESS);
      expect(original.toXdrJsonValue(), 'address');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef muxed_address arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_MUXED_ADDRESS);
      expect(original.toXdrJsonValue(), 'muxed_address');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef option arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_OPTION);
      original.option = XdrSCSpecTypeOption(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'option',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef result arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_RESULT);
      original.result = XdrSCSpecTypeResult(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'result',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef vec arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_VEC);
      original.vec = XdrSCSpecTypeVec(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'vec',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef map arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_MAP);
      original.map = XdrSCSpecTypeMap(
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'map',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef tuple arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_TUPLE);
      original.tuple = XdrSCSpecTypeTuple([
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      ]);
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'tuple',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef bytes_n arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BYTES_N);
      original.bytesN = XdrSCSpecTypeBytesN(XdrUint32(42));
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'bytes_n',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef udt arm round trip', () {
      var original = XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_UDT);
      original.udt = XdrSCSpecTypeUDT('test_string');
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'udt',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecTypeDef.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecTypeDef.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecTypeDef rejects an undeclared discriminant', () {
      expect(
        () => XdrSCSpecTypeDef(XdrSCSpecType(15)).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeDef rejects an undeclared arm name', () {
      expect(
        () => XdrSCSpecTypeDef.fromXdrJsonValue('xdr_json_undeclared_arm'),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecTypeDef rejects an undeclared arm key', () {
      expect(
        () => XdrSCSpecTypeDef.fromXdrJsonValue(<String, Object?>{
          'xdr_json_undeclared_arm': null,
        }),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTStructFieldV0 round trip', () {
      var original = XdrSCSpecUDTStructFieldV0(
        'test_string',
        'test_string',
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTStructFieldV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTStructFieldV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTStructFieldV0 rejects an undeclared key', () {
      var original = XdrSCSpecUDTStructFieldV0(
        'test_string',
        'test_string',
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTStructFieldV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTStructV0 round trip', () {
      var original =
          XdrSCSpecUDTStructV0('test_string', 'test_string', 'test_string', [
            XdrSCSpecUDTStructFieldV0(
              'test_string',
              'test_string',
              XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
            ),
          ]);
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTStructV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTStructV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTStructV0 rejects an undeclared key', () {
      var original =
          XdrSCSpecUDTStructV0('test_string', 'test_string', 'test_string', [
            XdrSCSpecUDTStructFieldV0(
              'test_string',
              'test_string',
              XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
            ),
          ]);
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTStructV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTUnionCaseVoidV0 round trip', () {
      var original = XdrSCSpecUDTUnionCaseVoidV0('test_string', 'test_string');
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTUnionCaseVoidV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTUnionCaseVoidV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTUnionCaseVoidV0 rejects an undeclared key', () {
      var original = XdrSCSpecUDTUnionCaseVoidV0('test_string', 'test_string');
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTUnionCaseVoidV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTUnionCaseTupleV0 round trip', () {
      var original = XdrSCSpecUDTUnionCaseTupleV0(
        'test_string',
        'test_string',
        [XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL)],
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTUnionCaseTupleV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTUnionCaseTupleV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTUnionCaseTupleV0 rejects an undeclared key', () {
      var original = XdrSCSpecUDTUnionCaseTupleV0(
        'test_string',
        'test_string',
        [XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL)],
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTUnionCaseTupleV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test(
      'XdrSCSpecUDTUnionCaseV0Kind SC_SPEC_UDT_UNION_CASE_VOID_V0 renders as void_v0',
      () {
        var member = XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_VOID_V0;
        expect(member.value, 0);
        expect(member.toXdrJsonValue(), 'void_v0');
        expect(member.toXdrJson(), '"void_v0"');
        var parsed = XdrSCSpecUDTUnionCaseV0Kind.fromXdrJson('"void_v0"');
        expect(parsed.value, 0);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(
          XdrSCSpecUDTUnionCaseV0Kind.fromXdrJsonValue('void_v0').value,
          0,
        );
      },
    );
    test(
      'XdrSCSpecUDTUnionCaseV0Kind SC_SPEC_UDT_UNION_CASE_TUPLE_V0 renders as tuple_v0',
      () {
        var member =
            XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_TUPLE_V0;
        expect(member.value, 1);
        expect(member.toXdrJsonValue(), 'tuple_v0');
        expect(member.toXdrJson(), '"tuple_v0"');
        var parsed = XdrSCSpecUDTUnionCaseV0Kind.fromXdrJson('"tuple_v0"');
        expect(parsed.value, 1);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(
          XdrSCSpecUDTUnionCaseV0Kind.fromXdrJsonValue('tuple_v0').value,
          1,
        );
      },
    );
    test('XdrSCSpecUDTUnionCaseV0Kind rejects an undeclared member name', () {
      expect(
        () => XdrSCSpecUDTUnionCaseV0Kind.fromXdrJsonValue(
          'xdr_json_undeclared_member',
        ),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTUnionCaseV0Kind rejects an undeclared value', () {
      expect(
        () => XdrSCSpecUDTUnionCaseV0Kind(2).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTUnionCaseV0 void_v0 arm round trip', () {
      var original = XdrSCSpecUDTUnionCaseV0(
        XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_VOID_V0,
      );
      original.voidCase = XdrSCSpecUDTUnionCaseVoidV0(
        'test_string',
        'test_string',
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'void_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTUnionCaseV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTUnionCaseV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTUnionCaseV0 tuple_v0 arm round trip', () {
      var original = XdrSCSpecUDTUnionCaseV0(
        XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_TUPLE_V0,
      );
      original.tupleCase = XdrSCSpecUDTUnionCaseTupleV0(
        'test_string',
        'test_string',
        [XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL)],
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'tuple_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTUnionCaseV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTUnionCaseV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTUnionCaseV0 rejects an undeclared discriminant', () {
      expect(
        () => XdrSCSpecUDTUnionCaseV0(
          XdrSCSpecUDTUnionCaseV0Kind(2),
        ).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTUnionCaseV0 rejects an undeclared arm key', () {
      expect(
        () => XdrSCSpecUDTUnionCaseV0.fromXdrJsonValue(<String, Object?>{
          'xdr_json_undeclared_arm': null,
        }),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTUnionV0 round trip', () {
      var original =
          XdrSCSpecUDTUnionV0('test_string', 'test_string', 'test_string', [
            (XdrSCSpecUDTUnionCaseV0(
                XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_VOID_V0,
              )
              ..voidCase = XdrSCSpecUDTUnionCaseVoidV0(
                'test_string',
                'test_string',
              )),
          ]);
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTUnionV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTUnionV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTUnionV0 rejects an undeclared key', () {
      var original =
          XdrSCSpecUDTUnionV0('test_string', 'test_string', 'test_string', [
            (XdrSCSpecUDTUnionCaseV0(
                XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_VOID_V0,
              )
              ..voidCase = XdrSCSpecUDTUnionCaseVoidV0(
                'test_string',
                'test_string',
              )),
          ]);
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTUnionV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTEnumCaseV0 round trip', () {
      var original = XdrSCSpecUDTEnumCaseV0(
        'test_string',
        'test_string',
        XdrUint32(42),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTEnumCaseV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTEnumCaseV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTEnumCaseV0 rejects an undeclared key', () {
      var original = XdrSCSpecUDTEnumCaseV0(
        'test_string',
        'test_string',
        XdrUint32(42),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTEnumCaseV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTEnumV0 round trip', () {
      var original = XdrSCSpecUDTEnumV0(
        'test_string',
        'test_string',
        'test_string',
        [XdrSCSpecUDTEnumCaseV0('test_string', 'test_string', XdrUint32(42))],
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTEnumV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTEnumV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTEnumV0 rejects an undeclared key', () {
      var original = XdrSCSpecUDTEnumV0(
        'test_string',
        'test_string',
        'test_string',
        [XdrSCSpecUDTEnumCaseV0('test_string', 'test_string', XdrUint32(42))],
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTEnumV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTErrorEnumCaseV0 round trip', () {
      var original = XdrSCSpecUDTErrorEnumCaseV0(
        'test_string',
        'test_string',
        XdrUint32(42),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTErrorEnumCaseV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTErrorEnumCaseV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTErrorEnumCaseV0 rejects an undeclared key', () {
      var original = XdrSCSpecUDTErrorEnumCaseV0(
        'test_string',
        'test_string',
        XdrUint32(42),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTErrorEnumCaseV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecUDTErrorEnumV0 round trip', () {
      var original = XdrSCSpecUDTErrorEnumV0(
        'test_string',
        'test_string',
        'test_string',
        [
          XdrSCSpecUDTErrorEnumCaseV0(
            'test_string',
            'test_string',
            XdrUint32(42),
          ),
        ],
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecUDTErrorEnumV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecUDTErrorEnumV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecUDTErrorEnumV0 rejects an undeclared key', () {
      var original = XdrSCSpecUDTErrorEnumV0(
        'test_string',
        'test_string',
        'test_string',
        [
          XdrSCSpecUDTErrorEnumCaseV0(
            'test_string',
            'test_string',
            XdrUint32(42),
          ),
        ],
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecUDTErrorEnumV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecFunctionInputV0 round trip', () {
      var original = XdrSCSpecFunctionInputV0(
        'test_string',
        'test_string',
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecFunctionInputV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecFunctionInputV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecFunctionInputV0 rejects an undeclared key', () {
      var original = XdrSCSpecFunctionInputV0(
        'test_string',
        'test_string',
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecFunctionInputV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecFunctionV0 round trip', () {
      var original = XdrSCSpecFunctionV0(
        'test_string',
        'test_string',
        [
          XdrSCSpecFunctionInputV0(
            'test_string',
            'test_string',
            XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
          ),
        ],
        [XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL)],
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecFunctionV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecFunctionV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecFunctionV0 rejects an undeclared key', () {
      var original = XdrSCSpecFunctionV0(
        'test_string',
        'test_string',
        [
          XdrSCSpecFunctionInputV0(
            'test_string',
            'test_string',
            XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
          ),
        ],
        [XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL)],
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecFunctionV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test(
      'XdrSCSpecEventParamLocationV0 SC_SPEC_EVENT_PARAM_LOCATION_DATA renders as data',
      () {
        var member =
            XdrSCSpecEventParamLocationV0.SC_SPEC_EVENT_PARAM_LOCATION_DATA;
        expect(member.value, 0);
        expect(member.toXdrJsonValue(), 'data');
        expect(member.toXdrJson(), '"data"');
        var parsed = XdrSCSpecEventParamLocationV0.fromXdrJson('"data"');
        expect(parsed.value, 0);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecEventParamLocationV0.fromXdrJsonValue('data').value, 0);
      },
    );
    test(
      'XdrSCSpecEventParamLocationV0 SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST renders as topic_list',
      () {
        var member = XdrSCSpecEventParamLocationV0
            .SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST;
        expect(member.value, 1);
        expect(member.toXdrJsonValue(), 'topic_list');
        expect(member.toXdrJson(), '"topic_list"');
        var parsed = XdrSCSpecEventParamLocationV0.fromXdrJson('"topic_list"');
        expect(parsed.value, 1);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(
          XdrSCSpecEventParamLocationV0.fromXdrJsonValue('topic_list').value,
          1,
        );
      },
    );
    test('XdrSCSpecEventParamLocationV0 rejects an undeclared member name', () {
      expect(
        () => XdrSCSpecEventParamLocationV0.fromXdrJsonValue(
          'xdr_json_undeclared_member',
        ),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecEventParamLocationV0 rejects an undeclared value', () {
      expect(
        () => XdrSCSpecEventParamLocationV0(2).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecEventParamV0 round trip', () {
      var original = XdrSCSpecEventParamV0(
        'test_string',
        'test_string',
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecEventParamLocationV0.SC_SPEC_EVENT_PARAM_LOCATION_DATA,
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEventParamV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEventParamV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEventParamV0 rejects an undeclared key', () {
      var original = XdrSCSpecEventParamV0(
        'test_string',
        'test_string',
        XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
        XdrSCSpecEventParamLocationV0.SC_SPEC_EVENT_PARAM_LOCATION_DATA,
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecEventParamV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test(
      'XdrSCSpecEventDataFormat SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE renders as single_value',
      () {
        var member =
            XdrSCSpecEventDataFormat.SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE;
        expect(member.value, 0);
        expect(member.toXdrJsonValue(), 'single_value');
        expect(member.toXdrJson(), '"single_value"');
        var parsed = XdrSCSpecEventDataFormat.fromXdrJson('"single_value"');
        expect(parsed.value, 0);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(
          XdrSCSpecEventDataFormat.fromXdrJsonValue('single_value').value,
          0,
        );
      },
    );
    test(
      'XdrSCSpecEventDataFormat SC_SPEC_EVENT_DATA_FORMAT_VEC renders as vec',
      () {
        var member = XdrSCSpecEventDataFormat.SC_SPEC_EVENT_DATA_FORMAT_VEC;
        expect(member.value, 1);
        expect(member.toXdrJsonValue(), 'vec');
        expect(member.toXdrJson(), '"vec"');
        var parsed = XdrSCSpecEventDataFormat.fromXdrJson('"vec"');
        expect(parsed.value, 1);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecEventDataFormat.fromXdrJsonValue('vec').value, 1);
      },
    );
    test(
      'XdrSCSpecEventDataFormat SC_SPEC_EVENT_DATA_FORMAT_MAP renders as map',
      () {
        var member = XdrSCSpecEventDataFormat.SC_SPEC_EVENT_DATA_FORMAT_MAP;
        expect(member.value, 2);
        expect(member.toXdrJsonValue(), 'map');
        expect(member.toXdrJson(), '"map"');
        var parsed = XdrSCSpecEventDataFormat.fromXdrJson('"map"');
        expect(parsed.value, 2);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecEventDataFormat.fromXdrJsonValue('map').value, 2);
      },
    );
    test('XdrSCSpecEventDataFormat rejects an undeclared member name', () {
      expect(
        () => XdrSCSpecEventDataFormat.fromXdrJsonValue(
          'xdr_json_undeclared_member',
        ),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecEventDataFormat rejects an undeclared value', () {
      expect(
        () => XdrSCSpecEventDataFormat(3).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecEventV0 round trip', () {
      var original = XdrSCSpecEventV0(
        'test_string',
        'test_string',
        'test_string',
        ['test_string'],
        [
          XdrSCSpecEventParamV0(
            'test_string',
            'test_string',
            XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
            XdrSCSpecEventParamLocationV0.SC_SPEC_EVENT_PARAM_LOCATION_DATA,
          ),
        ],
        XdrSCSpecEventDataFormat.SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE,
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEventV0.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEventV0.fromXdrJsonValue(
        original.toXdrJsonValue(),
      );
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEventV0 rejects an undeclared key', () {
      var original = XdrSCSpecEventV0(
        'test_string',
        'test_string',
        'test_string',
        ['test_string'],
        [
          XdrSCSpecEventParamV0(
            'test_string',
            'test_string',
            XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
            XdrSCSpecEventParamLocationV0.SC_SPEC_EVENT_PARAM_LOCATION_DATA,
          ),
        ],
        XdrSCSpecEventDataFormat.SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE,
      );
      var object = <String, Object?>{
        ...(original.toXdrJsonValue() as Map<String, Object?>),
        'xdr_json_undeclared_key': null,
      };
      expect(
        () => XdrSCSpecEventV0.fromXdrJsonValue(object),
        throwsA(isA<FormatException>()),
      );
    });
    test(
      'XdrSCSpecEntryKind SC_SPEC_ENTRY_FUNCTION_V0 renders as function_v0',
      () {
        var member = XdrSCSpecEntryKind.SC_SPEC_ENTRY_FUNCTION_V0;
        expect(member.value, 0);
        expect(member.toXdrJsonValue(), 'function_v0');
        expect(member.toXdrJson(), '"function_v0"');
        var parsed = XdrSCSpecEntryKind.fromXdrJson('"function_v0"');
        expect(parsed.value, 0);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecEntryKind.fromXdrJsonValue('function_v0').value, 0);
      },
    );
    test(
      'XdrSCSpecEntryKind SC_SPEC_ENTRY_UDT_STRUCT_V0 renders as udt_struct_v0',
      () {
        var member = XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_STRUCT_V0;
        expect(member.value, 1);
        expect(member.toXdrJsonValue(), 'udt_struct_v0');
        expect(member.toXdrJson(), '"udt_struct_v0"');
        var parsed = XdrSCSpecEntryKind.fromXdrJson('"udt_struct_v0"');
        expect(parsed.value, 1);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecEntryKind.fromXdrJsonValue('udt_struct_v0').value, 1);
      },
    );
    test(
      'XdrSCSpecEntryKind SC_SPEC_ENTRY_UDT_UNION_V0 renders as udt_union_v0',
      () {
        var member = XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_UNION_V0;
        expect(member.value, 2);
        expect(member.toXdrJsonValue(), 'udt_union_v0');
        expect(member.toXdrJson(), '"udt_union_v0"');
        var parsed = XdrSCSpecEntryKind.fromXdrJson('"udt_union_v0"');
        expect(parsed.value, 2);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecEntryKind.fromXdrJsonValue('udt_union_v0').value, 2);
      },
    );
    test(
      'XdrSCSpecEntryKind SC_SPEC_ENTRY_UDT_ENUM_V0 renders as udt_enum_v0',
      () {
        var member = XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_ENUM_V0;
        expect(member.value, 3);
        expect(member.toXdrJsonValue(), 'udt_enum_v0');
        expect(member.toXdrJson(), '"udt_enum_v0"');
        var parsed = XdrSCSpecEntryKind.fromXdrJson('"udt_enum_v0"');
        expect(parsed.value, 3);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(XdrSCSpecEntryKind.fromXdrJsonValue('udt_enum_v0').value, 3);
      },
    );
    test(
      'XdrSCSpecEntryKind SC_SPEC_ENTRY_UDT_ERROR_ENUM_V0 renders as udt_error_enum_v0',
      () {
        var member = XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_ERROR_ENUM_V0;
        expect(member.value, 4);
        expect(member.toXdrJsonValue(), 'udt_error_enum_v0');
        expect(member.toXdrJson(), '"udt_error_enum_v0"');
        var parsed = XdrSCSpecEntryKind.fromXdrJson('"udt_error_enum_v0"');
        expect(parsed.value, 4);
        expect(
          parsed.toBase64EncodedXdrString(),
          member.toBase64EncodedXdrString(),
        );
        expect(
          XdrSCSpecEntryKind.fromXdrJsonValue('udt_error_enum_v0').value,
          4,
        );
      },
    );
    test('XdrSCSpecEntryKind SC_SPEC_ENTRY_EVENT_V0 renders as event_v0', () {
      var member = XdrSCSpecEntryKind.SC_SPEC_ENTRY_EVENT_V0;
      expect(member.value, 5);
      expect(member.toXdrJsonValue(), 'event_v0');
      expect(member.toXdrJson(), '"event_v0"');
      var parsed = XdrSCSpecEntryKind.fromXdrJson('"event_v0"');
      expect(parsed.value, 5);
      expect(
        parsed.toBase64EncodedXdrString(),
        member.toBase64EncodedXdrString(),
      );
      expect(XdrSCSpecEntryKind.fromXdrJsonValue('event_v0').value, 5);
    });
    test('XdrSCSpecEntryKind rejects an undeclared member name', () {
      expect(
        () => XdrSCSpecEntryKind.fromXdrJsonValue('xdr_json_undeclared_member'),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecEntryKind rejects an undeclared value', () {
      expect(
        () => XdrSCSpecEntryKind(6).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecEntry function_v0 arm round trip', () {
      var original = XdrSCSpecEntry(
        XdrSCSpecEntryKind.SC_SPEC_ENTRY_FUNCTION_V0,
      );
      original.functionV0 = XdrSCSpecFunctionV0(
        'test_string',
        'test_string',
        [
          XdrSCSpecFunctionInputV0(
            'test_string',
            'test_string',
            XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
          ),
        ],
        [XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL)],
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'function_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEntry.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEntry.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEntry udt_struct_v0 arm round trip', () {
      var original = XdrSCSpecEntry(
        XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_STRUCT_V0,
      );
      original.udtStructV0 =
          XdrSCSpecUDTStructV0('test_string', 'test_string', 'test_string', [
            XdrSCSpecUDTStructFieldV0(
              'test_string',
              'test_string',
              XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
            ),
          ]);
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'udt_struct_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEntry.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEntry.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEntry udt_union_v0 arm round trip', () {
      var original = XdrSCSpecEntry(
        XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_UNION_V0,
      );
      original.udtUnionV0 =
          (XdrSCSpecUDTUnionV0('test_string', 'test_string', 'test_string', [
            (XdrSCSpecUDTUnionCaseV0(
                XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_VOID_V0,
              )
              ..voidCase = XdrSCSpecUDTUnionCaseVoidV0(
                'test_string',
                'test_string',
              )),
          ]));
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'udt_union_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEntry.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEntry.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEntry udt_enum_v0 arm round trip', () {
      var original = XdrSCSpecEntry(
        XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_ENUM_V0,
      );
      original.udtEnumV0 = XdrSCSpecUDTEnumV0(
        'test_string',
        'test_string',
        'test_string',
        [XdrSCSpecUDTEnumCaseV0('test_string', 'test_string', XdrUint32(42))],
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'udt_enum_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEntry.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEntry.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEntry udt_error_enum_v0 arm round trip', () {
      var original = XdrSCSpecEntry(
        XdrSCSpecEntryKind.SC_SPEC_ENTRY_UDT_ERROR_ENUM_V0,
      );
      original.udtErrorEnumV0 = XdrSCSpecUDTErrorEnumV0(
        'test_string',
        'test_string',
        'test_string',
        [
          XdrSCSpecUDTErrorEnumCaseV0(
            'test_string',
            'test_string',
            XdrUint32(42),
          ),
        ],
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'udt_error_enum_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEntry.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEntry.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEntry event_v0 arm round trip', () {
      var original = XdrSCSpecEntry(XdrSCSpecEntryKind.SC_SPEC_ENTRY_EVENT_V0);
      original.eventV0 = XdrSCSpecEventV0(
        'test_string',
        'test_string',
        'test_string',
        ['test_string'],
        [
          XdrSCSpecEventParamV0(
            'test_string',
            'test_string',
            XdrSCSpecTypeDef(XdrSCSpecType.SC_SPEC_TYPE_BOOL),
            XdrSCSpecEventParamLocationV0.SC_SPEC_EVENT_PARAM_LOCATION_DATA,
          ),
        ],
        XdrSCSpecEventDataFormat.SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE,
      );
      expect(
        (original.toXdrJsonValue() as Map<String, Object?>).keys.single,
        'event_v0',
      );
      var json = original.toXdrJson();
      var fromDocument = XdrSCSpecEntry.fromXdrJson(json);
      expect(fromDocument.toXdrJson(), json);
      expect(
        fromDocument.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
      var fromTree = XdrSCSpecEntry.fromXdrJsonValue(original.toXdrJsonValue());
      expect(fromTree.toXdrJsonValue(), original.toXdrJsonValue());
      expect(
        fromTree.toBase64EncodedXdrString(),
        original.toBase64EncodedXdrString(),
      );
    });
    test('XdrSCSpecEntry rejects an undeclared discriminant', () {
      expect(
        () => XdrSCSpecEntry(XdrSCSpecEntryKind(6)).toXdrJsonValue(),
        throwsA(isA<FormatException>()),
      );
    });
    test('XdrSCSpecEntry rejects an undeclared arm key', () {
      expect(
        () => XdrSCSpecEntry.fromXdrJsonValue(<String, Object?>{
          'xdr_json_undeclared_arm': null,
        }),
        throwsA(isA<FormatException>()),
      );
    });
  });
}
