// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_peer_address_ip.dart';
import 'xdr_uint32.dart';

class XdrPeerAddress {

  XdrPeerAddressIp _ip;
  XdrPeerAddressIp get ip => this._ip;
  set ip(XdrPeerAddressIp value) => this._ip = value;

  XdrUint32 _port;
  XdrUint32 get port => this._port;
  set port(XdrUint32 value) => this._port = value;

  XdrUint32 _numFailures;
  XdrUint32 get numFailures => this._numFailures;
  set numFailures(XdrUint32 value) => this._numFailures = value;

  XdrPeerAddress(this._ip, this._port, this._numFailures);

  static void encode(XdrDataOutputStream stream, XdrPeerAddress encodedPeerAddress) {
    XdrPeerAddressIp.encode(stream, encodedPeerAddress.ip);
    XdrUint32.encode(stream, encodedPeerAddress.port);
    XdrUint32.encode(stream, encodedPeerAddress.numFailures);
  }

  static XdrPeerAddress decode(XdrDataInputStream stream) {
    XdrPeerAddressIp ip = XdrPeerAddressIp.decode(stream);
    XdrUint32 port = XdrUint32.decode(stream);
    XdrUint32 numFailures = XdrUint32.decode(stream);
    return XdrPeerAddress(ip, port, numFailures);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrPeerAddress.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrPeerAddress fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrPeerAddress.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _ip.toTxRep('$prefix.ip', lines);
    _port.toTxRep('$prefix.port', lines);
    _numFailures.toTxRep('$prefix.numFailures', lines);
  }

  static XdrPeerAddress fromTxRep(Map<String, String> map, String prefix) {
    XdrPeerAddressIp ip = XdrPeerAddressIp.fromTxRep(map, '$prefix.ip');
    XdrUint32 port = XdrUint32.fromTxRep(map, '$prefix.port');
    XdrUint32 numFailures = XdrUint32.fromTxRep(map, '$prefix.numFailures');
    return XdrPeerAddress(ip, port, numFailures);
  }
}
