// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';

class XdrSCSpecTypeUDT {
  String _name;
  String get name => this._name;
  set name(String value) => this._name = value;

  XdrSCSpecTypeUDT(this._name);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCSpecTypeUDT encodedSCSpecTypeUDT,
  ) {
    stream.writeString(encodedSCSpecTypeUDT.name);
  }

  static XdrSCSpecTypeUDT decode(XdrDataInputStream stream) {
    String name = stream.readString();
    return XdrSCSpecTypeUDT(name);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCSpecTypeUDT.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCSpecTypeUDT fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCSpecTypeUDT.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.name: ${TxRepHelper.escapeString(_name)}');
  }

  static XdrSCSpecTypeUDT fromTxRep(Map<String, String> map, String prefix) {
    String name = TxRepHelper.unescapeString(
      TxRepHelper.getValue(map, '$prefix.name') ?? '',
    );
    return XdrSCSpecTypeUDT(name);
  }
}
