// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_ledger_close_value_signature.dart';
import 'xdr_stellar_value_type.dart';

class XdrStellarValueExt {
  XdrStellarValueType _v;

  XdrStellarValueType get discriminant => this._v;

  set discriminant(XdrStellarValueType value) => this._v = value;

  XdrLedgerCloseValueSignature? _lcValueSignature;

  XdrLedgerCloseValueSignature? get lcValueSignature => this._lcValueSignature;

  XdrStellarValueExt(this._v);

  set lcValueSignature(XdrLedgerCloseValueSignature? value) =>
      this._lcValueSignature = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrStellarValueExt encodedStellarValueExt,
  ) {
    stream.writeInt(encodedStellarValueExt.discriminant.value);
    switch (encodedStellarValueExt.discriminant) {
      case XdrStellarValueType.STELLAR_VALUE_BASIC:
        break;
      case XdrStellarValueType.STELLAR_VALUE_SIGNED:
        XdrLedgerCloseValueSignature.encode(
          stream,
          encodedStellarValueExt._lcValueSignature!,
        );
        break;
      default:
        break;
    }
  }

  static XdrStellarValueExt decode(XdrDataInputStream stream) {
    XdrStellarValueExt decodedStellarValueExt = XdrStellarValueExt(
      XdrStellarValueType.decode(stream),
    );
    switch (decodedStellarValueExt.discriminant) {
      case XdrStellarValueType.STELLAR_VALUE_BASIC:
        break;
      case XdrStellarValueType.STELLAR_VALUE_SIGNED:
        decodedStellarValueExt._lcValueSignature =
            XdrLedgerCloseValueSignature.decode(stream);
        break;
      default:
        break;
    }
    return decodedStellarValueExt;
  }
}
