// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrHmacSha256Key {
  Uint8List _key;
  Uint8List get key => this._key;
  set key(Uint8List value) => this._key = value;

  XdrHmacSha256Key(this._key);

  static void encode(
    XdrDataOutputStream stream,
    XdrHmacSha256Key encodedHmacSha256Key,
  ) {
    stream.write(encodedHmacSha256Key.key);
  }

  static XdrHmacSha256Key decode(XdrDataInputStream stream) {
    Uint8List key = stream.readBytes(32);
    return XdrHmacSha256Key(key);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrHmacSha256Key.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrHmacSha256Key fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrHmacSha256Key.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrHmacSha256Key');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrHmacSha256Key.
  static XdrHmacSha256Key fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrHmacSha256Key'),
  );

  /// Returns the SEP-0051 rendering of this XdrHmacSha256Key.
  Object? toXdrJsonValue() => <String, Object?>{
    'key': XdrJsonHelper.hex(_key, type: 'XdrHmacSha256Key', key: 'key'),
  };

  /// Reads a XdrHmacSha256Key from its SEP-0051 rendering.
  static XdrHmacSha256Key fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrHmacSha256Key',
      allowedKeys: const <String>{'key'},
    );
    final Object? jsonKey = XdrJsonHelper.readField(
      object,
      'key',
      type: 'XdrHmacSha256Key',
    );
    return XdrHmacSha256Key(
      XdrJsonHelper.readHex(
        jsonKey,
        type: 'XdrHmacSha256Key',
        key: 'key',
        expectedLength: 32,
      ),
    );
  }
}
