// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_operation_meta.dart';
import 'xdr_transaction_meta_v1.dart';
import 'xdr_transaction_meta_v2.dart';
import 'xdr_transaction_meta_v3.dart';
import 'xdr_transaction_meta_v4.dart';

class XdrTransactionMeta {
  int _v;

  int get discriminant => this._v;
  set discriminant(int value) => this._v = value;

  /// Alias for [discriminant], the original XDR field name.
  int get v => this._v;
  set v(int value) => this._v = value;

  List<XdrOperationMeta>? _operations;

  List<XdrOperationMeta>? get operations => this._operations;

  XdrTransactionMetaV1? _v1;

  XdrTransactionMetaV1? get v1 => this._v1;

  XdrTransactionMetaV2? _v2;

  XdrTransactionMetaV2? get v2 => this._v2;

  XdrTransactionMetaV3? _v3;

  XdrTransactionMetaV3? get v3 => this._v3;

  XdrTransactionMetaV4? _v4;

  XdrTransactionMetaV4? get v4 => this._v4;

  XdrTransactionMeta(this._v);

  set operations(List<XdrOperationMeta>? value) => this._operations = value;

  set v1(XdrTransactionMetaV1? value) => this._v1 = value;

  set v2(XdrTransactionMetaV2? value) => this._v2 = value;

  set v3(XdrTransactionMetaV3? value) => this._v3 = value;

  set v4(XdrTransactionMetaV4? value) => this._v4 = value;

  static void encode(XdrDataOutputStream stream, XdrTransactionMeta encodedTransactionMeta) {
    stream.writeInt(encodedTransactionMeta.discriminant);
    switch (encodedTransactionMeta.discriminant) {
      case 0:
        int operationssize = encodedTransactionMeta._operations!.length;
        stream.writeInt(operationssize);
        for (int i = 0; i < operationssize; i++) {
          XdrOperationMeta.encode(stream, encodedTransactionMeta._operations![i]);
        }
        break;
      case 1:
        XdrTransactionMetaV1.encode(stream, encodedTransactionMeta._v1!);
        break;
      case 2:
        XdrTransactionMetaV2.encode(stream, encodedTransactionMeta._v2!);
        break;
      case 3:
        XdrTransactionMetaV3.encode(stream, encodedTransactionMeta._v3!);
        break;
      case 4:
        XdrTransactionMetaV4.encode(stream, encodedTransactionMeta._v4!);
        break;
      default:
        break;
    }
  }

  static XdrTransactionMeta decode(XdrDataInputStream stream) {
    int discriminant = stream.readInt();
    XdrTransactionMeta decodedTransactionMeta = XdrTransactionMeta(discriminant);
    switch (decodedTransactionMeta.discriminant) {
      case 0:
        int operationssize = stream.readInt();
        decodedTransactionMeta._operations = List<XdrOperationMeta>.empty(growable: true);
        for (int i = 0; i < operationssize; i++) {
          decodedTransactionMeta._operations!.add(XdrOperationMeta.decode(stream));
        }
        break;
      case 1:
        decodedTransactionMeta._v1 = XdrTransactionMetaV1.decode(stream);
        break;
      case 2:
        decodedTransactionMeta._v2 = XdrTransactionMetaV2.decode(stream);
        break;
      case 3:
        decodedTransactionMeta._v3 = XdrTransactionMetaV3.decode(stream);
        break;
      case 4:
        decodedTransactionMeta._v4 = XdrTransactionMetaV4.decode(stream);
        break;
      default:
        break;
    }
    return decodedTransactionMeta;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrTransactionMeta.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrTransactionMeta fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrTransactionMeta.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.v: $discriminant');
    switch (discriminant) {
      case 0:
        lines.add('$prefix.operations.len: ${_operations!.length}');
        for (int i = 0; i < _operations!.length; i++) {
          _operations![i].toTxRep('$prefix.operations[$i]', lines);
        }
        break;
      case 1:
        _v1!.toTxRep('$prefix.v1', lines);
        break;
      case 2:
        _v2!.toTxRep('$prefix.v2', lines);
        break;
      case 3:
        _v3!.toTxRep('$prefix.v3', lines);
        break;
      case 4:
        _v4!.toTxRep('$prefix.v4', lines);
        break;
      default:
        break;
    }
  }

  static XdrTransactionMeta fromTxRep(Map<String, String> map, String prefix) {
    int disc = TxRepHelper.parseInt(TxRepHelper.getValue(map, '$prefix.v') ?? '0');
    XdrTransactionMeta result = XdrTransactionMeta(disc);
    switch (result.discriminant) {
      case 0:
        int operationsLen = TxRepHelper.parseInt(TxRepHelper.getValue(map, '$prefix.operations.len') ?? '0');
        result._operations = [];
        for (int i = 0; i < operationsLen; i++) {
          result._operations!.add(XdrOperationMeta.fromTxRep(map, '$prefix.operations[$i]'));
        }
        break;
      case 1:
        result._v1 = XdrTransactionMetaV1.fromTxRep(map, '$prefix.v1');
        break;
      case 2:
        result._v2 = XdrTransactionMetaV2.fromTxRep(map, '$prefix.v2');
        break;
      case 3:
        result._v3 = XdrTransactionMetaV3.fromTxRep(map, '$prefix.v3');
        break;
      case 4:
        result._v4 = XdrTransactionMetaV4.fromTxRep(map, '$prefix.v4');
        break;
      default:
        break;
    }
    return result;
  }
}
