// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_hash.dart';
import 'xdr_transaction_phase.dart';

class XdrTransactionSetV1 {
  XdrHash _previousLedgerHash;
  XdrHash get previousLedgerHash => this._previousLedgerHash;
  set previousLedgerHash(XdrHash value) => this._previousLedgerHash = value;

  List<XdrTransactionPhase> _phases;
  List<XdrTransactionPhase> get phases => this._phases;
  set phases(List<XdrTransactionPhase> value) => this._phases = value;

  XdrTransactionSetV1(this._previousLedgerHash, this._phases);

  static void encode(
    XdrDataOutputStream stream,
    XdrTransactionSetV1 encodedTransactionSetV1,
  ) {
    XdrHash.encode(stream, encodedTransactionSetV1.previousLedgerHash);
    int phasessize = encodedTransactionSetV1.phases.length;
    stream.writeInt(phasessize);
    for (int i = 0; i < phasessize; i++) {
      XdrTransactionPhase.encode(stream, encodedTransactionSetV1.phases[i]);
    }
  }

  static XdrTransactionSetV1 decode(XdrDataInputStream stream) {
    XdrHash previousLedgerHash = XdrHash.decode(stream);
    int phasessize = stream.readInt();
    List<XdrTransactionPhase> phases = List<XdrTransactionPhase>.empty(
      growable: true,
    );
    for (int i = 0; i < phasessize; i++) {
      phases.add(XdrTransactionPhase.decode(stream));
    }
    return XdrTransactionSetV1(previousLedgerHash, phases);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrTransactionSetV1.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrTransactionSetV1 fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrTransactionSetV1.decode(XdrDataInputStream(bytes));
  }
}
