// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_allow_trust_op.dart';
import 'xdr_begin_sponsoring_future_reserves_op.dart';
import 'xdr_bump_sequence_op.dart';
import 'xdr_change_trust_op.dart';
import 'xdr_claim_claimable_balance_op.dart';
import 'xdr_clawback_claimable_balance_op.dart';
import 'xdr_clawback_op.dart';
import 'xdr_create_account_op.dart';
import 'xdr_create_claimable_balance_op.dart';
import 'xdr_create_passive_sell_offer_op.dart';
import 'xdr_data_io.dart';
import 'xdr_extend_footprint_ttl_op.dart';
import 'xdr_invoke_host_function_op.dart';
import 'xdr_json_helper.dart';
import 'xdr_liquidity_pool_deposit_op.dart';
import 'xdr_liquidity_pool_withdraw_op.dart';
import 'xdr_manage_buy_offer_op.dart';
import 'xdr_manage_data_op.dart';
import 'xdr_manage_sell_offer_op.dart';
import 'xdr_muxed_account.dart';
import 'xdr_operation_type.dart';
import 'xdr_path_payment_strict_receive_op.dart';
import 'xdr_path_payment_strict_send_op.dart';
import 'xdr_payment_op.dart';
import 'xdr_restore_footprint_op.dart';
import 'xdr_revoke_sponsorship_op.dart';
import 'xdr_set_options_op.dart';
import 'xdr_set_trust_line_flags_op.dart';

class XdrOperationBody {
  XdrOperationType _type;

  XdrOperationType get discriminant => this._type;

  set discriminant(XdrOperationType value) => this._type = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrOperationType get type => this._type;
  set type(XdrOperationType value) => this._type = value;

  XdrCreateAccountOp? _createAccountOp;

  XdrCreateAccountOp? get createAccountOp => this._createAccountOp;

  XdrPaymentOp? _paymentOp;

  XdrPaymentOp? get paymentOp => this._paymentOp;

  XdrPathPaymentStrictReceiveOp? _pathPaymentStrictReceiveOp;

  XdrPathPaymentStrictReceiveOp? get pathPaymentStrictReceiveOp =>
      this._pathPaymentStrictReceiveOp;

  XdrManageSellOfferOp? _manageSellOfferOp;

  XdrManageSellOfferOp? get manageSellOfferOp => this._manageSellOfferOp;

  XdrCreatePassiveSellOfferOp? _createPassiveSellOfferOp;

  XdrCreatePassiveSellOfferOp? get createPassiveSellOfferOp =>
      this._createPassiveSellOfferOp;

  XdrSetOptionsOp? _setOptionsOp;

  XdrSetOptionsOp? get setOptionsOp => this._setOptionsOp;

  XdrChangeTrustOp? _changeTrustOp;

  XdrChangeTrustOp? get changeTrustOp => this._changeTrustOp;

  XdrAllowTrustOp? _allowTrustOp;

  XdrAllowTrustOp? get allowTrustOp => this._allowTrustOp;

  XdrMuxedAccount? _destination;

  XdrMuxedAccount? get destination => this._destination;

  XdrManageDataOp? _manageDataOp;

  XdrManageDataOp? get manageDataOp => this._manageDataOp;

  XdrBumpSequenceOp? _bumpSequenceOp;

  XdrBumpSequenceOp? get bumpSequenceOp => this._bumpSequenceOp;

  XdrManageBuyOfferOp? _manageBuyOfferOp;

  XdrManageBuyOfferOp? get manageBuyOfferOp => this._manageBuyOfferOp;

  XdrPathPaymentStrictSendOp? _pathPaymentStrictSendOp;

  XdrPathPaymentStrictSendOp? get pathPaymentStrictSendOp =>
      this._pathPaymentStrictSendOp;

  XdrCreateClaimableBalanceOp? _createClaimableBalanceOp;

  XdrCreateClaimableBalanceOp? get createClaimableBalanceOp =>
      this._createClaimableBalanceOp;

  XdrClaimClaimableBalanceOp? _claimClaimableBalanceOp;

  XdrClaimClaimableBalanceOp? get claimClaimableBalanceOp =>
      this._claimClaimableBalanceOp;

  XdrBeginSponsoringFutureReservesOp? _beginSponsoringFutureReservesOp;

  XdrBeginSponsoringFutureReservesOp? get beginSponsoringFutureReservesOp =>
      this._beginSponsoringFutureReservesOp;

  XdrRevokeSponsorshipOp? _revokeSponsorshipOp;

  XdrRevokeSponsorshipOp? get revokeSponsorshipOp => this._revokeSponsorshipOp;

  XdrClawbackOp? _clawbackOp;

  XdrClawbackOp? get clawbackOp => this._clawbackOp;

  XdrClawbackClaimableBalanceOp? _clawbackClaimableBalanceOp;

  XdrClawbackClaimableBalanceOp? get clawbackClaimableBalanceOp =>
      this._clawbackClaimableBalanceOp;

  XdrSetTrustLineFlagsOp? _setTrustLineFlagsOp;

  XdrSetTrustLineFlagsOp? get setTrustLineFlagsOp => this._setTrustLineFlagsOp;

  XdrLiquidityPoolDepositOp? _liquidityPoolDepositOp;

  XdrLiquidityPoolDepositOp? get liquidityPoolDepositOp =>
      this._liquidityPoolDepositOp;

  XdrLiquidityPoolWithdrawOp? _liquidityPoolWithdrawOp;

  XdrLiquidityPoolWithdrawOp? get liquidityPoolWithdrawOp =>
      this._liquidityPoolWithdrawOp;

  XdrInvokeHostFunctionOp? _invokeHostFunctionOp;

  XdrInvokeHostFunctionOp? get invokeHostFunctionOp =>
      this._invokeHostFunctionOp;

  XdrExtendFootprintTTLOp? _extendFootprintTTLOp;

  XdrExtendFootprintTTLOp? get extendFootprintTTLOp =>
      this._extendFootprintTTLOp;

  XdrRestoreFootprintOp? _restoreFootprintOp;

  XdrRestoreFootprintOp? get restoreFootprintOp => this._restoreFootprintOp;

  XdrOperationBody(this._type);

  set createAccountOp(XdrCreateAccountOp? value) =>
      this._createAccountOp = value;

  set paymentOp(XdrPaymentOp? value) => this._paymentOp = value;

  set pathPaymentStrictReceiveOp(XdrPathPaymentStrictReceiveOp? value) =>
      this._pathPaymentStrictReceiveOp = value;

  set manageSellOfferOp(XdrManageSellOfferOp? value) =>
      this._manageSellOfferOp = value;

  set createPassiveSellOfferOp(XdrCreatePassiveSellOfferOp? value) =>
      this._createPassiveSellOfferOp = value;

  set setOptionsOp(XdrSetOptionsOp? value) => this._setOptionsOp = value;

  set changeTrustOp(XdrChangeTrustOp? value) => this._changeTrustOp = value;

  set allowTrustOp(XdrAllowTrustOp? value) => this._allowTrustOp = value;

  set destination(XdrMuxedAccount? value) => this._destination = value;

  set manageDataOp(XdrManageDataOp? value) => this._manageDataOp = value;

  set bumpSequenceOp(XdrBumpSequenceOp? value) => this._bumpSequenceOp = value;

  set manageBuyOfferOp(XdrManageBuyOfferOp? value) =>
      this._manageBuyOfferOp = value;

  set pathPaymentStrictSendOp(XdrPathPaymentStrictSendOp? value) =>
      this._pathPaymentStrictSendOp = value;

  set createClaimableBalanceOp(XdrCreateClaimableBalanceOp? value) =>
      this._createClaimableBalanceOp = value;

  set claimClaimableBalanceOp(XdrClaimClaimableBalanceOp? value) =>
      this._claimClaimableBalanceOp = value;

  set beginSponsoringFutureReservesOp(
    XdrBeginSponsoringFutureReservesOp? value,
  ) => this._beginSponsoringFutureReservesOp = value;

  set revokeSponsorshipOp(XdrRevokeSponsorshipOp? value) =>
      this._revokeSponsorshipOp = value;

  set clawbackOp(XdrClawbackOp? value) => this._clawbackOp = value;

  set clawbackClaimableBalanceOp(XdrClawbackClaimableBalanceOp? value) =>
      this._clawbackClaimableBalanceOp = value;

  set setTrustLineFlagsOp(XdrSetTrustLineFlagsOp? value) =>
      this._setTrustLineFlagsOp = value;

  set liquidityPoolDepositOp(XdrLiquidityPoolDepositOp? value) =>
      this._liquidityPoolDepositOp = value;

  set liquidityPoolWithdrawOp(XdrLiquidityPoolWithdrawOp? value) =>
      this._liquidityPoolWithdrawOp = value;

  set invokeHostFunctionOp(XdrInvokeHostFunctionOp? value) =>
      this._invokeHostFunctionOp = value;

  set extendFootprintTTLOp(XdrExtendFootprintTTLOp? value) =>
      this._extendFootprintTTLOp = value;

  set restoreFootprintOp(XdrRestoreFootprintOp? value) =>
      this._restoreFootprintOp = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrOperationBody encodedOperationBody,
  ) {
    stream.writeInt(encodedOperationBody.discriminant.value);
    switch (encodedOperationBody.discriminant) {
      case XdrOperationType.CREATE_ACCOUNT:
        XdrCreateAccountOp.encode(
          stream,
          encodedOperationBody._createAccountOp!,
        );
        break;
      case XdrOperationType.PAYMENT:
        XdrPaymentOp.encode(stream, encodedOperationBody._paymentOp!);
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_RECEIVE:
        XdrPathPaymentStrictReceiveOp.encode(
          stream,
          encodedOperationBody._pathPaymentStrictReceiveOp!,
        );
        break;
      case XdrOperationType.MANAGE_SELL_OFFER:
        XdrManageSellOfferOp.encode(
          stream,
          encodedOperationBody._manageSellOfferOp!,
        );
        break;
      case XdrOperationType.CREATE_PASSIVE_SELL_OFFER:
        XdrCreatePassiveSellOfferOp.encode(
          stream,
          encodedOperationBody._createPassiveSellOfferOp!,
        );
        break;
      case XdrOperationType.SET_OPTIONS:
        XdrSetOptionsOp.encode(stream, encodedOperationBody._setOptionsOp!);
        break;
      case XdrOperationType.CHANGE_TRUST:
        XdrChangeTrustOp.encode(stream, encodedOperationBody._changeTrustOp!);
        break;
      case XdrOperationType.ALLOW_TRUST:
        XdrAllowTrustOp.encode(stream, encodedOperationBody._allowTrustOp!);
        break;
      case XdrOperationType.ACCOUNT_MERGE:
        XdrMuxedAccount.encode(stream, encodedOperationBody._destination!);
        break;
      case XdrOperationType.INFLATION:
        break;
      case XdrOperationType.MANAGE_DATA:
        XdrManageDataOp.encode(stream, encodedOperationBody._manageDataOp!);
        break;
      case XdrOperationType.BUMP_SEQUENCE:
        XdrBumpSequenceOp.encode(stream, encodedOperationBody._bumpSequenceOp!);
        break;
      case XdrOperationType.MANAGE_BUY_OFFER:
        XdrManageBuyOfferOp.encode(
          stream,
          encodedOperationBody._manageBuyOfferOp!,
        );
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_SEND:
        XdrPathPaymentStrictSendOp.encode(
          stream,
          encodedOperationBody._pathPaymentStrictSendOp!,
        );
        break;
      case XdrOperationType.CREATE_CLAIMABLE_BALANCE:
        XdrCreateClaimableBalanceOp.encode(
          stream,
          encodedOperationBody._createClaimableBalanceOp!,
        );
        break;
      case XdrOperationType.CLAIM_CLAIMABLE_BALANCE:
        XdrClaimClaimableBalanceOp.encode(
          stream,
          encodedOperationBody._claimClaimableBalanceOp!,
        );
        break;
      case XdrOperationType.BEGIN_SPONSORING_FUTURE_RESERVES:
        XdrBeginSponsoringFutureReservesOp.encode(
          stream,
          encodedOperationBody._beginSponsoringFutureReservesOp!,
        );
        break;
      case XdrOperationType.END_SPONSORING_FUTURE_RESERVES:
        break;
      case XdrOperationType.REVOKE_SPONSORSHIP:
        XdrRevokeSponsorshipOp.encode(
          stream,
          encodedOperationBody._revokeSponsorshipOp!,
        );
        break;
      case XdrOperationType.CLAWBACK:
        XdrClawbackOp.encode(stream, encodedOperationBody._clawbackOp!);
        break;
      case XdrOperationType.CLAWBACK_CLAIMABLE_BALANCE:
        XdrClawbackClaimableBalanceOp.encode(
          stream,
          encodedOperationBody._clawbackClaimableBalanceOp!,
        );
        break;
      case XdrOperationType.SET_TRUST_LINE_FLAGS:
        XdrSetTrustLineFlagsOp.encode(
          stream,
          encodedOperationBody._setTrustLineFlagsOp!,
        );
        break;
      case XdrOperationType.LIQUIDITY_POOL_DEPOSIT:
        XdrLiquidityPoolDepositOp.encode(
          stream,
          encodedOperationBody._liquidityPoolDepositOp!,
        );
        break;
      case XdrOperationType.LIQUIDITY_POOL_WITHDRAW:
        XdrLiquidityPoolWithdrawOp.encode(
          stream,
          encodedOperationBody._liquidityPoolWithdrawOp!,
        );
        break;
      case XdrOperationType.INVOKE_HOST_FUNCTION:
        XdrInvokeHostFunctionOp.encode(
          stream,
          encodedOperationBody._invokeHostFunctionOp!,
        );
        break;
      case XdrOperationType.EXTEND_FOOTPRINT_TTL:
        XdrExtendFootprintTTLOp.encode(
          stream,
          encodedOperationBody._extendFootprintTTLOp!,
        );
        break;
      case XdrOperationType.RESTORE_FOOTPRINT:
        XdrRestoreFootprintOp.encode(
          stream,
          encodedOperationBody._restoreFootprintOp!,
        );
        break;
      default:
        break;
    }
  }

  static XdrOperationBody decode(XdrDataInputStream stream) {
    XdrOperationBody decodedOperationBody = XdrOperationBody(
      XdrOperationType.decode(stream),
    );
    switch (decodedOperationBody.discriminant) {
      case XdrOperationType.CREATE_ACCOUNT:
        decodedOperationBody._createAccountOp = XdrCreateAccountOp.decode(
          stream,
        );
        break;
      case XdrOperationType.PAYMENT:
        decodedOperationBody._paymentOp = XdrPaymentOp.decode(stream);
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_RECEIVE:
        decodedOperationBody._pathPaymentStrictReceiveOp =
            XdrPathPaymentStrictReceiveOp.decode(stream);
        break;
      case XdrOperationType.MANAGE_SELL_OFFER:
        decodedOperationBody._manageSellOfferOp = XdrManageSellOfferOp.decode(
          stream,
        );
        break;
      case XdrOperationType.CREATE_PASSIVE_SELL_OFFER:
        decodedOperationBody._createPassiveSellOfferOp =
            XdrCreatePassiveSellOfferOp.decode(stream);
        break;
      case XdrOperationType.SET_OPTIONS:
        decodedOperationBody._setOptionsOp = XdrSetOptionsOp.decode(stream);
        break;
      case XdrOperationType.CHANGE_TRUST:
        decodedOperationBody._changeTrustOp = XdrChangeTrustOp.decode(stream);
        break;
      case XdrOperationType.ALLOW_TRUST:
        decodedOperationBody._allowTrustOp = XdrAllowTrustOp.decode(stream);
        break;
      case XdrOperationType.ACCOUNT_MERGE:
        decodedOperationBody._destination = XdrMuxedAccount.decode(stream);
        break;
      case XdrOperationType.INFLATION:
        break;
      case XdrOperationType.MANAGE_DATA:
        decodedOperationBody._manageDataOp = XdrManageDataOp.decode(stream);
        break;
      case XdrOperationType.BUMP_SEQUENCE:
        decodedOperationBody._bumpSequenceOp = XdrBumpSequenceOp.decode(stream);
        break;
      case XdrOperationType.MANAGE_BUY_OFFER:
        decodedOperationBody._manageBuyOfferOp = XdrManageBuyOfferOp.decode(
          stream,
        );
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_SEND:
        decodedOperationBody._pathPaymentStrictSendOp =
            XdrPathPaymentStrictSendOp.decode(stream);
        break;
      case XdrOperationType.CREATE_CLAIMABLE_BALANCE:
        decodedOperationBody._createClaimableBalanceOp =
            XdrCreateClaimableBalanceOp.decode(stream);
        break;
      case XdrOperationType.CLAIM_CLAIMABLE_BALANCE:
        decodedOperationBody._claimClaimableBalanceOp =
            XdrClaimClaimableBalanceOp.decode(stream);
        break;
      case XdrOperationType.BEGIN_SPONSORING_FUTURE_RESERVES:
        decodedOperationBody._beginSponsoringFutureReservesOp =
            XdrBeginSponsoringFutureReservesOp.decode(stream);
        break;
      case XdrOperationType.END_SPONSORING_FUTURE_RESERVES:
        break;
      case XdrOperationType.REVOKE_SPONSORSHIP:
        decodedOperationBody._revokeSponsorshipOp =
            XdrRevokeSponsorshipOp.decode(stream);
        break;
      case XdrOperationType.CLAWBACK:
        decodedOperationBody._clawbackOp = XdrClawbackOp.decode(stream);
        break;
      case XdrOperationType.CLAWBACK_CLAIMABLE_BALANCE:
        decodedOperationBody._clawbackClaimableBalanceOp =
            XdrClawbackClaimableBalanceOp.decode(stream);
        break;
      case XdrOperationType.SET_TRUST_LINE_FLAGS:
        decodedOperationBody._setTrustLineFlagsOp =
            XdrSetTrustLineFlagsOp.decode(stream);
        break;
      case XdrOperationType.LIQUIDITY_POOL_DEPOSIT:
        decodedOperationBody._liquidityPoolDepositOp =
            XdrLiquidityPoolDepositOp.decode(stream);
        break;
      case XdrOperationType.LIQUIDITY_POOL_WITHDRAW:
        decodedOperationBody._liquidityPoolWithdrawOp =
            XdrLiquidityPoolWithdrawOp.decode(stream);
        break;
      case XdrOperationType.INVOKE_HOST_FUNCTION:
        decodedOperationBody._invokeHostFunctionOp =
            XdrInvokeHostFunctionOp.decode(stream);
        break;
      case XdrOperationType.EXTEND_FOOTPRINT_TTL:
        decodedOperationBody._extendFootprintTTLOp =
            XdrExtendFootprintTTLOp.decode(stream);
        break;
      case XdrOperationType.RESTORE_FOOTPRINT:
        decodedOperationBody._restoreFootprintOp = XdrRestoreFootprintOp.decode(
          stream,
        );
        break;
      default:
        break;
    }
    return decodedOperationBody;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrOperationBody.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrOperationBody fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrOperationBody.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.type: ${discriminant.enumName()}');
    switch (discriminant) {
      case XdrOperationType.CREATE_ACCOUNT:
        _createAccountOp!.toTxRep('$prefix.createAccountOp', lines);
        break;
      case XdrOperationType.PAYMENT:
        _paymentOp!.toTxRep('$prefix.paymentOp', lines);
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_RECEIVE:
        _pathPaymentStrictReceiveOp!.toTxRep(
          '$prefix.pathPaymentStrictReceiveOp',
          lines,
        );
        break;
      case XdrOperationType.MANAGE_SELL_OFFER:
        _manageSellOfferOp!.toTxRep('$prefix.manageSellOfferOp', lines);
        break;
      case XdrOperationType.CREATE_PASSIVE_SELL_OFFER:
        _createPassiveSellOfferOp!.toTxRep(
          '$prefix.createPassiveSellOfferOp',
          lines,
        );
        break;
      case XdrOperationType.SET_OPTIONS:
        _setOptionsOp!.toTxRep('$prefix.setOptionsOp', lines);
        break;
      case XdrOperationType.CHANGE_TRUST:
        _changeTrustOp!.toTxRep('$prefix.changeTrustOp', lines);
        break;
      case XdrOperationType.ALLOW_TRUST:
        _allowTrustOp!.toTxRep('$prefix.allowTrustOp', lines);
        break;
      case XdrOperationType.ACCOUNT_MERGE:
        lines.add(
          '$prefix.destination: ${TxRepHelper.formatMuxedAccount(_destination!)}',
        );
        break;
      case XdrOperationType.INFLATION:
        break;
      case XdrOperationType.MANAGE_DATA:
        _manageDataOp!.toTxRep('$prefix.manageDataOp', lines);
        break;
      case XdrOperationType.BUMP_SEQUENCE:
        _bumpSequenceOp!.toTxRep('$prefix.bumpSequenceOp', lines);
        break;
      case XdrOperationType.MANAGE_BUY_OFFER:
        _manageBuyOfferOp!.toTxRep('$prefix.manageBuyOfferOp', lines);
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_SEND:
        _pathPaymentStrictSendOp!.toTxRep(
          '$prefix.pathPaymentStrictSendOp',
          lines,
        );
        break;
      case XdrOperationType.CREATE_CLAIMABLE_BALANCE:
        _createClaimableBalanceOp!.toTxRep(
          '$prefix.createClaimableBalanceOp',
          lines,
        );
        break;
      case XdrOperationType.CLAIM_CLAIMABLE_BALANCE:
        _claimClaimableBalanceOp!.toTxRep(
          '$prefix.claimClaimableBalanceOp',
          lines,
        );
        break;
      case XdrOperationType.BEGIN_SPONSORING_FUTURE_RESERVES:
        _beginSponsoringFutureReservesOp!.toTxRep(
          '$prefix.beginSponsoringFutureReservesOp',
          lines,
        );
        break;
      case XdrOperationType.END_SPONSORING_FUTURE_RESERVES:
        break;
      case XdrOperationType.REVOKE_SPONSORSHIP:
        _revokeSponsorshipOp!.toTxRep('$prefix.revokeSponsorshipOp', lines);
        break;
      case XdrOperationType.CLAWBACK:
        _clawbackOp!.toTxRep('$prefix.clawbackOp', lines);
        break;
      case XdrOperationType.CLAWBACK_CLAIMABLE_BALANCE:
        _clawbackClaimableBalanceOp!.toTxRep(
          '$prefix.clawbackClaimableBalanceOp',
          lines,
        );
        break;
      case XdrOperationType.SET_TRUST_LINE_FLAGS:
        _setTrustLineFlagsOp!.toTxRep('$prefix.setTrustLineFlagsOp', lines);
        break;
      case XdrOperationType.LIQUIDITY_POOL_DEPOSIT:
        _liquidityPoolDepositOp!.toTxRep(
          '$prefix.liquidityPoolDepositOp',
          lines,
        );
        break;
      case XdrOperationType.LIQUIDITY_POOL_WITHDRAW:
        _liquidityPoolWithdrawOp!.toTxRep(
          '$prefix.liquidityPoolWithdrawOp',
          lines,
        );
        break;
      case XdrOperationType.INVOKE_HOST_FUNCTION:
        _invokeHostFunctionOp!.toTxRep('$prefix.invokeHostFunctionOp', lines);
        break;
      case XdrOperationType.EXTEND_FOOTPRINT_TTL:
        _extendFootprintTTLOp!.toTxRep('$prefix.extendFootprintTTLOp', lines);
        break;
      case XdrOperationType.RESTORE_FOOTPRINT:
        _restoreFootprintOp!.toTxRep('$prefix.restoreFootprintOp', lines);
        break;
      default:
        break;
    }
  }

  static XdrOperationBody fromTxRep(Map<String, String> map, String prefix) {
    XdrOperationType disc = XdrOperationType.fromTxRepName(
      TxRepHelper.getValue(map, '$prefix.type') ?? '',
    );
    XdrOperationBody result = XdrOperationBody(disc);
    switch (result.discriminant) {
      case XdrOperationType.CREATE_ACCOUNT:
        result._createAccountOp = XdrCreateAccountOp.fromTxRep(
          map,
          '$prefix.createAccountOp',
        );
        break;
      case XdrOperationType.PAYMENT:
        result._paymentOp = XdrPaymentOp.fromTxRep(map, '$prefix.paymentOp');
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_RECEIVE:
        result._pathPaymentStrictReceiveOp =
            XdrPathPaymentStrictReceiveOp.fromTxRep(
              map,
              '$prefix.pathPaymentStrictReceiveOp',
            );
        break;
      case XdrOperationType.MANAGE_SELL_OFFER:
        result._manageSellOfferOp = XdrManageSellOfferOp.fromTxRep(
          map,
          '$prefix.manageSellOfferOp',
        );
        break;
      case XdrOperationType.CREATE_PASSIVE_SELL_OFFER:
        result._createPassiveSellOfferOp =
            XdrCreatePassiveSellOfferOp.fromTxRep(
              map,
              '$prefix.createPassiveSellOfferOp',
            );
        break;
      case XdrOperationType.SET_OPTIONS:
        result._setOptionsOp = XdrSetOptionsOp.fromTxRep(
          map,
          '$prefix.setOptionsOp',
        );
        break;
      case XdrOperationType.CHANGE_TRUST:
        result._changeTrustOp = XdrChangeTrustOp.fromTxRep(
          map,
          '$prefix.changeTrustOp',
        );
        break;
      case XdrOperationType.ALLOW_TRUST:
        result._allowTrustOp = XdrAllowTrustOp.fromTxRep(
          map,
          '$prefix.allowTrustOp',
        );
        break;
      case XdrOperationType.ACCOUNT_MERGE:
        result._destination = TxRepHelper.parseMuxedAccount(
          TxRepHelper.getValue(map, '$prefix.destination') ?? '',
        );
        break;
      case XdrOperationType.INFLATION:
        break;
      case XdrOperationType.MANAGE_DATA:
        result._manageDataOp = XdrManageDataOp.fromTxRep(
          map,
          '$prefix.manageDataOp',
        );
        break;
      case XdrOperationType.BUMP_SEQUENCE:
        result._bumpSequenceOp = XdrBumpSequenceOp.fromTxRep(
          map,
          '$prefix.bumpSequenceOp',
        );
        break;
      case XdrOperationType.MANAGE_BUY_OFFER:
        result._manageBuyOfferOp = XdrManageBuyOfferOp.fromTxRep(
          map,
          '$prefix.manageBuyOfferOp',
        );
        break;
      case XdrOperationType.PATH_PAYMENT_STRICT_SEND:
        result._pathPaymentStrictSendOp = XdrPathPaymentStrictSendOp.fromTxRep(
          map,
          '$prefix.pathPaymentStrictSendOp',
        );
        break;
      case XdrOperationType.CREATE_CLAIMABLE_BALANCE:
        result._createClaimableBalanceOp =
            XdrCreateClaimableBalanceOp.fromTxRep(
              map,
              '$prefix.createClaimableBalanceOp',
            );
        break;
      case XdrOperationType.CLAIM_CLAIMABLE_BALANCE:
        result._claimClaimableBalanceOp = XdrClaimClaimableBalanceOp.fromTxRep(
          map,
          '$prefix.claimClaimableBalanceOp',
        );
        break;
      case XdrOperationType.BEGIN_SPONSORING_FUTURE_RESERVES:
        result._beginSponsoringFutureReservesOp =
            XdrBeginSponsoringFutureReservesOp.fromTxRep(
              map,
              '$prefix.beginSponsoringFutureReservesOp',
            );
        break;
      case XdrOperationType.END_SPONSORING_FUTURE_RESERVES:
        break;
      case XdrOperationType.REVOKE_SPONSORSHIP:
        result._revokeSponsorshipOp = XdrRevokeSponsorshipOp.fromTxRep(
          map,
          '$prefix.revokeSponsorshipOp',
        );
        break;
      case XdrOperationType.CLAWBACK:
        result._clawbackOp = XdrClawbackOp.fromTxRep(map, '$prefix.clawbackOp');
        break;
      case XdrOperationType.CLAWBACK_CLAIMABLE_BALANCE:
        result._clawbackClaimableBalanceOp =
            XdrClawbackClaimableBalanceOp.fromTxRep(
              map,
              '$prefix.clawbackClaimableBalanceOp',
            );
        break;
      case XdrOperationType.SET_TRUST_LINE_FLAGS:
        result._setTrustLineFlagsOp = XdrSetTrustLineFlagsOp.fromTxRep(
          map,
          '$prefix.setTrustLineFlagsOp',
        );
        break;
      case XdrOperationType.LIQUIDITY_POOL_DEPOSIT:
        result._liquidityPoolDepositOp = XdrLiquidityPoolDepositOp.fromTxRep(
          map,
          '$prefix.liquidityPoolDepositOp',
        );
        break;
      case XdrOperationType.LIQUIDITY_POOL_WITHDRAW:
        result._liquidityPoolWithdrawOp = XdrLiquidityPoolWithdrawOp.fromTxRep(
          map,
          '$prefix.liquidityPoolWithdrawOp',
        );
        break;
      case XdrOperationType.INVOKE_HOST_FUNCTION:
        result._invokeHostFunctionOp = XdrInvokeHostFunctionOp.fromTxRep(
          map,
          '$prefix.invokeHostFunctionOp',
        );
        break;
      case XdrOperationType.EXTEND_FOOTPRINT_TTL:
        result._extendFootprintTTLOp = XdrExtendFootprintTTLOp.fromTxRep(
          map,
          '$prefix.extendFootprintTTLOp',
        );
        break;
      case XdrOperationType.RESTORE_FOOTPRINT:
        result._restoreFootprintOp = XdrRestoreFootprintOp.fromTxRep(
          map,
          '$prefix.restoreFootprintOp',
        );
        break;
      default:
        break;
    }
    return result;
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrOperationBody');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrOperationBody.
  static XdrOperationBody fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrOperationBody'),
  );

  /// Returns the SEP-0051 rendering of this XdrOperationBody.
  Object? toXdrJsonValue() {
    switch (discriminant.value) {
      case 0:
        return <String, Object?>{
          'create_account': _createAccountOp!.toXdrJsonValue(),
        };
      case 1:
        return <String, Object?>{'payment': _paymentOp!.toXdrJsonValue()};
      case 2:
        return <String, Object?>{
          'path_payment_strict_receive': _pathPaymentStrictReceiveOp!
              .toXdrJsonValue(),
        };
      case 3:
        return <String, Object?>{
          'manage_sell_offer': _manageSellOfferOp!.toXdrJsonValue(),
        };
      case 4:
        return <String, Object?>{
          'create_passive_sell_offer': _createPassiveSellOfferOp!
              .toXdrJsonValue(),
        };
      case 5:
        return <String, Object?>{
          'set_options': _setOptionsOp!.toXdrJsonValue(),
        };
      case 6:
        return <String, Object?>{
          'change_trust': _changeTrustOp!.toXdrJsonValue(),
        };
      case 7:
        return <String, Object?>{
          'allow_trust': _allowTrustOp!.toXdrJsonValue(),
        };
      case 8:
        return <String, Object?>{
          'account_merge': _destination!.toXdrJsonValue(),
        };
      case 9:
        return 'inflation';
      case 10:
        return <String, Object?>{
          'manage_data': _manageDataOp!.toXdrJsonValue(),
        };
      case 11:
        return <String, Object?>{
          'bump_sequence': _bumpSequenceOp!.toXdrJsonValue(),
        };
      case 12:
        return <String, Object?>{
          'manage_buy_offer': _manageBuyOfferOp!.toXdrJsonValue(),
        };
      case 13:
        return <String, Object?>{
          'path_payment_strict_send': _pathPaymentStrictSendOp!
              .toXdrJsonValue(),
        };
      case 14:
        return <String, Object?>{
          'create_claimable_balance': _createClaimableBalanceOp!
              .toXdrJsonValue(),
        };
      case 15:
        return <String, Object?>{
          'claim_claimable_balance': _claimClaimableBalanceOp!.toXdrJsonValue(),
        };
      case 16:
        return <String, Object?>{
          'begin_sponsoring_future_reserves': _beginSponsoringFutureReservesOp!
              .toXdrJsonValue(),
        };
      case 17:
        return 'end_sponsoring_future_reserves';
      case 18:
        return <String, Object?>{
          'revoke_sponsorship': _revokeSponsorshipOp!.toXdrJsonValue(),
        };
      case 19:
        return <String, Object?>{'clawback': _clawbackOp!.toXdrJsonValue()};
      case 20:
        return <String, Object?>{
          'clawback_claimable_balance': _clawbackClaimableBalanceOp!
              .toXdrJsonValue(),
        };
      case 21:
        return <String, Object?>{
          'set_trust_line_flags': _setTrustLineFlagsOp!.toXdrJsonValue(),
        };
      case 22:
        return <String, Object?>{
          'liquidity_pool_deposit': _liquidityPoolDepositOp!.toXdrJsonValue(),
        };
      case 23:
        return <String, Object?>{
          'liquidity_pool_withdraw': _liquidityPoolWithdrawOp!.toXdrJsonValue(),
        };
      case 24:
        return <String, Object?>{
          'invoke_host_function': _invokeHostFunctionOp!.toXdrJsonValue(),
        };
      case 25:
        return <String, Object?>{
          'extend_footprint_ttl': _extendFootprintTTLOp!.toXdrJsonValue(),
        };
      case 26:
        return <String, Object?>{
          'restore_footprint': _restoreFootprintOp!.toXdrJsonValue(),
        };
    }
    XdrJsonHelper.fail(
      'XdrOperationBody',
      'holds the unknown discriminant ${discriminant.value}',
    );
  }

  /// Reads a XdrOperationBody from its SEP-0051 rendering.
  static XdrOperationBody fromXdrJsonValue(Object? value) {
    if (value is String) {
      switch (value) {
        case 'inflation':
          return XdrOperationBody(XdrOperationType.INFLATION);
        case 'end_sponsoring_future_reserves':
          return XdrOperationBody(
            XdrOperationType.END_SPONSORING_FUTURE_RESERVES,
          );
      }
      XdrJsonHelper.fail(
        'XdrOperationBody',
        'has no arm named ${XdrJsonHelper.preview(value)}',
      );
    }
    final MapEntry<String, Object?> arm = XdrJsonHelper.readSingleKeyObject(
      value,
      type: 'XdrOperationBody',
    );
    switch (arm.key) {
      case 'create_account':
        final XdrOperationBody arm0 = XdrOperationBody(
          XdrOperationType.CREATE_ACCOUNT,
        );
        arm0.createAccountOp = XdrCreateAccountOp.fromXdrJsonValue(arm.value);
        return arm0;
      case 'payment':
        final XdrOperationBody arm1 = XdrOperationBody(
          XdrOperationType.PAYMENT,
        );
        arm1.paymentOp = XdrPaymentOp.fromXdrJsonValue(arm.value);
        return arm1;
      case 'path_payment_strict_receive':
        final XdrOperationBody arm2 = XdrOperationBody(
          XdrOperationType.PATH_PAYMENT_STRICT_RECEIVE,
        );
        arm2.pathPaymentStrictReceiveOp =
            XdrPathPaymentStrictReceiveOp.fromXdrJsonValue(arm.value);
        return arm2;
      case 'manage_sell_offer':
        final XdrOperationBody arm3 = XdrOperationBody(
          XdrOperationType.MANAGE_SELL_OFFER,
        );
        arm3.manageSellOfferOp = XdrManageSellOfferOp.fromXdrJsonValue(
          arm.value,
        );
        return arm3;
      case 'create_passive_sell_offer':
        final XdrOperationBody arm4 = XdrOperationBody(
          XdrOperationType.CREATE_PASSIVE_SELL_OFFER,
        );
        arm4.createPassiveSellOfferOp =
            XdrCreatePassiveSellOfferOp.fromXdrJsonValue(arm.value);
        return arm4;
      case 'set_options':
        final XdrOperationBody arm5 = XdrOperationBody(
          XdrOperationType.SET_OPTIONS,
        );
        arm5.setOptionsOp = XdrSetOptionsOp.fromXdrJsonValue(arm.value);
        return arm5;
      case 'change_trust':
        final XdrOperationBody arm6 = XdrOperationBody(
          XdrOperationType.CHANGE_TRUST,
        );
        arm6.changeTrustOp = XdrChangeTrustOp.fromXdrJsonValue(arm.value);
        return arm6;
      case 'allow_trust':
        final XdrOperationBody arm7 = XdrOperationBody(
          XdrOperationType.ALLOW_TRUST,
        );
        arm7.allowTrustOp = XdrAllowTrustOp.fromXdrJsonValue(arm.value);
        return arm7;
      case 'account_merge':
        final XdrOperationBody arm8 = XdrOperationBody(
          XdrOperationType.ACCOUNT_MERGE,
        );
        arm8.destination = XdrMuxedAccount.fromXdrJsonValue(arm.value);
        return arm8;
      case 'manage_data':
        final XdrOperationBody arm9 = XdrOperationBody(
          XdrOperationType.MANAGE_DATA,
        );
        arm9.manageDataOp = XdrManageDataOp.fromXdrJsonValue(arm.value);
        return arm9;
      case 'bump_sequence':
        final XdrOperationBody arm10 = XdrOperationBody(
          XdrOperationType.BUMP_SEQUENCE,
        );
        arm10.bumpSequenceOp = XdrBumpSequenceOp.fromXdrJsonValue(arm.value);
        return arm10;
      case 'manage_buy_offer':
        final XdrOperationBody arm11 = XdrOperationBody(
          XdrOperationType.MANAGE_BUY_OFFER,
        );
        arm11.manageBuyOfferOp = XdrManageBuyOfferOp.fromXdrJsonValue(
          arm.value,
        );
        return arm11;
      case 'path_payment_strict_send':
        final XdrOperationBody arm12 = XdrOperationBody(
          XdrOperationType.PATH_PAYMENT_STRICT_SEND,
        );
        arm12.pathPaymentStrictSendOp =
            XdrPathPaymentStrictSendOp.fromXdrJsonValue(arm.value);
        return arm12;
      case 'create_claimable_balance':
        final XdrOperationBody arm13 = XdrOperationBody(
          XdrOperationType.CREATE_CLAIMABLE_BALANCE,
        );
        arm13.createClaimableBalanceOp =
            XdrCreateClaimableBalanceOp.fromXdrJsonValue(arm.value);
        return arm13;
      case 'claim_claimable_balance':
        final XdrOperationBody arm14 = XdrOperationBody(
          XdrOperationType.CLAIM_CLAIMABLE_BALANCE,
        );
        arm14.claimClaimableBalanceOp =
            XdrClaimClaimableBalanceOp.fromXdrJsonValue(arm.value);
        return arm14;
      case 'begin_sponsoring_future_reserves':
        final XdrOperationBody arm15 = XdrOperationBody(
          XdrOperationType.BEGIN_SPONSORING_FUTURE_RESERVES,
        );
        arm15.beginSponsoringFutureReservesOp =
            XdrBeginSponsoringFutureReservesOp.fromXdrJsonValue(arm.value);
        return arm15;
      case 'revoke_sponsorship':
        final XdrOperationBody arm16 = XdrOperationBody(
          XdrOperationType.REVOKE_SPONSORSHIP,
        );
        arm16.revokeSponsorshipOp = XdrRevokeSponsorshipOp.fromXdrJsonValue(
          arm.value,
        );
        return arm16;
      case 'clawback':
        final XdrOperationBody arm17 = XdrOperationBody(
          XdrOperationType.CLAWBACK,
        );
        arm17.clawbackOp = XdrClawbackOp.fromXdrJsonValue(arm.value);
        return arm17;
      case 'clawback_claimable_balance':
        final XdrOperationBody arm18 = XdrOperationBody(
          XdrOperationType.CLAWBACK_CLAIMABLE_BALANCE,
        );
        arm18.clawbackClaimableBalanceOp =
            XdrClawbackClaimableBalanceOp.fromXdrJsonValue(arm.value);
        return arm18;
      case 'set_trust_line_flags':
        final XdrOperationBody arm19 = XdrOperationBody(
          XdrOperationType.SET_TRUST_LINE_FLAGS,
        );
        arm19.setTrustLineFlagsOp = XdrSetTrustLineFlagsOp.fromXdrJsonValue(
          arm.value,
        );
        return arm19;
      case 'liquidity_pool_deposit':
        final XdrOperationBody arm20 = XdrOperationBody(
          XdrOperationType.LIQUIDITY_POOL_DEPOSIT,
        );
        arm20.liquidityPoolDepositOp =
            XdrLiquidityPoolDepositOp.fromXdrJsonValue(arm.value);
        return arm20;
      case 'liquidity_pool_withdraw':
        final XdrOperationBody arm21 = XdrOperationBody(
          XdrOperationType.LIQUIDITY_POOL_WITHDRAW,
        );
        arm21.liquidityPoolWithdrawOp =
            XdrLiquidityPoolWithdrawOp.fromXdrJsonValue(arm.value);
        return arm21;
      case 'invoke_host_function':
        final XdrOperationBody arm22 = XdrOperationBody(
          XdrOperationType.INVOKE_HOST_FUNCTION,
        );
        arm22.invokeHostFunctionOp = XdrInvokeHostFunctionOp.fromXdrJsonValue(
          arm.value,
        );
        return arm22;
      case 'extend_footprint_ttl':
        final XdrOperationBody arm23 = XdrOperationBody(
          XdrOperationType.EXTEND_FOOTPRINT_TTL,
        );
        arm23.extendFootprintTTLOp = XdrExtendFootprintTTLOp.fromXdrJsonValue(
          arm.value,
        );
        return arm23;
      case 'restore_footprint':
        final XdrOperationBody arm24 = XdrOperationBody(
          XdrOperationType.RESTORE_FOOTPRINT,
        );
        arm24.restoreFootprintOp = XdrRestoreFootprintOp.fromXdrJsonValue(
          arm.value,
        );
        return arm24;
    }
    XdrJsonHelper.fail(
      'XdrOperationBody',
      'has no arm named ${XdrJsonHelper.preview(arm.key)}',
    );
  }
}
