// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_int64.dart';
import 'xdr_uint64.dart';

class XdrInt256PartsBase {
  XdrInt64 _hiHi;
  XdrInt64 get hiHi => this._hiHi;
  set hiHi(XdrInt64 value) => this._hiHi = value;

  XdrUint64 _hiLo;
  XdrUint64 get hiLo => this._hiLo;
  set hiLo(XdrUint64 value) => this._hiLo = value;

  XdrUint64 _loHi;
  XdrUint64 get loHi => this._loHi;
  set loHi(XdrUint64 value) => this._loHi = value;

  XdrUint64 _loLo;
  XdrUint64 get loLo => this._loLo;
  set loLo(XdrUint64 value) => this._loLo = value;

  XdrInt256PartsBase(this._hiHi, this._hiLo, this._loHi, this._loLo);

  static void encode(
    XdrDataOutputStream stream,
    XdrInt256PartsBase encodedInt256Parts,
  ) {
    XdrInt64.encode(stream, encodedInt256Parts.hiHi);
    XdrUint64.encode(stream, encodedInt256Parts.hiLo);
    XdrUint64.encode(stream, encodedInt256Parts.loHi);
    XdrUint64.encode(stream, encodedInt256Parts.loLo);
  }

  static XdrInt256PartsBase decode(XdrDataInputStream stream) {
    XdrInt64 hiHi = XdrInt64.decode(stream);
    XdrUint64 hiLo = XdrUint64.decode(stream);
    XdrUint64 loHi = XdrUint64.decode(stream);
    XdrUint64 loLo = XdrUint64.decode(stream);
    return XdrInt256PartsBase(hiHi, hiLo, loHi, loLo);
  }
}
