// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_envelope_type.dart';
import 'xdr_transaction_v1_envelope.dart';

class XdrFeeBumpTransactionInnerTx {
  XdrEnvelopeType _type;

  XdrEnvelopeType get discriminant => this._type;

  set discriminant(XdrEnvelopeType value) => this._type = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrEnvelopeType get type => this._type;
  set type(XdrEnvelopeType value) => this._type = value;

  XdrTransactionV1Envelope? _v1;

  XdrTransactionV1Envelope? get v1 => this._v1;

  XdrFeeBumpTransactionInnerTx(this._type);

  set v1(XdrTransactionV1Envelope? value) => this._v1 = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrFeeBumpTransactionInnerTx encodedFeeBumpTransactionInnerTx,
  ) {
    stream.writeInt(encodedFeeBumpTransactionInnerTx.discriminant.value);
    switch (encodedFeeBumpTransactionInnerTx.discriminant) {
      case XdrEnvelopeType.ENVELOPE_TYPE_TX:
        XdrTransactionV1Envelope.encode(
          stream,
          encodedFeeBumpTransactionInnerTx._v1!,
        );
        break;
      default:
        break;
    }
  }

  static XdrFeeBumpTransactionInnerTx decode(XdrDataInputStream stream) {
    XdrFeeBumpTransactionInnerTx decodedFeeBumpTransactionInnerTx =
        XdrFeeBumpTransactionInnerTx(XdrEnvelopeType.decode(stream));
    switch (decodedFeeBumpTransactionInnerTx.discriminant) {
      case XdrEnvelopeType.ENVELOPE_TYPE_TX:
        decodedFeeBumpTransactionInnerTx._v1 = XdrTransactionV1Envelope.decode(
          stream,
        );
        break;
      default:
        break;
    }
    return decodedFeeBumpTransactionInnerTx;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrFeeBumpTransactionInnerTx.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrFeeBumpTransactionInnerTx fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrFeeBumpTransactionInnerTx.decode(XdrDataInputStream(bytes));
  }
}
