// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_sc_address.dart';
import 'xdr_sc_val.dart';

class XdrInvokeContractArgs {
  XdrSCAddress _contractAddress;
  XdrSCAddress get contractAddress => this._contractAddress;
  set contractAddress(XdrSCAddress value) => this._contractAddress = value;

  String _functionName;
  String get functionName => this._functionName;
  set functionName(String value) => this._functionName = value;

  List<XdrSCVal> _args;
  List<XdrSCVal> get args => this._args;
  set args(List<XdrSCVal> value) => this._args = value;

  XdrInvokeContractArgs(this._contractAddress, this._functionName, this._args);

  static void encode(
    XdrDataOutputStream stream,
    XdrInvokeContractArgs encodedInvokeContractArgs,
  ) {
    XdrSCAddress.encode(stream, encodedInvokeContractArgs.contractAddress);
    stream.writeString(encodedInvokeContractArgs.functionName);
    int argssize = encodedInvokeContractArgs.args.length;
    stream.writeInt(argssize);
    for (int i = 0; i < argssize; i++) {
      XdrSCVal.encode(stream, encodedInvokeContractArgs.args[i]);
    }
  }

  static XdrInvokeContractArgs decode(XdrDataInputStream stream) {
    XdrSCAddress contractAddress = XdrSCAddress.decode(stream);
    String functionName = stream.readString();
    int argssize = stream.readInt();
    List<XdrSCVal> args = List<XdrSCVal>.empty(growable: true);
    for (int i = 0; i < argssize; i++) {
      args.add(XdrSCVal.decode(stream));
    }
    return XdrInvokeContractArgs(contractAddress, functionName, args);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrInvokeContractArgs.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrInvokeContractArgs fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrInvokeContractArgs.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _contractAddress.toTxRep('$prefix.contractAddress', lines);
    lines.add(
      '$prefix.functionName: ${TxRepHelper.escapeString(_functionName)}',
    );
    lines.add('$prefix.args.len: ${_args.length}');
    for (int i = 0; i < _args.length; i++) {
      _args[i].toTxRep('$prefix.args[$i]', lines);
    }
  }

  static XdrInvokeContractArgs fromTxRep(
    Map<String, String> map,
    String prefix,
  ) {
    XdrSCAddress contractAddress = XdrSCAddress.fromTxRep(
      map,
      '$prefix.contractAddress',
    );
    String functionName = TxRepHelper.unescapeString(
      TxRepHelper.getValue(map, '$prefix.functionName') ?? '',
    );
    int argsLen = TxRepHelper.parseInt(
      TxRepHelper.getValue(map, '$prefix.args.len') ?? '0',
    );
    List<XdrSCVal> args = [];
    for (int i = 0; i < argsLen; i++) {
      args.add(XdrSCVal.fromTxRep(map, '$prefix.args[$i]'));
    }
    return XdrInvokeContractArgs(contractAddress, functionName, args);
  }
}
