// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_sc_spec_type_def.dart';

class XdrSCSpecTypeTuple {
  List<XdrSCSpecTypeDef> _valueTypes;
  List<XdrSCSpecTypeDef> get valueTypes => this._valueTypes;
  set valueTypes(List<XdrSCSpecTypeDef> value) => this._valueTypes = value;

  XdrSCSpecTypeTuple(this._valueTypes);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCSpecTypeTuple encodedSCSpecTypeTuple,
  ) {
    int valueTypessize = encodedSCSpecTypeTuple.valueTypes.length;
    stream.writeInt(valueTypessize);
    for (int i = 0; i < valueTypessize; i++) {
      XdrSCSpecTypeDef.encode(stream, encodedSCSpecTypeTuple.valueTypes[i]);
    }
  }

  static XdrSCSpecTypeTuple decode(XdrDataInputStream stream) {
    int valueTypessize = stream.readInt();
    List<XdrSCSpecTypeDef> valueTypes = List<XdrSCSpecTypeDef>.empty(
      growable: true,
    );
    for (int i = 0; i < valueTypessize; i++) {
      valueTypes.add(XdrSCSpecTypeDef.decode(stream));
    }
    return XdrSCSpecTypeTuple(valueTypes);
  }
}
