// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_hash.dart';

class XdrConfigUpgradeSetKey {
  XdrHash _contractID;
  XdrHash get contractID => this._contractID;
  set contractID(XdrHash value) => this._contractID = value;

  XdrHash _contentHash;
  XdrHash get contentHash => this._contentHash;
  set contentHash(XdrHash value) => this._contentHash = value;

  XdrConfigUpgradeSetKey(this._contractID, this._contentHash);

  static void encode(
    XdrDataOutputStream stream,
    XdrConfigUpgradeSetKey encodedConfigUpgradeSetKey,
  ) {
    XdrHash.encode(stream, encodedConfigUpgradeSetKey.contractID);
    XdrHash.encode(stream, encodedConfigUpgradeSetKey.contentHash);
  }

  static XdrConfigUpgradeSetKey decode(XdrDataInputStream stream) {
    XdrHash contractID = XdrHash.decode(stream);
    XdrHash contentHash = XdrHash.decode(stream);
    return XdrConfigUpgradeSetKey(contractID, contentHash);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrConfigUpgradeSetKey.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrConfigUpgradeSetKey fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrConfigUpgradeSetKey.decode(XdrDataInputStream(bytes));
  }
}
