// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_hash.dart';

class XdrFreezeBypassTxs {
  List<XdrHash> _txHashes;
  List<XdrHash> get txHashes => this._txHashes;
  set txHashes(List<XdrHash> value) => this._txHashes = value;

  XdrFreezeBypassTxs(this._txHashes);

  static void encode(
    XdrDataOutputStream stream,
    XdrFreezeBypassTxs encodedFreezeBypassTxs,
  ) {
    int txHashessize = encodedFreezeBypassTxs.txHashes.length;
    stream.writeInt(txHashessize);
    for (int i = 0; i < txHashessize; i++) {
      XdrHash.encode(stream, encodedFreezeBypassTxs.txHashes[i]);
    }
  }

  static XdrFreezeBypassTxs decode(XdrDataInputStream stream) {
    int txHashessize = stream.readInt();
    List<XdrHash> txHashes = List<XdrHash>.empty(growable: true);
    for (int i = 0; i < txHashessize; i++) {
      txHashes.add(XdrHash.decode(stream));
    }
    return XdrFreezeBypassTxs(txHashes);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrFreezeBypassTxs.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrFreezeBypassTxs fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrFreezeBypassTxs.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.txHashes.len: ${_txHashes.length}');
    for (int i = 0; i < _txHashes.length; i++) {
      _txHashes[i].toTxRep('$prefix.txHashes[$i]', lines);
    }
  }

  static XdrFreezeBypassTxs fromTxRep(Map<String, String> map, String prefix) {
    int txHashesLen = TxRepHelper.parseInt(
      TxRepHelper.getValue(map, '$prefix.txHashes.len') ?? '0',
    );
    List<XdrHash> txHashes = [];
    for (int i = 0; i < txHashesLen; i++) {
      txHashes.add(XdrHash.fromTxRep(map, '$prefix.txHashes[$i]'));
    }
    return XdrFreezeBypassTxs(txHashes);
  }
}
