// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_decorated_signature.dart';
import 'xdr_fee_bump_transaction.dart';

class XdrFeeBumpTransactionEnvelope {
  XdrFeeBumpTransaction _tx;
  XdrFeeBumpTransaction get tx => this._tx;
  set tx(XdrFeeBumpTransaction value) => this._tx = value;

  List<XdrDecoratedSignature> _signatures;
  List<XdrDecoratedSignature> get signatures => this._signatures;
  set signatures(List<XdrDecoratedSignature> value) => this._signatures = value;

  XdrFeeBumpTransactionEnvelope(this._tx, this._signatures);

  static void encode(
    XdrDataOutputStream stream,
    XdrFeeBumpTransactionEnvelope encodedFeeBumpTransactionEnvelope,
  ) {
    XdrFeeBumpTransaction.encode(stream, encodedFeeBumpTransactionEnvelope.tx);
    int signaturessize = encodedFeeBumpTransactionEnvelope.signatures.length;
    stream.writeInt(signaturessize);
    for (int i = 0; i < signaturessize; i++) {
      XdrDecoratedSignature.encode(
        stream,
        encodedFeeBumpTransactionEnvelope.signatures[i],
      );
    }
  }

  static XdrFeeBumpTransactionEnvelope decode(XdrDataInputStream stream) {
    XdrFeeBumpTransaction tx = XdrFeeBumpTransaction.decode(stream);
    int signaturessize = stream.readInt();
    List<XdrDecoratedSignature> signatures = List<XdrDecoratedSignature>.empty(
      growable: true,
    );
    for (int i = 0; i < signaturessize; i++) {
      signatures.add(XdrDecoratedSignature.decode(stream));
    }
    return XdrFeeBumpTransactionEnvelope(tx, signatures);
  }
}
