// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrEncodedLedgerKey {
  XdrEncodedLedgerKey(this._encodedLedgerKey);

  Uint8List _encodedLedgerKey;
  Uint8List get encodedLedgerKey => this._encodedLedgerKey;
  set encodedLedgerKey(Uint8List value) => this._encodedLedgerKey = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrEncodedLedgerKey encodedEncodedLedgerKey,
  ) {
    int encodedLedgerKeySize = encodedEncodedLedgerKey.encodedLedgerKey.length;
    stream.writeInt(encodedLedgerKeySize);
    stream.write(encodedEncodedLedgerKey.encodedLedgerKey);
  }

  static XdrEncodedLedgerKey decode(XdrDataInputStream stream) {
    int encodedLedgerKeySize = stream.readInt();
    return XdrEncodedLedgerKey(stream.readBytes(encodedLedgerKeySize));
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrEncodedLedgerKey.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrEncodedLedgerKey fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrEncodedLedgerKey.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrEncodedLedgerKey',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrEncodedLedgerKey.
  static XdrEncodedLedgerKey fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrEncodedLedgerKey'),
  );

  /// Returns the SEP-0051 rendering of the wrapped value.
  Object? toXdrJsonValue() =>
      XdrJsonHelper.hex(_encodedLedgerKey, type: 'XdrEncodedLedgerKey');

  /// Reads a XdrEncodedLedgerKey from the SEP-0051 rendering of its value.
  static XdrEncodedLedgerKey fromXdrJsonValue(Object? value) =>
      XdrEncodedLedgerKey(
        XdrJsonHelper.readHex(value, type: 'XdrEncodedLedgerKey'),
      );
}
