// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_ledger_entry_changes.dart';

class XdrOperationMeta {
  XdrLedgerEntryChanges _changes;
  XdrLedgerEntryChanges get changes => this._changes;
  set changes(XdrLedgerEntryChanges value) => this._changes = value;

  XdrOperationMeta(this._changes);

  static void encode(
    XdrDataOutputStream stream,
    XdrOperationMeta encodedOperationMeta,
  ) {
    XdrLedgerEntryChanges.encode(stream, encodedOperationMeta.changes);
  }

  static XdrOperationMeta decode(XdrDataInputStream stream) {
    XdrLedgerEntryChanges changes = XdrLedgerEntryChanges.decode(stream);
    return XdrOperationMeta(changes);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrOperationMeta.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrOperationMeta fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrOperationMeta.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrOperationMeta');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrOperationMeta.
  static XdrOperationMeta fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrOperationMeta'),
  );

  /// Returns the SEP-0051 rendering of this XdrOperationMeta.
  Object? toXdrJsonValue() => <String, Object?>{
    'changes': _changes.toXdrJsonValue(),
  };

  /// Reads a XdrOperationMeta from its SEP-0051 rendering.
  static XdrOperationMeta fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrOperationMeta',
      allowedKeys: const <String>{'changes'},
    );
    final Object? jsonChanges = XdrJsonHelper.readField(
      object,
      'changes',
      type: 'XdrOperationMeta',
    );
    return XdrOperationMeta(
      XdrLedgerEntryChanges.fromXdrJsonValue(jsonChanges),
    );
  }
}
