// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';

class XdrUint256 {
  XdrUint256(this._uint256);

  Uint8List _uint256;
  Uint8List get uint256 => this._uint256;
  set uint256(Uint8List value) => this._uint256 = value;

  static void encode(XdrDataOutputStream stream, XdrUint256 encodedUint256) {
    stream.write(encodedUint256.uint256);
  }

  static XdrUint256 decode(XdrDataInputStream stream) {
    int uint256Size = 32;
    return XdrUint256(stream.readBytes(uint256Size));
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrUint256.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrUint256 fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrUint256.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix: ${TxRepHelper.bytesToHex(_uint256)}');
  }

  static XdrUint256 fromTxRep(Map<String, String> map, String prefix) {
    String? raw = TxRepHelper.getValue(map, prefix);
    if (raw == null) throw Exception('missing $prefix');
    return XdrUint256(TxRepHelper.hexToBytes(raw));
  }
}
