// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_claimable_balance_entry_ext_v1.dart';
import 'xdr_data_io.dart';

class XdrClaimableBalanceEntryExt {
  int _v;

  int get discriminant => this._v;
  set discriminant(int value) => this._v = value;

  /// Alias for [discriminant], the original XDR field name.
  int get v => this._v;
  set v(int value) => this._v = value;

  XdrClaimableBalanceEntryExtV1? _v1;

  XdrClaimableBalanceEntryExtV1? get v1 => this._v1;

  XdrClaimableBalanceEntryExt(this._v);

  set v1(XdrClaimableBalanceEntryExtV1? value) => this._v1 = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrClaimableBalanceEntryExt encodedClaimableBalanceEntryExt,
  ) {
    stream.writeInt(encodedClaimableBalanceEntryExt.discriminant);
    switch (encodedClaimableBalanceEntryExt.discriminant) {
      case 0:
        break;
      case 1:
        XdrClaimableBalanceEntryExtV1.encode(
          stream,
          encodedClaimableBalanceEntryExt._v1!,
        );
        break;
      default:
        break;
    }
  }

  static XdrClaimableBalanceEntryExt decode(XdrDataInputStream stream) {
    int discriminant = stream.readInt();
    XdrClaimableBalanceEntryExt decodedClaimableBalanceEntryExt =
        XdrClaimableBalanceEntryExt(discriminant);
    switch (decodedClaimableBalanceEntryExt.discriminant) {
      case 0:
        break;
      case 1:
        decodedClaimableBalanceEntryExt._v1 =
            XdrClaimableBalanceEntryExtV1.decode(stream);
        break;
      default:
        break;
    }
    return decodedClaimableBalanceEntryExt;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrClaimableBalanceEntryExt.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrClaimableBalanceEntryExt fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrClaimableBalanceEntryExt.decode(XdrDataInputStream(bytes));
  }
}
