// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_claim_predicate_type.dart';
import 'xdr_data_io.dart';
import 'xdr_int64.dart';

class XdrClaimPredicate {
  XdrClaimPredicateType _type;

  XdrClaimPredicateType get discriminant => this._type;

  set discriminant(XdrClaimPredicateType value) => this._type = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrClaimPredicateType get type => this._type;
  set type(XdrClaimPredicateType value) => this._type = value;

  List<XdrClaimPredicate>? _andPredicates;

  List<XdrClaimPredicate>? get andPredicates => this._andPredicates;

  List<XdrClaimPredicate>? _orPredicates;

  List<XdrClaimPredicate>? get orPredicates => this._orPredicates;

  XdrClaimPredicate? _notPredicate;

  XdrClaimPredicate? get notPredicate => this._notPredicate;

  XdrInt64? _absBefore;

  XdrInt64? get absBefore => this._absBefore;

  XdrInt64? _relBefore;

  XdrInt64? get relBefore => this._relBefore;

  XdrClaimPredicate(this._type);

  set andPredicates(List<XdrClaimPredicate>? value) =>
      this._andPredicates = value;

  set orPredicates(List<XdrClaimPredicate>? value) =>
      this._orPredicates = value;

  set notPredicate(XdrClaimPredicate? value) => this._notPredicate = value;

  set absBefore(XdrInt64? value) => this._absBefore = value;

  set relBefore(XdrInt64? value) => this._relBefore = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrClaimPredicate encodedClaimPredicate,
  ) {
    stream.writeInt(encodedClaimPredicate.discriminant.value);
    switch (encodedClaimPredicate.discriminant) {
      case XdrClaimPredicateType.CLAIM_PREDICATE_UNCONDITIONAL:
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_AND:
        int andPredicatessize = encodedClaimPredicate._andPredicates!.length;
        stream.writeInt(andPredicatessize);
        for (int i = 0; i < andPredicatessize; i++) {
          XdrClaimPredicate.encode(
            stream,
            encodedClaimPredicate._andPredicates![i],
          );
        }
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_OR:
        int orPredicatessize = encodedClaimPredicate._orPredicates!.length;
        stream.writeInt(orPredicatessize);
        for (int i = 0; i < orPredicatessize; i++) {
          XdrClaimPredicate.encode(
            stream,
            encodedClaimPredicate._orPredicates![i],
          );
        }
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_NOT:
        if (encodedClaimPredicate._notPredicate == null) {
          stream.writeInt(0);
        } else {
          stream.writeInt(1);
          XdrClaimPredicate.encode(
            stream,
            encodedClaimPredicate._notPredicate!,
          );
        }
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME:
        XdrInt64.encode(stream, encodedClaimPredicate._absBefore!);
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_BEFORE_RELATIVE_TIME:
        XdrInt64.encode(stream, encodedClaimPredicate._relBefore!);
        break;
      default:
        break;
    }
  }

  static XdrClaimPredicate decode(XdrDataInputStream stream) {
    XdrClaimPredicate decodedClaimPredicate = XdrClaimPredicate(
      XdrClaimPredicateType.decode(stream),
    );
    switch (decodedClaimPredicate.discriminant) {
      case XdrClaimPredicateType.CLAIM_PREDICATE_UNCONDITIONAL:
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_AND:
        int andPredicatessize = stream.readInt();
        decodedClaimPredicate._andPredicates = List<XdrClaimPredicate>.empty(
          growable: true,
        );
        for (int i = 0; i < andPredicatessize; i++) {
          decodedClaimPredicate._andPredicates!.add(
            XdrClaimPredicate.decode(stream),
          );
        }
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_OR:
        int orPredicatessize = stream.readInt();
        decodedClaimPredicate._orPredicates = List<XdrClaimPredicate>.empty(
          growable: true,
        );
        for (int i = 0; i < orPredicatessize; i++) {
          decodedClaimPredicate._orPredicates!.add(
            XdrClaimPredicate.decode(stream),
          );
        }
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_NOT:
        int notPredicatePresent = stream.readInt();
        if (notPredicatePresent != 0) {
          decodedClaimPredicate._notPredicate = XdrClaimPredicate.decode(
            stream,
          );
        }
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME:
        decodedClaimPredicate._absBefore = XdrInt64.decode(stream);
        break;
      case XdrClaimPredicateType.CLAIM_PREDICATE_BEFORE_RELATIVE_TIME:
        decodedClaimPredicate._relBefore = XdrInt64.decode(stream);
        break;
      default:
        break;
    }
    return decodedClaimPredicate;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrClaimPredicate.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrClaimPredicate fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrClaimPredicate.decode(XdrDataInputStream(bytes));
  }
}
