// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_account_id.dart';
import 'xdr_allow_trust_op_asset.dart';
import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrAllowTrustOp {
  XdrAccountID _trustor;
  XdrAccountID get trustor => this._trustor;
  set trustor(XdrAccountID value) => this._trustor = value;

  XdrAllowTrustOpAsset _asset;
  XdrAllowTrustOpAsset get asset => this._asset;
  set asset(XdrAllowTrustOpAsset value) => this._asset = value;

  int _authorize;
  int get authorize => this._authorize;
  set authorize(int value) => this._authorize = value;

  XdrAllowTrustOp(this._trustor, this._asset, this._authorize);

  static void encode(
    XdrDataOutputStream stream,
    XdrAllowTrustOp encodedAllowTrustOp,
  ) {
    XdrAccountID.encode(stream, encodedAllowTrustOp.trustor);
    XdrAllowTrustOpAsset.encode(stream, encodedAllowTrustOp.asset);
    stream.writeInt(encodedAllowTrustOp.authorize);
  }

  static XdrAllowTrustOp decode(XdrDataInputStream stream) {
    XdrAccountID trustor = XdrAccountID.decode(stream);
    XdrAllowTrustOpAsset asset = XdrAllowTrustOpAsset.decode(stream);
    int authorize = stream.readInt();
    return XdrAllowTrustOp(trustor, asset, authorize);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrAllowTrustOp.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrAllowTrustOp fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrAllowTrustOp.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.trustor: ${TxRepHelper.formatAccountId(_trustor)}');
    lines.add('$prefix.asset: ${TxRepHelper.formatAllowTrustAsset(_asset)}');
    lines.add('$prefix.authorize: ${_authorize}');
  }

  static XdrAllowTrustOp fromTxRep(Map<String, String> map, String prefix) {
    XdrAccountID trustor = TxRepHelper.parseAccountId(
      TxRepHelper.getValue(map, '$prefix.trustor') ?? '',
    );
    XdrAllowTrustOpAsset asset = TxRepHelper.parseAllowTrustAsset(
      TxRepHelper.getValue(map, '$prefix.asset') ?? '',
    );
    int authorize = TxRepHelper.parseInt(
      TxRepHelper.getValue(map, '$prefix.authorize') ?? '0',
    );
    return XdrAllowTrustOp(trustor, asset, authorize);
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrAllowTrustOp');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrAllowTrustOp.
  static XdrAllowTrustOp fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrAllowTrustOp'),
  );

  /// Returns the SEP-0051 rendering of this XdrAllowTrustOp.
  Object? toXdrJsonValue() => <String, Object?>{
    'trustor': _trustor.toXdrJsonValue(),
    'asset': _asset.toXdrJsonValue(),
    'authorize': XdrJsonHelper.uint32(
      _authorize,
      type: 'XdrAllowTrustOp',
      key: 'authorize',
    ),
  };

  /// Reads a XdrAllowTrustOp from its SEP-0051 rendering.
  static XdrAllowTrustOp fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrAllowTrustOp',
      allowedKeys: const <String>{'trustor', 'asset', 'authorize'},
    );
    final Object? jsonTrustor = XdrJsonHelper.readField(
      object,
      'trustor',
      type: 'XdrAllowTrustOp',
    );
    final Object? jsonAsset = XdrJsonHelper.readField(
      object,
      'asset',
      type: 'XdrAllowTrustOp',
    );
    final Object? jsonAuthorize = XdrJsonHelper.readField(
      object,
      'authorize',
      type: 'XdrAllowTrustOp',
    );
    return XdrAllowTrustOp(
      XdrAccountID.fromXdrJsonValue(jsonTrustor),
      XdrAllowTrustOpAsset.fromXdrJsonValue(jsonAsset),
      XdrJsonHelper.readUint32(
        jsonAuthorize,
        type: 'XdrAllowTrustOp',
        key: 'authorize',
      ),
    );
  }
}
