// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_curve25519_public.dart';
import 'xdr_data_io.dart';
import 'xdr_signature.dart';
import 'xdr_uint64.dart';

class XdrAuthCert {

  XdrCurve25519Public _pubkey;
  XdrCurve25519Public get pubkey => this._pubkey;
  set pubkey(XdrCurve25519Public value) => this._pubkey = value;

  XdrUint64 _expiration;
  XdrUint64 get expiration => this._expiration;
  set expiration(XdrUint64 value) => this._expiration = value;

  XdrSignature _sig;
  XdrSignature get sig => this._sig;
  set sig(XdrSignature value) => this._sig = value;

  XdrAuthCert(this._pubkey, this._expiration, this._sig);

  static void encode(XdrDataOutputStream stream, XdrAuthCert encodedAuthCert) {
    XdrCurve25519Public.encode(stream, encodedAuthCert.pubkey);
    XdrUint64.encode(stream, encodedAuthCert.expiration);
    XdrSignature.encode(stream, encodedAuthCert.sig);
  }

  static XdrAuthCert decode(XdrDataInputStream stream) {
    XdrCurve25519Public pubkey = XdrCurve25519Public.decode(stream);
    XdrUint64 expiration = XdrUint64.decode(stream);
    XdrSignature sig = XdrSignature.decode(stream);
    return XdrAuthCert(pubkey, expiration, sig);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrAuthCert.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrAuthCert fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrAuthCert.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _pubkey.toTxRep('$prefix.pubkey', lines);
    _expiration.toTxRep('$prefix.expiration', lines);
    _sig.toTxRep('$prefix.sig', lines);
  }

  static XdrAuthCert fromTxRep(Map<String, String> map, String prefix) {
    XdrCurve25519Public pubkey = XdrCurve25519Public.fromTxRep(map, '$prefix.pubkey');
    XdrUint64 expiration = XdrUint64.fromTxRep(map, '$prefix.expiration');
    XdrSignature sig = XdrSignature.fromTxRep(map, '$prefix.sig');
    return XdrAuthCert(pubkey, expiration, sig);
  }
}
