// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_sc_spec_udt_union_case_tuple_v0.dart';
import 'xdr_sc_spec_udt_union_case_v0_kind.dart';
import 'xdr_sc_spec_udt_union_case_void_v0.dart';

class XdrSCSpecUDTUnionCaseV0 {
  XdrSCSpecUDTUnionCaseV0Kind _kind;

  XdrSCSpecUDTUnionCaseV0Kind get discriminant => this._kind;

  set discriminant(XdrSCSpecUDTUnionCaseV0Kind value) => this._kind = value;

  XdrSCSpecUDTUnionCaseVoidV0? _voidCase;

  XdrSCSpecUDTUnionCaseVoidV0? get voidCase => this._voidCase;

  XdrSCSpecUDTUnionCaseTupleV0? _tupleCase;

  XdrSCSpecUDTUnionCaseTupleV0? get tupleCase => this._tupleCase;

  XdrSCSpecUDTUnionCaseV0(this._kind);

  set voidCase(XdrSCSpecUDTUnionCaseVoidV0? value) => this._voidCase = value;

  set tupleCase(XdrSCSpecUDTUnionCaseTupleV0? value) => this._tupleCase = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrSCSpecUDTUnionCaseV0 encodedSCSpecUDTUnionCaseV0,
  ) {
    stream.writeInt(encodedSCSpecUDTUnionCaseV0.discriminant.value);
    switch (encodedSCSpecUDTUnionCaseV0.discriminant) {
      case XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_VOID_V0:
        XdrSCSpecUDTUnionCaseVoidV0.encode(
          stream,
          encodedSCSpecUDTUnionCaseV0._voidCase!,
        );
        break;
      case XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_TUPLE_V0:
        XdrSCSpecUDTUnionCaseTupleV0.encode(
          stream,
          encodedSCSpecUDTUnionCaseV0._tupleCase!,
        );
        break;
      default:
        break;
    }
  }

  static XdrSCSpecUDTUnionCaseV0 decode(XdrDataInputStream stream) {
    XdrSCSpecUDTUnionCaseV0 decodedSCSpecUDTUnionCaseV0 =
        XdrSCSpecUDTUnionCaseV0(XdrSCSpecUDTUnionCaseV0Kind.decode(stream));
    switch (decodedSCSpecUDTUnionCaseV0.discriminant) {
      case XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_VOID_V0:
        decodedSCSpecUDTUnionCaseV0._voidCase =
            XdrSCSpecUDTUnionCaseVoidV0.decode(stream);
        break;
      case XdrSCSpecUDTUnionCaseV0Kind.SC_SPEC_UDT_UNION_CASE_TUPLE_V0:
        decodedSCSpecUDTUnionCaseV0._tupleCase =
            XdrSCSpecUDTUnionCaseTupleV0.decode(stream);
        break;
      default:
        break;
    }
    return decodedSCSpecUDTUnionCaseV0;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCSpecUDTUnionCaseV0.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCSpecUDTUnionCaseV0 fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCSpecUDTUnionCaseV0.decode(XdrDataInputStream(bytes));
  }
}
