// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_survey_response_message.dart';
import 'xdr_uint32.dart';

class XdrTimeSlicedSurveyResponseMessage {
  XdrSurveyResponseMessage _response;
  XdrSurveyResponseMessage get response => this._response;
  set response(XdrSurveyResponseMessage value) => this._response = value;

  XdrUint32 _nonce;
  XdrUint32 get nonce => this._nonce;
  set nonce(XdrUint32 value) => this._nonce = value;

  XdrTimeSlicedSurveyResponseMessage(this._response, this._nonce);

  static void encode(
    XdrDataOutputStream stream,
    XdrTimeSlicedSurveyResponseMessage encodedTimeSlicedSurveyResponseMessage,
  ) {
    XdrSurveyResponseMessage.encode(
      stream,
      encodedTimeSlicedSurveyResponseMessage.response,
    );
    XdrUint32.encode(stream, encodedTimeSlicedSurveyResponseMessage.nonce);
  }

  static XdrTimeSlicedSurveyResponseMessage decode(XdrDataInputStream stream) {
    XdrSurveyResponseMessage response = XdrSurveyResponseMessage.decode(stream);
    XdrUint32 nonce = XdrUint32.decode(stream);
    return XdrTimeSlicedSurveyResponseMessage(response, nonce);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrTimeSlicedSurveyResponseMessage.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrTimeSlicedSurveyResponseMessage fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrTimeSlicedSurveyResponseMessage.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrTimeSlicedSurveyResponseMessage',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrTimeSlicedSurveyResponseMessage.
  static XdrTimeSlicedSurveyResponseMessage fromXdrJson(String json) =>
      fromXdrJsonValue(
        XdrJsonHelper.decodeDocument(
          json,
          type: 'XdrTimeSlicedSurveyResponseMessage',
        ),
      );

  /// Returns the SEP-0051 rendering of this XdrTimeSlicedSurveyResponseMessage.
  Object? toXdrJsonValue() => <String, Object?>{
    'response': _response.toXdrJsonValue(),
    'nonce': _nonce.toXdrJsonValue(),
  };

  /// Reads a XdrTimeSlicedSurveyResponseMessage from its SEP-0051 rendering.
  static XdrTimeSlicedSurveyResponseMessage fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrTimeSlicedSurveyResponseMessage',
      allowedKeys: const <String>{'response', 'nonce'},
    );
    final Object? jsonResponse = XdrJsonHelper.readField(
      object,
      'response',
      type: 'XdrTimeSlicedSurveyResponseMessage',
    );
    final Object? jsonNonce = XdrJsonHelper.readField(
      object,
      'nonce',
      type: 'XdrTimeSlicedSurveyResponseMessage',
    );
    return XdrTimeSlicedSurveyResponseMessage(
      XdrSurveyResponseMessage.fromXdrJsonValue(jsonResponse),
      XdrUint32.fromXdrJsonValue(jsonNonce),
    );
  }
}
