// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_ledger_footprint.dart';
import 'xdr_uint32.dart';

class XdrSorobanResources {
  XdrLedgerFootprint _footprint;
  XdrLedgerFootprint get footprint => this._footprint;
  set footprint(XdrLedgerFootprint value) => this._footprint = value;

  XdrUint32 _instructions;
  XdrUint32 get instructions => this._instructions;
  set instructions(XdrUint32 value) => this._instructions = value;

  XdrUint32 _diskReadBytes;
  XdrUint32 get diskReadBytes => this._diskReadBytes;
  set diskReadBytes(XdrUint32 value) => this._diskReadBytes = value;

  XdrUint32 _writeBytes;
  XdrUint32 get writeBytes => this._writeBytes;
  set writeBytes(XdrUint32 value) => this._writeBytes = value;

  XdrSorobanResources(
    this._footprint,
    this._instructions,
    this._diskReadBytes,
    this._writeBytes,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrSorobanResources encodedSorobanResources,
  ) {
    XdrLedgerFootprint.encode(stream, encodedSorobanResources.footprint);
    XdrUint32.encode(stream, encodedSorobanResources.instructions);
    XdrUint32.encode(stream, encodedSorobanResources.diskReadBytes);
    XdrUint32.encode(stream, encodedSorobanResources.writeBytes);
  }

  static XdrSorobanResources decode(XdrDataInputStream stream) {
    XdrLedgerFootprint footprint = XdrLedgerFootprint.decode(stream);
    XdrUint32 instructions = XdrUint32.decode(stream);
    XdrUint32 diskReadBytes = XdrUint32.decode(stream);
    XdrUint32 writeBytes = XdrUint32.decode(stream);
    return XdrSorobanResources(
      footprint,
      instructions,
      diskReadBytes,
      writeBytes,
    );
  }
}
