// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_decorated_signature.dart';
import 'xdr_transaction.dart';

class XdrTransactionV1Envelope {
  XdrTransaction _tx;
  XdrTransaction get tx => this._tx;
  set tx(XdrTransaction value) => this._tx = value;

  List<XdrDecoratedSignature> _signatures;
  List<XdrDecoratedSignature> get signatures => this._signatures;
  set signatures(List<XdrDecoratedSignature> value) => this._signatures = value;

  XdrTransactionV1Envelope(this._tx, this._signatures);

  static void encode(
    XdrDataOutputStream stream,
    XdrTransactionV1Envelope encodedTransactionV1Envelope,
  ) {
    XdrTransaction.encode(stream, encodedTransactionV1Envelope.tx);
    int signaturessize = encodedTransactionV1Envelope.signatures.length;
    stream.writeInt(signaturessize);
    for (int i = 0; i < signaturessize; i++) {
      XdrDecoratedSignature.encode(
        stream,
        encodedTransactionV1Envelope.signatures[i],
      );
    }
  }

  static XdrTransactionV1Envelope decode(XdrDataInputStream stream) {
    XdrTransaction tx = XdrTransaction.decode(stream);
    int signaturessize = stream.readInt();
    List<XdrDecoratedSignature> signatures = List<XdrDecoratedSignature>.empty(
      growable: true,
    );
    for (int i = 0; i < signaturessize; i++) {
      signatures.add(XdrDecoratedSignature.decode(stream));
    }
    return XdrTransactionV1Envelope(tx, signatures);
  }
}
