// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_sc_spec_type_def.dart';

class XdrSCSpecUDTStructFieldV0 {
  String _doc;
  String get doc => this._doc;
  set doc(String value) => this._doc = value;

  String _name;
  String get name => this._name;
  set name(String value) => this._name = value;

  XdrSCSpecTypeDef _type;
  XdrSCSpecTypeDef get type => this._type;
  set type(XdrSCSpecTypeDef value) => this._type = value;

  XdrSCSpecUDTStructFieldV0(this._doc, this._name, this._type);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCSpecUDTStructFieldV0 encodedSCSpecUDTStructFieldV0,
  ) {
    stream.writeString(encodedSCSpecUDTStructFieldV0.doc);
    stream.writeString(encodedSCSpecUDTStructFieldV0.name);
    XdrSCSpecTypeDef.encode(stream, encodedSCSpecUDTStructFieldV0.type);
  }

  static XdrSCSpecUDTStructFieldV0 decode(XdrDataInputStream stream) {
    String doc = stream.readString();
    String name = stream.readString();
    XdrSCSpecTypeDef type = XdrSCSpecTypeDef.decode(stream);
    return XdrSCSpecUDTStructFieldV0(doc, name, type);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCSpecUDTStructFieldV0.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCSpecUDTStructFieldV0 fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCSpecUDTStructFieldV0.decode(XdrDataInputStream(bytes));
  }
}
