// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_change_trust_asset.dart';
import 'xdr_data_io.dart';
import 'xdr_int64.dart';
import 'xdr_json_helper.dart';

class XdrChangeTrustOp {
  XdrChangeTrustAsset _line;
  XdrChangeTrustAsset get line => this._line;
  set line(XdrChangeTrustAsset value) => this._line = value;

  XdrInt64 _limit;
  XdrInt64 get limit => this._limit;
  set limit(XdrInt64 value) => this._limit = value;

  XdrChangeTrustOp(this._line, this._limit);

  static void encode(
    XdrDataOutputStream stream,
    XdrChangeTrustOp encodedChangeTrustOp,
  ) {
    XdrChangeTrustAsset.encode(stream, encodedChangeTrustOp.line);
    XdrInt64.encode(stream, encodedChangeTrustOp.limit);
  }

  static XdrChangeTrustOp decode(XdrDataInputStream stream) {
    XdrChangeTrustAsset line = XdrChangeTrustAsset.decode(stream);
    XdrInt64 limit = XdrInt64.decode(stream);
    return XdrChangeTrustOp(line, limit);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrChangeTrustOp.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrChangeTrustOp fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrChangeTrustOp.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _line.toTxRep('$prefix.line', lines);
    _limit.toTxRep('$prefix.limit', lines);
  }

  static XdrChangeTrustOp fromTxRep(Map<String, String> map, String prefix) {
    XdrChangeTrustAsset line = XdrChangeTrustAsset.fromTxRep(
      map,
      '$prefix.line',
    );
    XdrInt64 limit = XdrInt64.fromTxRep(map, '$prefix.limit');
    return XdrChangeTrustOp(line, limit);
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrChangeTrustOp');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrChangeTrustOp.
  static XdrChangeTrustOp fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrChangeTrustOp'),
  );

  /// Returns the SEP-0051 rendering of this XdrChangeTrustOp.
  Object? toXdrJsonValue() => <String, Object?>{
    'line': _line.toXdrJsonValue(),
    'limit': _limit.toXdrJsonValue(),
  };

  /// Reads a XdrChangeTrustOp from its SEP-0051 rendering.
  static XdrChangeTrustOp fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrChangeTrustOp',
      allowedKeys: const <String>{'line', 'limit'},
    );
    final Object? jsonLine = XdrJsonHelper.readField(
      object,
      'line',
      type: 'XdrChangeTrustOp',
    );
    final Object? jsonLimit = XdrJsonHelper.readField(
      object,
      'limit',
      type: 'XdrChangeTrustOp',
    );
    return XdrChangeTrustOp(
      XdrChangeTrustAsset.fromXdrJsonValue(jsonLine),
      XdrInt64.fromXdrJsonValue(jsonLimit),
    );
  }
}
