// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrSCBytes {
  XdrSCBytes(this._sCBytes);

  Uint8List _sCBytes;
  Uint8List get sCBytes => this._sCBytes;
  set sCBytes(Uint8List value) => this._sCBytes = value;

  static void encode(XdrDataOutputStream stream, XdrSCBytes encodedSCBytes) {
    int sCBytesSize = encodedSCBytes.sCBytes.length;
    stream.writeInt(sCBytesSize);
    stream.write(encodedSCBytes.sCBytes);
  }

  static XdrSCBytes decode(XdrDataInputStream stream) {
    int sCBytesSize = stream.readInt();
    return XdrSCBytes(stream.readBytes(sCBytesSize));
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCBytes.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCBytes fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCBytes.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix: ${TxRepHelper.bytesToHex(_sCBytes)}');
  }

  static XdrSCBytes fromTxRep(Map<String, String> map, String prefix) {
    String? raw = TxRepHelper.getValue(map, prefix);
    if (raw == null) throw Exception('missing $prefix');
    return XdrSCBytes(TxRepHelper.hexToBytes(raw));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrSCBytes');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrSCBytes.
  static XdrSCBytes fromXdrJson(String json) =>
      fromXdrJsonValue(XdrJsonHelper.decodeDocument(json, type: 'XdrSCBytes'));

  /// Returns the SEP-0051 rendering of the wrapped value.
  Object? toXdrJsonValue() => XdrJsonHelper.hex(_sCBytes, type: 'XdrSCBytes');

  /// Reads a XdrSCBytes from the SEP-0051 rendering of its value.
  static XdrSCBytes fromXdrJsonValue(Object? value) =>
      XdrSCBytes(XdrJsonHelper.readHex(value, type: 'XdrSCBytes'));
}
