// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_sc_spec_udt_error_enum_case_v0.dart';

class XdrSCSpecUDTErrorEnumV0 {
  String _doc;
  String get doc => this._doc;
  set doc(String value) => this._doc = value;

  String _lib;
  String get lib => this._lib;
  set lib(String value) => this._lib = value;

  String _name;
  String get name => this._name;
  set name(String value) => this._name = value;

  List<XdrSCSpecUDTErrorEnumCaseV0> _cases;
  List<XdrSCSpecUDTErrorEnumCaseV0> get cases => this._cases;
  set cases(List<XdrSCSpecUDTErrorEnumCaseV0> value) => this._cases = value;

  XdrSCSpecUDTErrorEnumV0(this._doc, this._lib, this._name, this._cases);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCSpecUDTErrorEnumV0 encodedSCSpecUDTErrorEnumV0,
  ) {
    stream.writeString(encodedSCSpecUDTErrorEnumV0.doc);
    stream.writeString(encodedSCSpecUDTErrorEnumV0.lib);
    stream.writeString(encodedSCSpecUDTErrorEnumV0.name);
    int casessize = encodedSCSpecUDTErrorEnumV0.cases.length;
    stream.writeInt(casessize);
    for (int i = 0; i < casessize; i++) {
      XdrSCSpecUDTErrorEnumCaseV0.encode(
        stream,
        encodedSCSpecUDTErrorEnumV0.cases[i],
      );
    }
  }

  static XdrSCSpecUDTErrorEnumV0 decode(XdrDataInputStream stream) {
    String doc = stream.readString();
    String lib = stream.readString();
    String name = stream.readString();
    int casessize = stream.readInt();
    List<XdrSCSpecUDTErrorEnumCaseV0> cases =
        List<XdrSCSpecUDTErrorEnumCaseV0>.empty(growable: true);
    for (int i = 0; i < casessize; i++) {
      cases.add(XdrSCSpecUDTErrorEnumCaseV0.decode(stream));
    }
    return XdrSCSpecUDTErrorEnumV0(doc, lib, name, cases);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCSpecUDTErrorEnumV0.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCSpecUDTErrorEnumV0 fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCSpecUDTErrorEnumV0.decode(XdrDataInputStream(bytes));
  }
}
