// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_contract_executable.dart';
import 'xdr_contract_id_preimage.dart';
import 'xdr_data_io.dart';

class XdrCreateContractArgs {
  XdrContractIDPreimage _contractIDPreimage;
  XdrContractIDPreimage get contractIDPreimage => this._contractIDPreimage;
  set contractIDPreimage(XdrContractIDPreimage value) =>
      this._contractIDPreimage = value;

  XdrContractExecutable _executable;
  XdrContractExecutable get executable => this._executable;
  set executable(XdrContractExecutable value) => this._executable = value;

  XdrCreateContractArgs(this._contractIDPreimage, this._executable);

  static void encode(
    XdrDataOutputStream stream,
    XdrCreateContractArgs encodedCreateContractArgs,
  ) {
    XdrContractIDPreimage.encode(
      stream,
      encodedCreateContractArgs.contractIDPreimage,
    );
    XdrContractExecutable.encode(stream, encodedCreateContractArgs.executable);
  }

  static XdrCreateContractArgs decode(XdrDataInputStream stream) {
    XdrContractIDPreimage contractIDPreimage = XdrContractIDPreimage.decode(
      stream,
    );
    XdrContractExecutable executable = XdrContractExecutable.decode(stream);
    return XdrCreateContractArgs(contractIDPreimage, executable);
  }
}
