// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_data_value.dart';
import 'xdr_json_helper.dart';
import 'xdr_string64.dart';

class XdrManageDataOp {
  XdrString64 _dataName;
  XdrString64 get dataName => this._dataName;
  set dataName(XdrString64 value) => this._dataName = value;

  XdrDataValue? _dataValue;
  XdrDataValue? get dataValue => this._dataValue;
  set dataValue(XdrDataValue? value) => this._dataValue = value;

  XdrManageDataOp(this._dataName, this._dataValue);

  static void encode(
    XdrDataOutputStream stream,
    XdrManageDataOp encodedManageDataOp,
  ) {
    XdrString64.encode(stream, encodedManageDataOp.dataName);
    if (encodedManageDataOp.dataValue != null) {
      stream.writeInt(1);
      XdrDataValue.encode(stream, encodedManageDataOp.dataValue!);
    } else {
      stream.writeInt(0);
    }
  }

  static XdrManageDataOp decode(XdrDataInputStream stream) {
    XdrString64 dataName = XdrString64.decode(stream);
    XdrDataValue? dataValue;
    int dataValuePresent = stream.readInt();
    if (dataValuePresent != 0) {
      dataValue = XdrDataValue.decode(stream);
    }
    return XdrManageDataOp(dataName, dataValue);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrManageDataOp.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrManageDataOp fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrManageDataOp.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _dataName.toTxRep('$prefix.dataName', lines);
    if (_dataValue != null) {
      lines.add('$prefix.dataValue._present: true');
      _dataValue!.toTxRep('$prefix.dataValue', lines);
    } else {
      lines.add('$prefix.dataValue._present: false');
    }
  }

  static XdrManageDataOp fromTxRep(Map<String, String> map, String prefix) {
    XdrString64 dataName = XdrString64.fromTxRep(map, '$prefix.dataName');
    XdrDataValue? dataValue;
    String? dataValuePresent = TxRepHelper.getValue(
      map,
      '$prefix.dataValue._present',
    );
    if (dataValuePresent != null && dataValuePresent == 'true') {
      dataValue = XdrDataValue.fromTxRep(map, '$prefix.dataValue');
    }
    return XdrManageDataOp(dataName, dataValue);
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrManageDataOp');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrManageDataOp.
  static XdrManageDataOp fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrManageDataOp'),
  );

  /// Returns the SEP-0051 rendering of this XdrManageDataOp.
  Object? toXdrJsonValue() => <String, Object?>{
    'data_name': _dataName.toXdrJsonValue(),
    'data_value': _dataValue == null ? null : _dataValue!.toXdrJsonValue(),
  };

  /// Reads a XdrManageDataOp from its SEP-0051 rendering.
  static XdrManageDataOp fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrManageDataOp',
      allowedKeys: const <String>{'data_name', 'data_value'},
    );
    final Object? jsonDataName = XdrJsonHelper.readField(
      object,
      'data_name',
      type: 'XdrManageDataOp',
    );
    final Object? jsonDataValue = XdrJsonHelper.readField(
      object,
      'data_value',
      type: 'XdrManageDataOp',
    );
    return XdrManageDataOp(
      XdrString64.fromXdrJsonValue(jsonDataName),
      jsonDataValue == null
          ? null
          : XdrDataValue.fromXdrJsonValue(jsonDataValue),
    );
  }
}
