// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_claim_atom_type.dart';
import 'xdr_claim_liquidity_atom.dart';
import 'xdr_claim_offer_atom.dart';
import 'xdr_claim_offer_atom_v0.dart';
import 'xdr_data_io.dart';

class XdrClaimAtom {
  XdrClaimAtomType _type;

  XdrClaimAtomType get discriminant => this._type;

  set discriminant(XdrClaimAtomType value) => this._type = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrClaimAtomType get type => this._type;
  set type(XdrClaimAtomType value) => this._type = value;

  XdrClaimOfferAtomV0? _v0;

  XdrClaimOfferAtomV0? get v0 => this._v0;

  XdrClaimOfferAtom? _orderBook;

  XdrClaimOfferAtom? get orderBook => this._orderBook;

  XdrClaimLiquidityAtom? _liquidityPool;

  XdrClaimLiquidityAtom? get liquidityPool => this._liquidityPool;

  XdrClaimAtom(this._type);

  set v0(XdrClaimOfferAtomV0? value) => this._v0 = value;

  set orderBook(XdrClaimOfferAtom? value) => this._orderBook = value;

  set liquidityPool(XdrClaimLiquidityAtom? value) =>
      this._liquidityPool = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrClaimAtom encodedClaimAtom,
  ) {
    stream.writeInt(encodedClaimAtom.discriminant.value);
    switch (encodedClaimAtom.discriminant) {
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_V0:
        XdrClaimOfferAtomV0.encode(stream, encodedClaimAtom._v0!);
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_ORDER_BOOK:
        XdrClaimOfferAtom.encode(stream, encodedClaimAtom._orderBook!);
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
        XdrClaimLiquidityAtom.encode(stream, encodedClaimAtom._liquidityPool!);
        break;
      default:
        break;
    }
  }

  static XdrClaimAtom decode(XdrDataInputStream stream) {
    XdrClaimAtom decodedClaimAtom = XdrClaimAtom(
      XdrClaimAtomType.decode(stream),
    );
    switch (decodedClaimAtom.discriminant) {
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_V0:
        decodedClaimAtom._v0 = XdrClaimOfferAtomV0.decode(stream);
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_ORDER_BOOK:
        decodedClaimAtom._orderBook = XdrClaimOfferAtom.decode(stream);
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
        decodedClaimAtom._liquidityPool = XdrClaimLiquidityAtom.decode(stream);
        break;
      default:
        break;
    }
    return decodedClaimAtom;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrClaimAtom.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrClaimAtom fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrClaimAtom.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.type: ${discriminant.enumName()}');
    switch (discriminant) {
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_V0:
        _v0!.toTxRep('$prefix.v0', lines);
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_ORDER_BOOK:
        _orderBook!.toTxRep('$prefix.orderBook', lines);
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
        _liquidityPool!.toTxRep('$prefix.liquidityPool', lines);
        break;
      default:
        break;
    }
  }

  static XdrClaimAtom fromTxRep(Map<String, String> map, String prefix) {
    XdrClaimAtomType disc = XdrClaimAtomType.fromTxRepName(
      TxRepHelper.getValue(map, '$prefix.type') ?? '',
    );
    XdrClaimAtom result = XdrClaimAtom(disc);
    switch (result.discriminant) {
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_V0:
        result._v0 = XdrClaimOfferAtomV0.fromTxRep(map, '$prefix.v0');
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_ORDER_BOOK:
        result._orderBook = XdrClaimOfferAtom.fromTxRep(
          map,
          '$prefix.orderBook',
        );
        break;
      case XdrClaimAtomType.CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
        result._liquidityPool = XdrClaimLiquidityAtom.fromTxRep(
          map,
          '$prefix.liquidityPool',
        );
        break;
      default:
        break;
    }
    return result;
  }
}
