// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_hash.dart';

class XdrLedgerKeyTTL {
  XdrHash _keyHash;
  XdrHash get keyHash => this._keyHash;
  set keyHash(XdrHash value) => this._keyHash = value;

  XdrLedgerKeyTTL(this._keyHash);

  static void encode(
    XdrDataOutputStream stream,
    XdrLedgerKeyTTL encodedLedgerKeyTTL,
  ) {
    XdrHash.encode(stream, encodedLedgerKeyTTL.keyHash);
  }

  static XdrLedgerKeyTTL decode(XdrDataInputStream stream) {
    XdrHash keyHash = XdrHash.decode(stream);
    return XdrLedgerKeyTTL(keyHash);
  }
}
