// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_uint32.dart';

class XdrConfigSettingContractParallelComputeV0 {
  XdrUint32 _ledgerMaxDependentTxClusters;
  XdrUint32 get ledgerMaxDependentTxClusters =>
      this._ledgerMaxDependentTxClusters;
  set ledgerMaxDependentTxClusters(XdrUint32 value) =>
      this._ledgerMaxDependentTxClusters = value;

  XdrConfigSettingContractParallelComputeV0(this._ledgerMaxDependentTxClusters);

  static void encode(
    XdrDataOutputStream stream,
    XdrConfigSettingContractParallelComputeV0
    encodedConfigSettingContractParallelComputeV0,
  ) {
    XdrUint32.encode(
      stream,
      encodedConfigSettingContractParallelComputeV0
          .ledgerMaxDependentTxClusters,
    );
  }

  static XdrConfigSettingContractParallelComputeV0 decode(
    XdrDataInputStream stream,
  ) {
    XdrUint32 ledgerMaxDependentTxClusters = XdrUint32.decode(stream);
    return XdrConfigSettingContractParallelComputeV0(
      ledgerMaxDependentTxClusters,
    );
  }
}
