// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_create_contract_args.dart';
import 'xdr_create_contract_args_v2.dart';
import 'xdr_data_io.dart';
import 'xdr_invoke_contract_args.dart';
import 'xdr_soroban_authorized_function_type.dart';

class XdrSorobanAuthorizedFunctionBase {
  XdrSorobanAuthorizedFunctionType _type;

  XdrSorobanAuthorizedFunctionType get discriminant => this._type;

  set discriminant(XdrSorobanAuthorizedFunctionType value) =>
      this._type = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrSorobanAuthorizedFunctionType get type => this._type;
  set type(XdrSorobanAuthorizedFunctionType value) => this._type = value;

  XdrInvokeContractArgs? _contractFn;

  XdrInvokeContractArgs? get contractFn => this._contractFn;

  XdrCreateContractArgs? _createContractHostFn;

  XdrCreateContractArgs? get createContractHostFn => this._createContractHostFn;

  XdrCreateContractArgsV2? _createContractV2HostFn;

  XdrCreateContractArgsV2? get createContractV2HostFn =>
      this._createContractV2HostFn;

  XdrSorobanAuthorizedFunctionBase(this._type);

  set contractFn(XdrInvokeContractArgs? value) => this._contractFn = value;

  set createContractHostFn(XdrCreateContractArgs? value) =>
      this._createContractHostFn = value;

  set createContractV2HostFn(XdrCreateContractArgsV2? value) =>
      this._createContractV2HostFn = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrSorobanAuthorizedFunctionBase encodedSorobanAuthorizedFunction,
  ) {
    stream.writeInt(encodedSorobanAuthorizedFunction.discriminant.value);
    switch (encodedSorobanAuthorizedFunction.discriminant) {
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
        XdrInvokeContractArgs.encode(
          stream,
          encodedSorobanAuthorizedFunction._contractFn!,
        );
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
        XdrCreateContractArgs.encode(
          stream,
          encodedSorobanAuthorizedFunction._createContractHostFn!,
        );
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN:
        XdrCreateContractArgsV2.encode(
          stream,
          encodedSorobanAuthorizedFunction._createContractV2HostFn!,
        );
        break;
      default:
        break;
    }
  }

  static XdrSorobanAuthorizedFunctionBase decode(XdrDataInputStream stream) {
    return decodeAs(stream, XdrSorobanAuthorizedFunctionBase.new);
  }

  static T decodeAs<T extends XdrSorobanAuthorizedFunctionBase>(
    XdrDataInputStream stream,
    T Function(XdrSorobanAuthorizedFunctionType) constructor,
  ) {
    T decoded = constructor(XdrSorobanAuthorizedFunctionType.decode(stream));
    switch (decoded.discriminant) {
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
        decoded._contractFn = XdrInvokeContractArgs.decode(stream);
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
        decoded._createContractHostFn = XdrCreateContractArgs.decode(stream);
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN:
        decoded._createContractV2HostFn = XdrCreateContractArgsV2.decode(
          stream,
        );
        break;
      default:
        break;
    }
    return decoded;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSorobanAuthorizedFunctionBase.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSorobanAuthorizedFunctionBase fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSorobanAuthorizedFunctionBase.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.type: ${discriminant.enumName()}');
    switch (discriminant) {
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
        _contractFn!.toTxRep('$prefix.contractFn', lines);
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
        _createContractHostFn!.toTxRep('$prefix.createContractHostFn', lines);
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN:
        _createContractV2HostFn!.toTxRep(
          '$prefix.createContractV2HostFn',
          lines,
        );
        break;
      default:
        break;
    }
  }

  static XdrSorobanAuthorizedFunctionBase fromTxRep(
    Map<String, String> map,
    String prefix,
  ) {
    XdrSorobanAuthorizedFunctionType disc =
        XdrSorobanAuthorizedFunctionType.fromTxRepName(
          TxRepHelper.getValue(map, '$prefix.type') ?? '',
        );
    XdrSorobanAuthorizedFunctionBase result = XdrSorobanAuthorizedFunctionBase(
      disc,
    );
    switch (result.discriminant) {
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN:
        result._contractFn = XdrInvokeContractArgs.fromTxRep(
          map,
          '$prefix.contractFn',
        );
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN:
        result._createContractHostFn = XdrCreateContractArgs.fromTxRep(
          map,
          '$prefix.createContractHostFn',
        );
        break;
      case XdrSorobanAuthorizedFunctionType
          .SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN:
        result._createContractV2HostFn = XdrCreateContractArgsV2.fromTxRep(
          map,
          '$prefix.createContractV2HostFn',
        );
        break;
      default:
        break;
    }
    return result;
  }
}
