// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_generalized_transaction_set.dart';

class XdrTransactionHistoryEntryExt {
  int _v;

  int get discriminant => this._v;
  set discriminant(int value) => this._v = value;

  XdrGeneralizedTransactionSet? _generalizedTxSet;

  XdrGeneralizedTransactionSet? get generalizedTxSet => this._generalizedTxSet;

  XdrTransactionHistoryEntryExt(this._v);

  set generalizedTxSet(XdrGeneralizedTransactionSet? value) =>
      this._generalizedTxSet = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrTransactionHistoryEntryExt encodedTransactionHistoryEntryExt,
  ) {
    stream.writeInt(encodedTransactionHistoryEntryExt.discriminant);
    switch (encodedTransactionHistoryEntryExt.discriminant) {
      case 0:
        break;
      case 1:
        XdrGeneralizedTransactionSet.encode(
          stream,
          encodedTransactionHistoryEntryExt._generalizedTxSet!,
        );
        break;
      default:
        break;
    }
  }

  static XdrTransactionHistoryEntryExt decode(XdrDataInputStream stream) {
    int discriminant = stream.readInt();
    XdrTransactionHistoryEntryExt decodedTransactionHistoryEntryExt =
        XdrTransactionHistoryEntryExt(discriminant);
    switch (decodedTransactionHistoryEntryExt.discriminant) {
      case 0:
        break;
      case 1:
        decodedTransactionHistoryEntryExt._generalizedTxSet =
            XdrGeneralizedTransactionSet.decode(stream);
        break;
      default:
        break;
    }
    return decodedTransactionHistoryEntryExt;
  }
}
