// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_time_sliced_peer_data.dart';

class XdrTimeSlicedPeerDataList {
  XdrTimeSlicedPeerDataList(this._timeSlicedPeerDataList);

  List<XdrTimeSlicedPeerData> _timeSlicedPeerDataList;
  List<XdrTimeSlicedPeerData> get timeSlicedPeerDataList =>
      this._timeSlicedPeerDataList;
  set timeSlicedPeerDataList(List<XdrTimeSlicedPeerData> value) =>
      this._timeSlicedPeerDataList = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrTimeSlicedPeerDataList encodedTimeSlicedPeerDataList,
  ) {
    int size = encodedTimeSlicedPeerDataList.timeSlicedPeerDataList.length;
    stream.writeInt(size);
    for (int i = 0; i < size; i++) {
      XdrTimeSlicedPeerData.encode(
        stream,
        encodedTimeSlicedPeerDataList.timeSlicedPeerDataList[i],
      );
    }
  }

  static XdrTimeSlicedPeerDataList decode(XdrDataInputStream stream) {
    int size = stream.readInt();
    List<XdrTimeSlicedPeerData> items = List<XdrTimeSlicedPeerData>.empty(
      growable: true,
    );
    for (int i = 0; i < size; i++) {
      items.add(XdrTimeSlicedPeerData.decode(stream));
    }
    return XdrTimeSlicedPeerDataList(items);
  }
}
