// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_hash.dart';
import 'xdr_int64.dart';
import 'xdr_json_helper.dart';
import 'xdr_ledger_header_ext.dart';
import 'xdr_stellar_value.dart';
import 'xdr_uint32.dart';
import 'xdr_uint64.dart';

class XdrLedgerHeader {
  XdrUint32 _ledgerVersion;
  XdrUint32 get ledgerVersion => this._ledgerVersion;
  set ledgerVersion(XdrUint32 value) => this._ledgerVersion = value;

  XdrHash _previousLedgerHash;
  XdrHash get previousLedgerHash => this._previousLedgerHash;
  set previousLedgerHash(XdrHash value) => this._previousLedgerHash = value;

  XdrStellarValue _scpValue;
  XdrStellarValue get scpValue => this._scpValue;
  set scpValue(XdrStellarValue value) => this._scpValue = value;

  XdrHash _txSetResultHash;
  XdrHash get txSetResultHash => this._txSetResultHash;
  set txSetResultHash(XdrHash value) => this._txSetResultHash = value;

  XdrHash _bucketListHash;
  XdrHash get bucketListHash => this._bucketListHash;
  set bucketListHash(XdrHash value) => this._bucketListHash = value;

  XdrUint32 _ledgerSeq;
  XdrUint32 get ledgerSeq => this._ledgerSeq;
  set ledgerSeq(XdrUint32 value) => this._ledgerSeq = value;

  XdrInt64 _totalCoins;
  XdrInt64 get totalCoins => this._totalCoins;
  set totalCoins(XdrInt64 value) => this._totalCoins = value;

  XdrInt64 _feePool;
  XdrInt64 get feePool => this._feePool;
  set feePool(XdrInt64 value) => this._feePool = value;

  XdrUint32 _inflationSeq;
  XdrUint32 get inflationSeq => this._inflationSeq;
  set inflationSeq(XdrUint32 value) => this._inflationSeq = value;

  XdrUint64 _idPool;
  XdrUint64 get idPool => this._idPool;
  set idPool(XdrUint64 value) => this._idPool = value;

  XdrUint32 _baseFee;
  XdrUint32 get baseFee => this._baseFee;
  set baseFee(XdrUint32 value) => this._baseFee = value;

  XdrUint32 _baseReserve;
  XdrUint32 get baseReserve => this._baseReserve;
  set baseReserve(XdrUint32 value) => this._baseReserve = value;

  XdrUint32 _maxTxSetSize;
  XdrUint32 get maxTxSetSize => this._maxTxSetSize;
  set maxTxSetSize(XdrUint32 value) => this._maxTxSetSize = value;

  List<XdrHash> _skipList;
  List<XdrHash> get skipList => this._skipList;
  set skipList(List<XdrHash> value) => this._skipList = value;

  XdrLedgerHeaderExt _ext;
  XdrLedgerHeaderExt get ext => this._ext;
  set ext(XdrLedgerHeaderExt value) => this._ext = value;

  XdrLedgerHeader(
    this._ledgerVersion,
    this._previousLedgerHash,
    this._scpValue,
    this._txSetResultHash,
    this._bucketListHash,
    this._ledgerSeq,
    this._totalCoins,
    this._feePool,
    this._inflationSeq,
    this._idPool,
    this._baseFee,
    this._baseReserve,
    this._maxTxSetSize,
    this._skipList,
    this._ext,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrLedgerHeader encodedLedgerHeader,
  ) {
    XdrUint32.encode(stream, encodedLedgerHeader.ledgerVersion);
    XdrHash.encode(stream, encodedLedgerHeader.previousLedgerHash);
    XdrStellarValue.encode(stream, encodedLedgerHeader.scpValue);
    XdrHash.encode(stream, encodedLedgerHeader.txSetResultHash);
    XdrHash.encode(stream, encodedLedgerHeader.bucketListHash);
    XdrUint32.encode(stream, encodedLedgerHeader.ledgerSeq);
    XdrInt64.encode(stream, encodedLedgerHeader.totalCoins);
    XdrInt64.encode(stream, encodedLedgerHeader.feePool);
    XdrUint32.encode(stream, encodedLedgerHeader.inflationSeq);
    XdrUint64.encode(stream, encodedLedgerHeader.idPool);
    XdrUint32.encode(stream, encodedLedgerHeader.baseFee);
    XdrUint32.encode(stream, encodedLedgerHeader.baseReserve);
    XdrUint32.encode(stream, encodedLedgerHeader.maxTxSetSize);
    int skipListsize = encodedLedgerHeader.skipList.length;
    for (int i = 0; i < skipListsize; i++) {
      XdrHash.encode(stream, encodedLedgerHeader.skipList[i]);
    }
    XdrLedgerHeaderExt.encode(stream, encodedLedgerHeader.ext);
  }

  static XdrLedgerHeader decode(XdrDataInputStream stream) {
    XdrUint32 ledgerVersion = XdrUint32.decode(stream);
    XdrHash previousLedgerHash = XdrHash.decode(stream);
    XdrStellarValue scpValue = XdrStellarValue.decode(stream);
    XdrHash txSetResultHash = XdrHash.decode(stream);
    XdrHash bucketListHash = XdrHash.decode(stream);
    XdrUint32 ledgerSeq = XdrUint32.decode(stream);
    XdrInt64 totalCoins = XdrInt64.decode(stream);
    XdrInt64 feePool = XdrInt64.decode(stream);
    XdrUint32 inflationSeq = XdrUint32.decode(stream);
    XdrUint64 idPool = XdrUint64.decode(stream);
    XdrUint32 baseFee = XdrUint32.decode(stream);
    XdrUint32 baseReserve = XdrUint32.decode(stream);
    XdrUint32 maxTxSetSize = XdrUint32.decode(stream);
    List<XdrHash> skipList = List<XdrHash>.empty(growable: true);
    for (int i = 0; i < 4; i++) {
      skipList.add(XdrHash.decode(stream));
    }
    XdrLedgerHeaderExt ext = XdrLedgerHeaderExt.decode(stream);
    return XdrLedgerHeader(
      ledgerVersion,
      previousLedgerHash,
      scpValue,
      txSetResultHash,
      bucketListHash,
      ledgerSeq,
      totalCoins,
      feePool,
      inflationSeq,
      idPool,
      baseFee,
      baseReserve,
      maxTxSetSize,
      skipList,
      ext,
    );
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrLedgerHeader.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrLedgerHeader fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrLedgerHeader.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrLedgerHeader');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrLedgerHeader.
  static XdrLedgerHeader fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrLedgerHeader'),
  );

  /// Returns the SEP-0051 rendering of this XdrLedgerHeader.
  Object? toXdrJsonValue() => <String, Object?>{
    'ledger_version': _ledgerVersion.toXdrJsonValue(),
    'previous_ledger_hash': _previousLedgerHash.toXdrJsonValue(),
    'scp_value': _scpValue.toXdrJsonValue(),
    'tx_set_result_hash': _txSetResultHash.toXdrJsonValue(),
    'bucket_list_hash': _bucketListHash.toXdrJsonValue(),
    'ledger_seq': _ledgerSeq.toXdrJsonValue(),
    'total_coins': _totalCoins.toXdrJsonValue(),
    'fee_pool': _feePool.toXdrJsonValue(),
    'inflation_seq': _inflationSeq.toXdrJsonValue(),
    'id_pool': _idPool.toXdrJsonValue(),
    'base_fee': _baseFee.toXdrJsonValue(),
    'base_reserve': _baseReserve.toXdrJsonValue(),
    'max_tx_set_size': _maxTxSetSize.toXdrJsonValue(),
    'skip_list': XdrJsonHelper.array<XdrHash>(
      _skipList,
      (XdrHash v) => v.toXdrJsonValue(),
      type: 'XdrLedgerHeader',
      key: 'skip_list',
    ),
    'ext': _ext.toXdrJsonValue(),
  };

  /// Reads a XdrLedgerHeader from its SEP-0051 rendering.
  static XdrLedgerHeader fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrLedgerHeader',
      allowedKeys: const <String>{
        'ledger_version',
        'previous_ledger_hash',
        'scp_value',
        'tx_set_result_hash',
        'bucket_list_hash',
        'ledger_seq',
        'total_coins',
        'fee_pool',
        'inflation_seq',
        'id_pool',
        'base_fee',
        'base_reserve',
        'max_tx_set_size',
        'skip_list',
        'ext',
      },
    );
    final Object? jsonLedgerVersion = XdrJsonHelper.readField(
      object,
      'ledger_version',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonPreviousLedgerHash = XdrJsonHelper.readField(
      object,
      'previous_ledger_hash',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonScpValue = XdrJsonHelper.readField(
      object,
      'scp_value',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonTxSetResultHash = XdrJsonHelper.readField(
      object,
      'tx_set_result_hash',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonBucketListHash = XdrJsonHelper.readField(
      object,
      'bucket_list_hash',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonLedgerSeq = XdrJsonHelper.readField(
      object,
      'ledger_seq',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonTotalCoins = XdrJsonHelper.readField(
      object,
      'total_coins',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonFeePool = XdrJsonHelper.readField(
      object,
      'fee_pool',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonInflationSeq = XdrJsonHelper.readField(
      object,
      'inflation_seq',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonIdPool = XdrJsonHelper.readField(
      object,
      'id_pool',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonBaseFee = XdrJsonHelper.readField(
      object,
      'base_fee',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonBaseReserve = XdrJsonHelper.readField(
      object,
      'base_reserve',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonMaxTxSetSize = XdrJsonHelper.readField(
      object,
      'max_tx_set_size',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonSkipList = XdrJsonHelper.readField(
      object,
      'skip_list',
      type: 'XdrLedgerHeader',
    );
    final Object? jsonExt = XdrJsonHelper.readField(
      object,
      'ext',
      type: 'XdrLedgerHeader',
    );
    return XdrLedgerHeader(
      XdrUint32.fromXdrJsonValue(jsonLedgerVersion),
      XdrHash.fromXdrJsonValue(jsonPreviousLedgerHash),
      XdrStellarValue.fromXdrJsonValue(jsonScpValue),
      XdrHash.fromXdrJsonValue(jsonTxSetResultHash),
      XdrHash.fromXdrJsonValue(jsonBucketListHash),
      XdrUint32.fromXdrJsonValue(jsonLedgerSeq),
      XdrInt64.fromXdrJsonValue(jsonTotalCoins),
      XdrInt64.fromXdrJsonValue(jsonFeePool),
      XdrUint32.fromXdrJsonValue(jsonInflationSeq),
      XdrUint64.fromXdrJsonValue(jsonIdPool),
      XdrUint32.fromXdrJsonValue(jsonBaseFee),
      XdrUint32.fromXdrJsonValue(jsonBaseReserve),
      XdrUint32.fromXdrJsonValue(jsonMaxTxSetSize),
      XdrJsonHelper.readArray(
        jsonSkipList,
        type: 'XdrLedgerHeader',
        key: 'skip_list',
        fixedLength: 4,
      ).map<XdrHash>((Object? e) => XdrHash.fromXdrJsonValue(e)).toList(),
      XdrLedgerHeaderExt.fromXdrJsonValue(jsonExt),
    );
  }
}
