// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_ledger_header_extension_v1_ext.dart';
import 'xdr_uint32.dart';

class XdrLedgerHeaderExtensionV1 {
  XdrUint32 _flags;
  XdrUint32 get flags => this._flags;
  set flags(XdrUint32 value) => this._flags = value;

  XdrLedgerHeaderExtensionV1Ext _ext;
  XdrLedgerHeaderExtensionV1Ext get ext => this._ext;
  set ext(XdrLedgerHeaderExtensionV1Ext value) => this._ext = value;

  XdrLedgerHeaderExtensionV1(this._flags, this._ext);

  static void encode(
    XdrDataOutputStream stream,
    XdrLedgerHeaderExtensionV1 encodedLedgerHeaderExtensionV1,
  ) {
    XdrUint32.encode(stream, encodedLedgerHeaderExtensionV1.flags);
    XdrLedgerHeaderExtensionV1Ext.encode(
      stream,
      encodedLedgerHeaderExtensionV1.ext,
    );
  }

  static XdrLedgerHeaderExtensionV1 decode(XdrDataInputStream stream) {
    XdrUint32 flags = XdrUint32.decode(stream);
    XdrLedgerHeaderExtensionV1Ext ext = XdrLedgerHeaderExtensionV1Ext.decode(
      stream,
    );
    return XdrLedgerHeaderExtensionV1(flags, ext);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrLedgerHeaderExtensionV1.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrLedgerHeaderExtensionV1 fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrLedgerHeaderExtensionV1.decode(XdrDataInputStream(bytes));
  }
}
