// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_scp_envelope.dart';
import 'xdr_uint32.dart';

class XdrLedgerSCPMessages {

  XdrUint32 _ledgerSeq;
  XdrUint32 get ledgerSeq => this._ledgerSeq;
  set ledgerSeq(XdrUint32 value) => this._ledgerSeq = value;

  List<XdrSCPEnvelope> _messages;
  List<XdrSCPEnvelope> get messages => this._messages;
  set messages(List<XdrSCPEnvelope> value) => this._messages = value;

  XdrLedgerSCPMessages(this._ledgerSeq, this._messages);

  static void encode(XdrDataOutputStream stream, XdrLedgerSCPMessages encodedLedgerSCPMessages) {
    XdrUint32.encode(stream, encodedLedgerSCPMessages.ledgerSeq);
    int messagessize = encodedLedgerSCPMessages.messages.length;
    stream.writeInt(messagessize);
    for (int i = 0; i < messagessize; i++) {
      XdrSCPEnvelope.encode(stream, encodedLedgerSCPMessages.messages[i]);
    }
  }

  static XdrLedgerSCPMessages decode(XdrDataInputStream stream) {
    XdrUint32 ledgerSeq = XdrUint32.decode(stream);
    int messagessize = stream.readInt();
    List<XdrSCPEnvelope> messages = List<XdrSCPEnvelope>.empty(growable: true);
    for (int i = 0; i < messagessize; i++) {
      messages.add(XdrSCPEnvelope.decode(stream));
    }
    return XdrLedgerSCPMessages(ledgerSeq, messages);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrLedgerSCPMessages.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrLedgerSCPMessages fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrLedgerSCPMessages.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _ledgerSeq.toTxRep('$prefix.ledgerSeq', lines);
    lines.add('$prefix.messages.len: ${_messages.length}');
    for (int i = 0; i < _messages.length; i++) {
      _messages[i].toTxRep('$prefix.messages[$i]', lines);
    }
  }

  static XdrLedgerSCPMessages fromTxRep(Map<String, String> map, String prefix) {
    XdrUint32 ledgerSeq = XdrUint32.fromTxRep(map, '$prefix.ledgerSeq');
    int messagesLen = TxRepHelper.parseInt(TxRepHelper.getValue(map, '$prefix.messages.len') ?? '0');
    List<XdrSCPEnvelope> messages = [];
    for (int i = 0; i < messagesLen; i++) {
      messages.add(XdrSCPEnvelope.fromTxRep(map, '$prefix.messages[$i]'));
    }
    return XdrLedgerSCPMessages(ledgerSeq, messages);
  }
}
