// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_sc_meta_kind.dart';
import 'xdr_sc_meta_v0.dart';

class XdrSCMetaEntry {
  XdrSCMetaKind _kind;

  XdrSCMetaKind get discriminant => this._kind;

  set discriminant(XdrSCMetaKind value) => this._kind = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrSCMetaKind get kind => this._kind;
  set kind(XdrSCMetaKind value) => this._kind = value;

  XdrSCMetaV0? _v0;

  XdrSCMetaV0? get v0 => this._v0;

  XdrSCMetaEntry(this._kind);

  set v0(XdrSCMetaV0? value) => this._v0 = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrSCMetaEntry encodedSCMetaEntry,
  ) {
    stream.writeInt(encodedSCMetaEntry.discriminant.value);
    switch (encodedSCMetaEntry.discriminant) {
      case XdrSCMetaKind.SC_META_V0:
        XdrSCMetaV0.encode(stream, encodedSCMetaEntry._v0!);
        break;
      default:
        break;
    }
  }

  static XdrSCMetaEntry decode(XdrDataInputStream stream) {
    XdrSCMetaEntry decodedSCMetaEntry = XdrSCMetaEntry(
      XdrSCMetaKind.decode(stream),
    );
    switch (decodedSCMetaEntry.discriminant) {
      case XdrSCMetaKind.SC_META_V0:
        decodedSCMetaEntry._v0 = XdrSCMetaV0.decode(stream);
        break;
      default:
        break;
    }
    return decodedSCMetaEntry;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCMetaEntry.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCMetaEntry fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCMetaEntry.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.kind: ${discriminant.enumName()}');
    switch (discriminant) {
      case XdrSCMetaKind.SC_META_V0:
        _v0!.toTxRep('$prefix.v0', lines);
        break;
      default:
        break;
    }
  }

  static XdrSCMetaEntry fromTxRep(Map<String, String> map, String prefix) {
    XdrSCMetaKind disc = XdrSCMetaKind.fromTxRepName(
      TxRepHelper.getValue(map, '$prefix.kind') ?? '',
    );
    XdrSCMetaEntry result = XdrSCMetaEntry(disc);
    switch (result.discriminant) {
      case XdrSCMetaKind.SC_META_V0:
        result._v0 = XdrSCMetaV0.fromTxRep(map, '$prefix.v0');
        break;
      default:
        break;
    }
    return result;
  }
}
