// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrSignature {
  XdrSignature(this._signature);

  Uint8List _signature;
  Uint8List get signature => this._signature;
  set signature(Uint8List value) => this._signature = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrSignature encodedSignature,
  ) {
    int signatureSize = encodedSignature.signature.length;
    stream.writeInt(signatureSize);
    stream.write(encodedSignature.signature);
  }

  static XdrSignature decode(XdrDataInputStream stream) {
    int signatureSize = stream.readInt();
    return XdrSignature(stream.readBytes(signatureSize));
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSignature.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSignature fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSignature.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix: ${TxRepHelper.bytesToHex(_signature)}');
  }

  static XdrSignature fromTxRep(Map<String, String> map, String prefix) {
    String? raw = TxRepHelper.getValue(map, prefix);
    if (raw == null) throw Exception('missing $prefix');
    return XdrSignature(TxRepHelper.hexToBytes(raw));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrSignature');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrSignature.
  static XdrSignature fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrSignature'),
  );

  /// Returns the SEP-0051 rendering of the wrapped value.
  Object? toXdrJsonValue() =>
      XdrJsonHelper.hex(_signature, type: 'XdrSignature', maxLength: 64);

  /// Reads a XdrSignature from the SEP-0051 rendering of its value.
  static XdrSignature fromXdrJsonValue(Object? value) => XdrSignature(
    XdrJsonHelper.readHex(value, type: 'XdrSignature', maxLength: 64),
  );
}
