// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';

class XdrClaimAtomType {
  final _value;
  const XdrClaimAtomType._internal(this._value);
  toString() => 'ClaimAtomType.$_value';
  XdrClaimAtomType(this._value);
  get value => this._value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XdrClaimAtomType && _value == other._value;

  @override
  int get hashCode => _value.hashCode;

  static const CLAIM_ATOM_TYPE_V0 = const XdrClaimAtomType._internal(0);
  static const CLAIM_ATOM_TYPE_ORDER_BOOK = const XdrClaimAtomType._internal(1);
  static const CLAIM_ATOM_TYPE_LIQUIDITY_POOL =
      const XdrClaimAtomType._internal(2);

  static XdrClaimAtomType decode(XdrDataInputStream stream) {
    int value = stream.readInt();
    switch (value) {
      case 0:
        return CLAIM_ATOM_TYPE_V0;
      case 1:
        return CLAIM_ATOM_TYPE_ORDER_BOOK;
      case 2:
        return CLAIM_ATOM_TYPE_LIQUIDITY_POOL;
      default:
        throw Exception("Unknown enum value: $value");
    }
  }

  static void encode(XdrDataOutputStream stream, XdrClaimAtomType value) {
    stream.writeInt(value.value);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrClaimAtomType.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrClaimAtomType fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrClaimAtomType.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix: ${enumName()}');
  }

  String enumName() {
    switch (_value) {
      case 0:
        return 'CLAIM_ATOM_TYPE_V0';
      case 1:
        return 'CLAIM_ATOM_TYPE_ORDER_BOOK';
      case 2:
        return 'CLAIM_ATOM_TYPE_LIQUIDITY_POOL';
      default:
        return 'XdrClaimAtomType#$_value';
    }
  }

  static XdrClaimAtomType fromTxRep(Map<String, String> map, String prefix) {
    String? raw = TxRepHelper.getValue(map, prefix);
    if (raw == null) throw Exception('missing $prefix');
    return fromTxRepName(raw);
  }

  static XdrClaimAtomType fromTxRepName(String name) {
    switch (name) {
      case 'CLAIM_ATOM_TYPE_V0':
        return CLAIM_ATOM_TYPE_V0;
      case 'CLAIM_ATOM_TYPE_ORDER_BOOK':
        return CLAIM_ATOM_TYPE_ORDER_BOOK;
      case 'CLAIM_ATOM_TYPE_LIQUIDITY_POOL':
        return CLAIM_ATOM_TYPE_LIQUIDITY_POOL;
      default:
        if (name.startsWith('XdrClaimAtomType#')) {
          int? val = int.tryParse(name.substring('XdrClaimAtomType#'.length));
          if (val != null) return XdrClaimAtomType._internal(val);
        }
        throw Exception('Unknown enum value: $name');
    }
  }
}
