// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_uint32.dart';

class XdrSendMoreExtended {

  XdrUint32 _numMessages;
  XdrUint32 get numMessages => this._numMessages;
  set numMessages(XdrUint32 value) => this._numMessages = value;

  XdrUint32 _numBytes;
  XdrUint32 get numBytes => this._numBytes;
  set numBytes(XdrUint32 value) => this._numBytes = value;

  XdrSendMoreExtended(this._numMessages, this._numBytes);

  static void encode(XdrDataOutputStream stream, XdrSendMoreExtended encodedSendMoreExtended) {
    XdrUint32.encode(stream, encodedSendMoreExtended.numMessages);
    XdrUint32.encode(stream, encodedSendMoreExtended.numBytes);
  }

  static XdrSendMoreExtended decode(XdrDataInputStream stream) {
    XdrUint32 numMessages = XdrUint32.decode(stream);
    XdrUint32 numBytes = XdrUint32.decode(stream);
    return XdrSendMoreExtended(numMessages, numBytes);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSendMoreExtended.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSendMoreExtended fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSendMoreExtended.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _numMessages.toTxRep('$prefix.numMessages', lines);
    _numBytes.toTxRep('$prefix.numBytes', lines);
  }

  static XdrSendMoreExtended fromTxRep(Map<String, String> map, String prefix) {
    XdrUint32 numMessages = XdrUint32.fromTxRep(map, '$prefix.numMessages');
    XdrUint32 numBytes = XdrUint32.fromTxRep(map, '$prefix.numBytes');
    return XdrSendMoreExtended(numMessages, numBytes);
  }
}
