// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_bucket_metadata_ext.dart';
import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_uint32.dart';

class XdrBucketMetadata {
  XdrUint32 _ledgerVersion;
  XdrUint32 get ledgerVersion => this._ledgerVersion;
  set ledgerVersion(XdrUint32 value) => this._ledgerVersion = value;

  XdrBucketMetadataExt _ext;
  XdrBucketMetadataExt get ext => this._ext;
  set ext(XdrBucketMetadataExt value) => this._ext = value;

  XdrBucketMetadata(this._ledgerVersion, this._ext);

  static void encode(
    XdrDataOutputStream stream,
    XdrBucketMetadata encodedBucketMetadata,
  ) {
    XdrUint32.encode(stream, encodedBucketMetadata.ledgerVersion);
    XdrBucketMetadataExt.encode(stream, encodedBucketMetadata.ext);
  }

  static XdrBucketMetadata decode(XdrDataInputStream stream) {
    XdrUint32 ledgerVersion = XdrUint32.decode(stream);
    XdrBucketMetadataExt ext = XdrBucketMetadataExt.decode(stream);
    return XdrBucketMetadata(ledgerVersion, ext);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrBucketMetadata.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrBucketMetadata fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrBucketMetadata.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrBucketMetadata');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrBucketMetadata.
  static XdrBucketMetadata fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrBucketMetadata'),
  );

  /// Returns the SEP-0051 rendering of this XdrBucketMetadata.
  Object? toXdrJsonValue() => <String, Object?>{
    'ledger_version': _ledgerVersion.toXdrJsonValue(),
    'ext': _ext.toXdrJsonValue(),
  };

  /// Reads a XdrBucketMetadata from its SEP-0051 rendering.
  static XdrBucketMetadata fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrBucketMetadata',
      allowedKeys: const <String>{'ledger_version', 'ext'},
    );
    final Object? jsonLedgerVersion = XdrJsonHelper.readField(
      object,
      'ledger_version',
      type: 'XdrBucketMetadata',
    );
    final Object? jsonExt = XdrJsonHelper.readField(
      object,
      'ext',
      type: 'XdrBucketMetadata',
    );
    return XdrBucketMetadata(
      XdrUint32.fromXdrJsonValue(jsonLedgerVersion),
      XdrBucketMetadataExt.fromXdrJsonValue(jsonExt),
    );
  }
}
