// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_uint64.dart';

class XdrUInt256PartsBase {
  XdrUint64 _hiHi;
  XdrUint64 get hiHi => this._hiHi;
  set hiHi(XdrUint64 value) => this._hiHi = value;

  XdrUint64 _hiLo;
  XdrUint64 get hiLo => this._hiLo;
  set hiLo(XdrUint64 value) => this._hiLo = value;

  XdrUint64 _loHi;
  XdrUint64 get loHi => this._loHi;
  set loHi(XdrUint64 value) => this._loHi = value;

  XdrUint64 _loLo;
  XdrUint64 get loLo => this._loLo;
  set loLo(XdrUint64 value) => this._loLo = value;

  XdrUInt256PartsBase(this._hiHi, this._hiLo, this._loHi, this._loLo);

  static void encode(
    XdrDataOutputStream stream,
    XdrUInt256PartsBase encodedUInt256Parts,
  ) {
    XdrUint64.encode(stream, encodedUInt256Parts.hiHi);
    XdrUint64.encode(stream, encodedUInt256Parts.hiLo);
    XdrUint64.encode(stream, encodedUInt256Parts.loHi);
    XdrUint64.encode(stream, encodedUInt256Parts.loLo);
  }

  static XdrUInt256PartsBase decode(XdrDataInputStream stream) {
    XdrUint64 hiHi = XdrUint64.decode(stream);
    XdrUint64 hiLo = XdrUint64.decode(stream);
    XdrUint64 loHi = XdrUint64.decode(stream);
    XdrUint64 loLo = XdrUint64.decode(stream);
    return XdrUInt256PartsBase(hiHi, hiLo, loHi, loLo);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrUInt256PartsBase.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrUInt256PartsBase fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrUInt256PartsBase.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _hiHi.toTxRep('$prefix.hi_hi', lines);
    _hiLo.toTxRep('$prefix.hi_lo', lines);
    _loHi.toTxRep('$prefix.lo_hi', lines);
    _loLo.toTxRep('$prefix.lo_lo', lines);
  }

  static XdrUInt256PartsBase fromTxRep(Map<String, String> map, String prefix) {
    XdrUint64 hiHi = XdrUint64.fromTxRep(map, '$prefix.hi_hi');
    XdrUint64 hiLo = XdrUint64.fromTxRep(map, '$prefix.hi_lo');
    XdrUint64 loHi = XdrUint64.fromTxRep(map, '$prefix.lo_hi');
    XdrUint64 loLo = XdrUint64.fromTxRep(map, '$prefix.lo_lo');
    return XdrUInt256PartsBase(hiHi, hiLo, loHi, loLo);
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrUInt256Parts');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrUInt256Parts.
  static XdrUInt256PartsBase fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrUInt256Parts'),
  );

  /// Returns the SEP-0051 rendering of this XdrUInt256Parts.
  Object? toXdrJsonValue() => XdrJsonHelper.partsToDecimalString(
    <BigInt>[_hiHi.uint64, _hiLo.uint64, _loHi.uint64, _loLo.uint64],
    signed: false,
    type: 'XdrUInt256Parts',
  );

  /// Reads a XdrUInt256Parts from its SEP-0051 rendering.
  static XdrUInt256PartsBase fromXdrJsonValue(Object? value) {
    final List<BigInt> limbs = XdrJsonHelper.decimalStringToParts(
      value,
      limbCount: 4,
      signed: false,
      type: 'XdrUInt256Parts',
    );
    return XdrUInt256PartsBase(
      XdrUint64(limbs[0]),
      XdrUint64(limbs[1]),
      XdrUint64(limbs[2]),
      XdrUint64(limbs[3]),
    );
  }
}
