// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_ledger_scp_messages.dart';
import 'xdr_scp_quorum_set.dart';

class XdrSCPHistoryEntryV0 {
  List<XdrSCPQuorumSet> _quorumSets;
  List<XdrSCPQuorumSet> get quorumSets => this._quorumSets;
  set quorumSets(List<XdrSCPQuorumSet> value) => this._quorumSets = value;

  XdrLedgerSCPMessages _ledgerMessages;
  XdrLedgerSCPMessages get ledgerMessages => this._ledgerMessages;
  set ledgerMessages(XdrLedgerSCPMessages value) =>
      this._ledgerMessages = value;

  XdrSCPHistoryEntryV0(this._quorumSets, this._ledgerMessages);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCPHistoryEntryV0 encodedSCPHistoryEntryV0,
  ) {
    int quorumSetssize = encodedSCPHistoryEntryV0.quorumSets.length;
    stream.writeInt(quorumSetssize);
    for (int i = 0; i < quorumSetssize; i++) {
      XdrSCPQuorumSet.encode(stream, encodedSCPHistoryEntryV0.quorumSets[i]);
    }
    XdrLedgerSCPMessages.encode(
      stream,
      encodedSCPHistoryEntryV0.ledgerMessages,
    );
  }

  static XdrSCPHistoryEntryV0 decode(XdrDataInputStream stream) {
    int quorumSetssize = stream.readInt();
    List<XdrSCPQuorumSet> quorumSets = List<XdrSCPQuorumSet>.empty(
      growable: true,
    );
    for (int i = 0; i < quorumSetssize; i++) {
      quorumSets.add(XdrSCPQuorumSet.decode(stream));
    }
    XdrLedgerSCPMessages ledgerMessages = XdrLedgerSCPMessages.decode(stream);
    return XdrSCPHistoryEntryV0(quorumSets, ledgerMessages);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCPHistoryEntryV0.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCPHistoryEntryV0 fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCPHistoryEntryV0.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.quorumSets.len: ${_quorumSets.length}');
    for (int i = 0; i < _quorumSets.length; i++) {
      _quorumSets[i].toTxRep('$prefix.quorumSets[$i]', lines);
    }
    _ledgerMessages.toTxRep('$prefix.ledgerMessages', lines);
  }

  static XdrSCPHistoryEntryV0 fromTxRep(
    Map<String, String> map,
    String prefix,
  ) {
    int quorumSetsLen = TxRepHelper.parseInt(
      TxRepHelper.getValue(map, '$prefix.quorumSets.len') ?? '0',
    );
    List<XdrSCPQuorumSet> quorumSets = [];
    for (int i = 0; i < quorumSetsLen; i++) {
      quorumSets.add(XdrSCPQuorumSet.fromTxRep(map, '$prefix.quorumSets[$i]'));
    }
    XdrLedgerSCPMessages ledgerMessages = XdrLedgerSCPMessages.fromTxRep(
      map,
      '$prefix.ledgerMessages',
    );
    return XdrSCPHistoryEntryV0(quorumSets, ledgerMessages);
  }
}
