// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_decorated_signature.dart';
import 'xdr_fee_bump_transaction.dart';
import 'xdr_json_helper.dart';

class XdrFeeBumpTransactionEnvelope {
  XdrFeeBumpTransaction _tx;
  XdrFeeBumpTransaction get tx => this._tx;
  set tx(XdrFeeBumpTransaction value) => this._tx = value;

  List<XdrDecoratedSignature> _signatures;
  List<XdrDecoratedSignature> get signatures => this._signatures;
  set signatures(List<XdrDecoratedSignature> value) => this._signatures = value;

  XdrFeeBumpTransactionEnvelope(this._tx, this._signatures);

  static void encode(
    XdrDataOutputStream stream,
    XdrFeeBumpTransactionEnvelope encodedFeeBumpTransactionEnvelope,
  ) {
    XdrFeeBumpTransaction.encode(stream, encodedFeeBumpTransactionEnvelope.tx);
    int signaturessize = encodedFeeBumpTransactionEnvelope.signatures.length;
    stream.writeInt(signaturessize);
    for (int i = 0; i < signaturessize; i++) {
      XdrDecoratedSignature.encode(
        stream,
        encodedFeeBumpTransactionEnvelope.signatures[i],
      );
    }
  }

  static XdrFeeBumpTransactionEnvelope decode(XdrDataInputStream stream) {
    XdrFeeBumpTransaction tx = XdrFeeBumpTransaction.decode(stream);
    int signaturessize = stream.readInt();
    List<XdrDecoratedSignature> signatures = List<XdrDecoratedSignature>.empty(
      growable: true,
    );
    for (int i = 0; i < signaturessize; i++) {
      signatures.add(XdrDecoratedSignature.decode(stream));
    }
    return XdrFeeBumpTransactionEnvelope(tx, signatures);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrFeeBumpTransactionEnvelope.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrFeeBumpTransactionEnvelope fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrFeeBumpTransactionEnvelope.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _tx.toTxRep('$prefix.tx', lines);
    lines.add('$prefix.signatures.len: ${_signatures.length}');
    for (int i = 0; i < _signatures.length; i++) {
      _signatures[i].toTxRep('$prefix.signatures[$i]', lines);
    }
  }

  static XdrFeeBumpTransactionEnvelope fromTxRep(
    Map<String, String> map,
    String prefix,
  ) {
    XdrFeeBumpTransaction tx = XdrFeeBumpTransaction.fromTxRep(
      map,
      '$prefix.tx',
    );
    int signaturesLen = TxRepHelper.parseInt(
      TxRepHelper.getValue(map, '$prefix.signatures.len') ?? '0',
    );
    List<XdrDecoratedSignature> signatures = [];
    for (int i = 0; i < signaturesLen; i++) {
      signatures.add(
        XdrDecoratedSignature.fromTxRep(map, '$prefix.signatures[$i]'),
      );
    }
    return XdrFeeBumpTransactionEnvelope(tx, signatures);
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrFeeBumpTransactionEnvelope',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrFeeBumpTransactionEnvelope.
  static XdrFeeBumpTransactionEnvelope fromXdrJson(String json) =>
      fromXdrJsonValue(
        XdrJsonHelper.decodeDocument(
          json,
          type: 'XdrFeeBumpTransactionEnvelope',
        ),
      );

  /// Returns the SEP-0051 rendering of this XdrFeeBumpTransactionEnvelope.
  Object? toXdrJsonValue() => <String, Object?>{
    'tx': _tx.toXdrJsonValue(),
    'signatures': XdrJsonHelper.array<XdrDecoratedSignature>(
      _signatures,
      (XdrDecoratedSignature v) => v.toXdrJsonValue(),
      type: 'XdrFeeBumpTransactionEnvelope',
      key: 'signatures',
      maxLength: 20,
    ),
  };

  /// Reads a XdrFeeBumpTransactionEnvelope from its SEP-0051 rendering.
  static XdrFeeBumpTransactionEnvelope fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrFeeBumpTransactionEnvelope',
      allowedKeys: const <String>{'tx', 'signatures'},
    );
    final Object? jsonTx = XdrJsonHelper.readField(
      object,
      'tx',
      type: 'XdrFeeBumpTransactionEnvelope',
    );
    final Object? jsonSignatures = XdrJsonHelper.readField(
      object,
      'signatures',
      type: 'XdrFeeBumpTransactionEnvelope',
    );
    return XdrFeeBumpTransactionEnvelope(
      XdrFeeBumpTransaction.fromXdrJsonValue(jsonTx),
      XdrJsonHelper.readArray(
            jsonSignatures,
            type: 'XdrFeeBumpTransactionEnvelope',
            key: 'signatures',
            maxLength: 20,
          )
          .map<XdrDecoratedSignature>(
            (Object? e) => XdrDecoratedSignature.fromXdrJsonValue(e),
          )
          .toList(),
    );
  }
}
