// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_memo.dart';
import 'xdr_muxed_account.dart';
import 'xdr_operation.dart';
import 'xdr_preconditions.dart';
import 'xdr_sequence_number.dart';
import 'xdr_transaction_ext.dart';
import 'xdr_uint32.dart';

class XdrTransaction {

  XdrMuxedAccount _sourceAccount;
  XdrMuxedAccount get sourceAccount => this._sourceAccount;
  set sourceAccount(XdrMuxedAccount value) => this._sourceAccount = value;

  XdrUint32 _fee;
  XdrUint32 get fee => this._fee;
  set fee(XdrUint32 value) => this._fee = value;

  XdrSequenceNumber _seqNum;
  XdrSequenceNumber get seqNum => this._seqNum;
  set seqNum(XdrSequenceNumber value) => this._seqNum = value;

  XdrPreconditions _cond;
  XdrPreconditions get cond => this._cond;
  set cond(XdrPreconditions value) => this._cond = value;

  XdrMemo _memo;
  XdrMemo get memo => this._memo;
  set memo(XdrMemo value) => this._memo = value;

  List<XdrOperation> _operations;
  List<XdrOperation> get operations => this._operations;
  set operations(List<XdrOperation> value) => this._operations = value;

  XdrTransactionExt _ext;
  XdrTransactionExt get ext => this._ext;
  set ext(XdrTransactionExt value) => this._ext = value;

  XdrTransaction(this._sourceAccount, this._fee, this._seqNum, this._cond, this._memo, this._operations, this._ext);

  static void encode(XdrDataOutputStream stream, XdrTransaction encodedTransaction) {
    XdrMuxedAccount.encode(stream, encodedTransaction.sourceAccount);
    XdrUint32.encode(stream, encodedTransaction.fee);
    XdrSequenceNumber.encode(stream, encodedTransaction.seqNum);
    XdrPreconditions.encode(stream, encodedTransaction.cond);
    XdrMemo.encode(stream, encodedTransaction.memo);
    int operationssize = encodedTransaction.operations.length;
    stream.writeInt(operationssize);
    for (int i = 0; i < operationssize; i++) {
      XdrOperation.encode(stream, encodedTransaction.operations[i]);
    }
    XdrTransactionExt.encode(stream, encodedTransaction.ext);
  }

  static XdrTransaction decode(XdrDataInputStream stream) {
    XdrMuxedAccount sourceAccount = XdrMuxedAccount.decode(stream);
    XdrUint32 fee = XdrUint32.decode(stream);
    XdrSequenceNumber seqNum = XdrSequenceNumber.decode(stream);
    XdrPreconditions cond = XdrPreconditions.decode(stream);
    XdrMemo memo = XdrMemo.decode(stream);
    int operationssize = stream.readInt();
    List<XdrOperation> operations = List<XdrOperation>.empty(growable: true);
    for (int i = 0; i < operationssize; i++) {
      operations.add(XdrOperation.decode(stream));
    }
    XdrTransactionExt ext = XdrTransactionExt.decode(stream);
    return XdrTransaction(sourceAccount, fee, seqNum, cond, memo, operations, ext);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrTransaction.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrTransaction fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrTransaction.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.sourceAccount: ${TxRepHelper.formatMuxedAccount(_sourceAccount)}');
    _fee.toTxRep('$prefix.fee', lines);
    _seqNum.toTxRep('$prefix.seqNum', lines);
    _cond.toTxRep('$prefix.cond', lines);
    _memo.toTxRep('$prefix.memo', lines);
    lines.add('$prefix.operations.len: ${_operations.length}');
    for (int i = 0; i < _operations.length; i++) {
      _operations[i].toTxRep('$prefix.operations[$i]', lines);
    }
    _ext.toTxRep('$prefix.ext', lines);
  }

  static XdrTransaction fromTxRep(Map<String, String> map, String prefix) {
    XdrMuxedAccount sourceAccount = TxRepHelper.parseMuxedAccount(TxRepHelper.getValue(map, '$prefix.sourceAccount') ?? '');
    XdrUint32 fee = XdrUint32.fromTxRep(map, '$prefix.fee');
    XdrSequenceNumber seqNum = XdrSequenceNumber.fromTxRep(map, '$prefix.seqNum');
    XdrPreconditions cond = XdrPreconditions.fromTxRep(map, '$prefix.cond');
    XdrMemo memo = XdrMemo.fromTxRep(map, '$prefix.memo');
    int operationsLen = TxRepHelper.parseInt(TxRepHelper.getValue(map, '$prefix.operations.len') ?? '0');
    List<XdrOperation> operations = [];
    for (int i = 0; i < operationsLen; i++) {
      operations.add(XdrOperation.fromTxRep(map, '$prefix.operations[$i]'));
    }
    XdrTransactionExt ext = XdrTransactionExt.fromTxRep(map, '$prefix.ext');
    return XdrTransaction(sourceAccount, fee, seqNum, cond, memo, operations, ext);
  }
}
