// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_ledger_close_meta_ext_v1.dart';

class XdrLedgerCloseMetaExt {
  int _v;

  int get discriminant => this._v;
  set discriminant(int value) => this._v = value;

  /// Alias for [discriminant], the original XDR field name.
  int get v => this._v;
  set v(int value) => this._v = value;

  XdrLedgerCloseMetaExtV1? _v1;

  XdrLedgerCloseMetaExtV1? get v1 => this._v1;

  XdrLedgerCloseMetaExt(this._v);

  set v1(XdrLedgerCloseMetaExtV1? value) => this._v1 = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrLedgerCloseMetaExt encodedLedgerCloseMetaExt,
  ) {
    stream.writeInt(encodedLedgerCloseMetaExt.discriminant);
    switch (encodedLedgerCloseMetaExt.discriminant) {
      case 0:
        break;
      case 1:
        XdrLedgerCloseMetaExtV1.encode(stream, encodedLedgerCloseMetaExt._v1!);
        break;
      default:
        break;
    }
  }

  static XdrLedgerCloseMetaExt decode(XdrDataInputStream stream) {
    int discriminant = stream.readInt();
    XdrLedgerCloseMetaExt decodedLedgerCloseMetaExt = XdrLedgerCloseMetaExt(
      discriminant,
    );
    switch (decodedLedgerCloseMetaExt.discriminant) {
      case 0:
        break;
      case 1:
        decodedLedgerCloseMetaExt._v1 = XdrLedgerCloseMetaExtV1.decode(stream);
        break;
      default:
        break;
    }
    return decodedLedgerCloseMetaExt;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrLedgerCloseMetaExt.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrLedgerCloseMetaExt fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrLedgerCloseMetaExt.decode(XdrDataInputStream(bytes));
  }
}
