// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_account_id.dart';
import 'xdr_asset.dart';
import 'xdr_data_io.dart';
import 'xdr_int64.dart';
import 'xdr_json_helper.dart';
import 'xdr_uint64.dart';

class XdrClaimOfferAtom {
  XdrAccountID _sellerID;
  XdrAccountID get sellerID => this._sellerID;
  set sellerID(XdrAccountID value) => this._sellerID = value;

  XdrUint64 _offerID;
  XdrUint64 get offerID => this._offerID;
  set offerID(XdrUint64 value) => this._offerID = value;

  XdrAsset _assetSold;
  XdrAsset get assetSold => this._assetSold;
  set assetSold(XdrAsset value) => this._assetSold = value;

  XdrInt64 _amountSold;
  XdrInt64 get amountSold => this._amountSold;
  set amountSold(XdrInt64 value) => this._amountSold = value;

  XdrAsset _assetBought;
  XdrAsset get assetBought => this._assetBought;
  set assetBought(XdrAsset value) => this._assetBought = value;

  XdrInt64 _amountBought;
  XdrInt64 get amountBought => this._amountBought;
  set amountBought(XdrInt64 value) => this._amountBought = value;

  XdrClaimOfferAtom(
    this._sellerID,
    this._offerID,
    this._assetSold,
    this._amountSold,
    this._assetBought,
    this._amountBought,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrClaimOfferAtom encodedClaimOfferAtom,
  ) {
    XdrAccountID.encode(stream, encodedClaimOfferAtom.sellerID);
    XdrUint64.encode(stream, encodedClaimOfferAtom.offerID);
    XdrAsset.encode(stream, encodedClaimOfferAtom.assetSold);
    XdrInt64.encode(stream, encodedClaimOfferAtom.amountSold);
    XdrAsset.encode(stream, encodedClaimOfferAtom.assetBought);
    XdrInt64.encode(stream, encodedClaimOfferAtom.amountBought);
  }

  static XdrClaimOfferAtom decode(XdrDataInputStream stream) {
    XdrAccountID sellerID = XdrAccountID.decode(stream);
    XdrUint64 offerID = XdrUint64.decode(stream);
    XdrAsset assetSold = XdrAsset.decode(stream);
    XdrInt64 amountSold = XdrInt64.decode(stream);
    XdrAsset assetBought = XdrAsset.decode(stream);
    XdrInt64 amountBought = XdrInt64.decode(stream);
    return XdrClaimOfferAtom(
      sellerID,
      offerID,
      assetSold,
      amountSold,
      assetBought,
      amountBought,
    );
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrClaimOfferAtom.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrClaimOfferAtom fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrClaimOfferAtom.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrClaimOfferAtom');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrClaimOfferAtom.
  static XdrClaimOfferAtom fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrClaimOfferAtom'),
  );

  /// Returns the SEP-0051 rendering of this XdrClaimOfferAtom.
  Object? toXdrJsonValue() => <String, Object?>{
    'seller_id': _sellerID.toXdrJsonValue(),
    'offer_id': _offerID.toXdrJsonValue(),
    'asset_sold': _assetSold.toXdrJsonValue(),
    'amount_sold': _amountSold.toXdrJsonValue(),
    'asset_bought': _assetBought.toXdrJsonValue(),
    'amount_bought': _amountBought.toXdrJsonValue(),
  };

  /// Reads a XdrClaimOfferAtom from its SEP-0051 rendering.
  static XdrClaimOfferAtom fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrClaimOfferAtom',
      allowedKeys: const <String>{
        'seller_id',
        'offer_id',
        'asset_sold',
        'amount_sold',
        'asset_bought',
        'amount_bought',
      },
    );
    final Object? jsonSellerID = XdrJsonHelper.readField(
      object,
      'seller_id',
      type: 'XdrClaimOfferAtom',
    );
    final Object? jsonOfferID = XdrJsonHelper.readField(
      object,
      'offer_id',
      type: 'XdrClaimOfferAtom',
    );
    final Object? jsonAssetSold = XdrJsonHelper.readField(
      object,
      'asset_sold',
      type: 'XdrClaimOfferAtom',
    );
    final Object? jsonAmountSold = XdrJsonHelper.readField(
      object,
      'amount_sold',
      type: 'XdrClaimOfferAtom',
    );
    final Object? jsonAssetBought = XdrJsonHelper.readField(
      object,
      'asset_bought',
      type: 'XdrClaimOfferAtom',
    );
    final Object? jsonAmountBought = XdrJsonHelper.readField(
      object,
      'amount_bought',
      type: 'XdrClaimOfferAtom',
    );
    return XdrClaimOfferAtom(
      XdrAccountID.fromXdrJsonValue(jsonSellerID),
      XdrUint64.fromXdrJsonValue(jsonOfferID),
      XdrAsset.fromXdrJsonValue(jsonAssetSold),
      XdrInt64.fromXdrJsonValue(jsonAmountSold),
      XdrAsset.fromXdrJsonValue(jsonAssetBought),
      XdrInt64.fromXdrJsonValue(jsonAmountBought),
    );
  }
}
