// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_data_value.dart';
import 'xdr_string64.dart';

class XdrManageDataOp {
  XdrString64 _dataName;
  XdrString64 get dataName => this._dataName;
  set dataName(XdrString64 value) => this._dataName = value;

  XdrDataValue? _dataValue;
  XdrDataValue? get dataValue => this._dataValue;
  set dataValue(XdrDataValue? value) => this._dataValue = value;

  XdrManageDataOp(this._dataName, this._dataValue);

  static void encode(
    XdrDataOutputStream stream,
    XdrManageDataOp encodedManageDataOp,
  ) {
    XdrString64.encode(stream, encodedManageDataOp.dataName);
    if (encodedManageDataOp.dataValue != null) {
      stream.writeInt(1);
      XdrDataValue.encode(stream, encodedManageDataOp.dataValue!);
    } else {
      stream.writeInt(0);
    }
  }

  static XdrManageDataOp decode(XdrDataInputStream stream) {
    XdrString64 dataName = XdrString64.decode(stream);
    XdrDataValue? dataValue;
    int dataValuePresent = stream.readInt();
    if (dataValuePresent != 0) {
      dataValue = XdrDataValue.decode(stream);
    }
    return XdrManageDataOp(dataName, dataValue);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrManageDataOp.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrManageDataOp fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrManageDataOp.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _dataName.toTxRep('$prefix.dataName', lines);
    if (_dataValue != null) {
      lines.add('$prefix.dataValue._present: true');
      _dataValue!.toTxRep('$prefix.dataValue', lines);
    } else {
      lines.add('$prefix.dataValue._present: false');
    }
  }

  static XdrManageDataOp fromTxRep(Map<String, String> map, String prefix) {
    XdrString64 dataName = XdrString64.fromTxRep(map, '$prefix.dataName');
    XdrDataValue? dataValue;
    String? dataValuePresent = TxRepHelper.getValue(
      map,
      '$prefix.dataValue._present',
    );
    if (dataValuePresent != null && dataValuePresent == 'true') {
      dataValue = XdrDataValue.fromTxRep(map, '$prefix.dataValue');
    }
    return XdrManageDataOp(dataName, dataValue);
  }
}
