// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrHotArchiveBucketEntryType {
  final _value;
  const XdrHotArchiveBucketEntryType._internal(this._value);
  toString() => 'HotArchiveBucketEntryType.$_value';
  XdrHotArchiveBucketEntryType(this._value);
  get value => this._value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XdrHotArchiveBucketEntryType && _value == other._value;

  @override
  int get hashCode => _value.hashCode;

  static const HOT_ARCHIVE_METAENTRY =
      const XdrHotArchiveBucketEntryType._internal(-1);
  static const HOT_ARCHIVE_ARCHIVED =
      const XdrHotArchiveBucketEntryType._internal(0);
  static const HOT_ARCHIVE_LIVE = const XdrHotArchiveBucketEntryType._internal(
    1,
  );

  static XdrHotArchiveBucketEntryType decode(XdrDataInputStream stream) {
    int value = stream.readInt();
    switch (value) {
      case -1:
        return HOT_ARCHIVE_METAENTRY;
      case 0:
        return HOT_ARCHIVE_ARCHIVED;
      case 1:
        return HOT_ARCHIVE_LIVE;
      default:
        throw Exception("Unknown enum value: $value");
    }
  }

  static void encode(
    XdrDataOutputStream stream,
    XdrHotArchiveBucketEntryType value,
  ) {
    stream.writeInt(value.value);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrHotArchiveBucketEntryType.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrHotArchiveBucketEntryType fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrHotArchiveBucketEntryType.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrHotArchiveBucketEntryType',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrHotArchiveBucketEntryType.
  static XdrHotArchiveBucketEntryType fromXdrJson(String json) =>
      fromXdrJsonValue(
        XdrJsonHelper.decodeDocument(
          json,
          type: 'XdrHotArchiveBucketEntryType',
        ),
      );

  /// Returns this member's SEP-0051 name.
  Object? toXdrJsonValue() {
    switch (_value) {
      case -1:
        return 'metaentry';
      case 0:
        return 'archived';
      case 1:
        return 'live';
      default:
        XdrJsonHelper.fail(
          'XdrHotArchiveBucketEntryType',
          'holds the unknown value $_value',
        );
    }
  }

  /// Reads a XdrHotArchiveBucketEntryType from its SEP-0051 name.
  static XdrHotArchiveBucketEntryType fromXdrJsonValue(Object? value) {
    if (value is String) {
      switch (value) {
        case 'metaentry':
          return XdrHotArchiveBucketEntryType.HOT_ARCHIVE_METAENTRY;
        case 'archived':
          return XdrHotArchiveBucketEntryType.HOT_ARCHIVE_ARCHIVED;
        case 'live':
          return XdrHotArchiveBucketEntryType.HOT_ARCHIVE_LIVE;
      }
    }
    XdrJsonHelper.fail(
      'XdrHotArchiveBucketEntryType',
      'expects one of its member names but found ${XdrJsonHelper.preview(value)}',
    );
  }
}
