// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_uint32.dart';
import 'xdr_value.dart';

class XdrSCPBallot {
  XdrUint32 _counter;
  XdrUint32 get counter => this._counter;
  set counter(XdrUint32 value) => this._counter = value;

  XdrValue _value;
  XdrValue get value => this._value;
  set value(XdrValue value) => this._value = value;

  XdrSCPBallot(this._counter, this._value);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCPBallot encodedSCPBallot,
  ) {
    XdrUint32.encode(stream, encodedSCPBallot.counter);
    XdrValue.encode(stream, encodedSCPBallot.value);
  }

  static XdrSCPBallot decode(XdrDataInputStream stream) {
    XdrUint32 counter = XdrUint32.decode(stream);
    XdrValue value = XdrValue.decode(stream);
    return XdrSCPBallot(counter, value);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCPBallot.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCPBallot fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCPBallot.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _counter.toTxRep('$prefix.counter', lines);
    _value.toTxRep('$prefix.value', lines);
  }

  static XdrSCPBallot fromTxRep(Map<String, String> map, String prefix) {
    XdrUint32 counter = XdrUint32.fromTxRep(map, '$prefix.counter');
    XdrValue value = XdrValue.fromTxRep(map, '$prefix.value');
    return XdrSCPBallot(counter, value);
  }
}
