// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_sc_spec_type_def.dart';

class XdrSCSpecTypeOption {
  XdrSCSpecTypeDef _valueType;
  XdrSCSpecTypeDef get valueType => this._valueType;
  set valueType(XdrSCSpecTypeDef value) => this._valueType = value;

  XdrSCSpecTypeOption(this._valueType);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCSpecTypeOption encodedSCSpecTypeOption,
  ) {
    XdrSCSpecTypeDef.encode(stream, encodedSCSpecTypeOption.valueType);
  }

  static XdrSCSpecTypeOption decode(XdrDataInputStream stream) {
    XdrSCSpecTypeDef valueType = XdrSCSpecTypeDef.decode(stream);
    return XdrSCSpecTypeOption(valueType);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCSpecTypeOption.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCSpecTypeOption fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCSpecTypeOption.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrSCSpecTypeOption',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrSCSpecTypeOption.
  static XdrSCSpecTypeOption fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrSCSpecTypeOption'),
  );

  /// Returns the SEP-0051 rendering of this XdrSCSpecTypeOption.
  Object? toXdrJsonValue() => <String, Object?>{
    'value_type': _valueType.toXdrJsonValue(),
  };

  /// Reads a XdrSCSpecTypeOption from its SEP-0051 rendering.
  static XdrSCSpecTypeOption fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrSCSpecTypeOption',
      allowedKeys: const <String>{'value_type'},
    );
    final Object? jsonValueType = XdrJsonHelper.readField(
      object,
      'value_type',
      type: 'XdrSCSpecTypeOption',
    );
    return XdrSCSpecTypeOption(
      XdrSCSpecTypeDef.fromXdrJsonValue(jsonValueType),
    );
  }
}
