// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_node_id.dart';
import 'xdr_scp_statement_pledges.dart';
import 'xdr_uint64.dart';

class XdrSCPStatement {
  XdrNodeID _nodeID;
  XdrNodeID get nodeID => this._nodeID;
  set nodeID(XdrNodeID value) => this._nodeID = value;

  XdrUint64 _slotIndex;
  XdrUint64 get slotIndex => this._slotIndex;
  set slotIndex(XdrUint64 value) => this._slotIndex = value;

  XdrSCPStatementPledges _pledges;
  XdrSCPStatementPledges get pledges => this._pledges;
  set pledges(XdrSCPStatementPledges value) => this._pledges = value;

  XdrSCPStatement(this._nodeID, this._slotIndex, this._pledges);

  static void encode(
    XdrDataOutputStream stream,
    XdrSCPStatement encodedSCPStatement,
  ) {
    XdrNodeID.encode(stream, encodedSCPStatement.nodeID);
    XdrUint64.encode(stream, encodedSCPStatement.slotIndex);
    XdrSCPStatementPledges.encode(stream, encodedSCPStatement.pledges);
  }

  static XdrSCPStatement decode(XdrDataInputStream stream) {
    XdrNodeID nodeID = XdrNodeID.decode(stream);
    XdrUint64 slotIndex = XdrUint64.decode(stream);
    XdrSCPStatementPledges pledges = XdrSCPStatementPledges.decode(stream);
    return XdrSCPStatement(nodeID, slotIndex, pledges);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCPStatement.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCPStatement fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCPStatement.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _nodeID.toTxRep('$prefix.nodeID', lines);
    _slotIndex.toTxRep('$prefix.slotIndex', lines);
    _pledges.toTxRep('$prefix.pledges', lines);
  }

  static XdrSCPStatement fromTxRep(Map<String, String> map, String prefix) {
    XdrNodeID nodeID = XdrNodeID.fromTxRep(map, '$prefix.nodeID');
    XdrUint64 slotIndex = XdrUint64.fromTxRep(map, '$prefix.slotIndex');
    XdrSCPStatementPledges pledges = XdrSCPStatementPledges.fromTxRep(
      map,
      '$prefix.pledges',
    );
    return XdrSCPStatement(nodeID, slotIndex, pledges);
  }
}
