// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_peer_address_ip.dart';
import 'xdr_uint32.dart';

class XdrPeerAddress {
  XdrPeerAddressIp _ip;
  XdrPeerAddressIp get ip => this._ip;
  set ip(XdrPeerAddressIp value) => this._ip = value;

  XdrUint32 _port;
  XdrUint32 get port => this._port;
  set port(XdrUint32 value) => this._port = value;

  XdrUint32 _numFailures;
  XdrUint32 get numFailures => this._numFailures;
  set numFailures(XdrUint32 value) => this._numFailures = value;

  XdrPeerAddress(this._ip, this._port, this._numFailures);

  static void encode(
    XdrDataOutputStream stream,
    XdrPeerAddress encodedPeerAddress,
  ) {
    XdrPeerAddressIp.encode(stream, encodedPeerAddress.ip);
    XdrUint32.encode(stream, encodedPeerAddress.port);
    XdrUint32.encode(stream, encodedPeerAddress.numFailures);
  }

  static XdrPeerAddress decode(XdrDataInputStream stream) {
    XdrPeerAddressIp ip = XdrPeerAddressIp.decode(stream);
    XdrUint32 port = XdrUint32.decode(stream);
    XdrUint32 numFailures = XdrUint32.decode(stream);
    return XdrPeerAddress(ip, port, numFailures);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrPeerAddress.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrPeerAddress fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrPeerAddress.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrPeerAddress');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrPeerAddress.
  static XdrPeerAddress fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrPeerAddress'),
  );

  /// Returns the SEP-0051 rendering of this XdrPeerAddress.
  Object? toXdrJsonValue() => <String, Object?>{
    'ip': _ip.toXdrJsonValue(),
    'port': _port.toXdrJsonValue(),
    'num_failures': _numFailures.toXdrJsonValue(),
  };

  /// Reads a XdrPeerAddress from its SEP-0051 rendering.
  static XdrPeerAddress fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrPeerAddress',
      allowedKeys: const <String>{'ip', 'port', 'num_failures'},
    );
    final Object? jsonIp = XdrJsonHelper.readField(
      object,
      'ip',
      type: 'XdrPeerAddress',
    );
    final Object? jsonPort = XdrJsonHelper.readField(
      object,
      'port',
      type: 'XdrPeerAddress',
    );
    final Object? jsonNumFailures = XdrJsonHelper.readField(
      object,
      'num_failures',
      type: 'XdrPeerAddress',
    );
    return XdrPeerAddress(
      XdrPeerAddressIp.fromXdrJsonValue(jsonIp),
      XdrUint32.fromXdrJsonValue(jsonPort),
      XdrUint32.fromXdrJsonValue(jsonNumFailures),
    );
  }
}
