// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_public_key.dart';

class XdrNodeID {
  XdrNodeID(this._nodeID);

  XdrPublicKey _nodeID;
  XdrPublicKey get nodeID => this._nodeID;
  set nodeID(XdrPublicKey value) => this._nodeID = value;

  static void encode(XdrDataOutputStream stream, XdrNodeID encodedNodeID) {
    XdrPublicKey.encode(stream, encodedNodeID.nodeID);
  }

  static XdrNodeID decode(XdrDataInputStream stream) {
    return XdrNodeID(XdrPublicKey.decode(stream));
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrNodeID.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrNodeID fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrNodeID.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrNodeID');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrNodeID.
  static XdrNodeID fromXdrJson(String json) =>
      fromXdrJsonValue(XdrJsonHelper.decodeDocument(json, type: 'XdrNodeID'));

  /// Returns the SEP-0051 rendering of the wrapped value.
  Object? toXdrJsonValue() => _nodeID.toXdrJsonValue();

  /// Reads a XdrNodeID from the SEP-0051 rendering of its value.
  static XdrNodeID fromXdrJsonValue(Object? value) =>
      XdrNodeID(XdrPublicKey.fromXdrJsonValue(value));
}
