// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_contract_id_preimage.dart';
import 'xdr_data_io.dart';
import 'xdr_hash.dart';
import 'xdr_json_helper.dart';

class XdrHashIDPreimageContractID {
  XdrHash _networkID;
  XdrHash get networkID => this._networkID;
  set networkID(XdrHash value) => this._networkID = value;

  XdrContractIDPreimage _contractIDPreimage;
  XdrContractIDPreimage get contractIDPreimage => this._contractIDPreimage;
  set contractIDPreimage(XdrContractIDPreimage value) =>
      this._contractIDPreimage = value;

  XdrHashIDPreimageContractID(this._networkID, this._contractIDPreimage);

  static void encode(
    XdrDataOutputStream stream,
    XdrHashIDPreimageContractID encodedHashIDPreimageContractID,
  ) {
    XdrHash.encode(stream, encodedHashIDPreimageContractID.networkID);
    XdrContractIDPreimage.encode(
      stream,
      encodedHashIDPreimageContractID.contractIDPreimage,
    );
  }

  static XdrHashIDPreimageContractID decode(XdrDataInputStream stream) {
    XdrHash networkID = XdrHash.decode(stream);
    XdrContractIDPreimage contractIDPreimage = XdrContractIDPreimage.decode(
      stream,
    );
    return XdrHashIDPreimageContractID(networkID, contractIDPreimage);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrHashIDPreimageContractID.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrHashIDPreimageContractID fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrHashIDPreimageContractID.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrHashIDPreimageContractID',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrHashIDPreimageContractID.
  static XdrHashIDPreimageContractID fromXdrJson(String json) =>
      fromXdrJsonValue(
        XdrJsonHelper.decodeDocument(json, type: 'XdrHashIDPreimageContractID'),
      );

  /// Returns the SEP-0051 rendering of this XdrHashIDPreimageContractID.
  Object? toXdrJsonValue() => <String, Object?>{
    'network_id': _networkID.toXdrJsonValue(),
    'contract_id_preimage': _contractIDPreimage.toXdrJsonValue(),
  };

  /// Reads a XdrHashIDPreimageContractID from its SEP-0051 rendering.
  static XdrHashIDPreimageContractID fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrHashIDPreimageContractID',
      allowedKeys: const <String>{'network_id', 'contract_id_preimage'},
    );
    final Object? jsonNetworkID = XdrJsonHelper.readField(
      object,
      'network_id',
      type: 'XdrHashIDPreimageContractID',
    );
    final Object? jsonContractIDPreimage = XdrJsonHelper.readField(
      object,
      'contract_id_preimage',
      type: 'XdrHashIDPreimageContractID',
    );
    return XdrHashIDPreimageContractID(
      XdrHash.fromXdrJsonValue(jsonNetworkID),
      XdrContractIDPreimage.fromXdrJsonValue(jsonContractIDPreimage),
    );
  }
}
