// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrContractEventType {
  final _value;
  const XdrContractEventType._internal(this._value);
  toString() => 'ContractEventType.$_value';
  XdrContractEventType(this._value);
  get value => this._value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XdrContractEventType && _value == other._value;

  @override
  int get hashCode => _value.hashCode;

  static const SYSTEM = const XdrContractEventType._internal(0);
  static const CONTRACT = const XdrContractEventType._internal(1);
  static const DIAGNOSTIC = const XdrContractEventType._internal(2);

  static XdrContractEventType decode(XdrDataInputStream stream) {
    int value = stream.readInt();
    switch (value) {
      case 0:
        return SYSTEM;
      case 1:
        return CONTRACT;
      case 2:
        return DIAGNOSTIC;
      default:
        throw Exception("Unknown enum value: $value");
    }
  }

  static void encode(XdrDataOutputStream stream, XdrContractEventType value) {
    stream.writeInt(value.value);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrContractEventType.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrContractEventType fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrContractEventType.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrContractEventType',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrContractEventType.
  static XdrContractEventType fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrContractEventType'),
  );

  /// Returns this member's SEP-0051 name.
  Object? toXdrJsonValue() {
    switch (_value) {
      case 0:
        return 'system';
      case 1:
        return 'contract';
      case 2:
        return 'diagnostic';
      default:
        XdrJsonHelper.fail(
          'XdrContractEventType',
          'holds the unknown value $_value',
        );
    }
  }

  /// Reads a XdrContractEventType from its SEP-0051 name.
  static XdrContractEventType fromXdrJsonValue(Object? value) {
    if (value is String) {
      switch (value) {
        case 'system':
          return XdrContractEventType.SYSTEM;
        case 'contract':
          return XdrContractEventType.CONTRACT;
        case 'diagnostic':
          return XdrContractEventType.DIAGNOSTIC;
      }
    }
    XdrJsonHelper.fail(
      'XdrContractEventType',
      'expects one of its member names but found ${XdrJsonHelper.preview(value)}',
    );
  }
}
