// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_auth_cert.dart';
import 'xdr_data_io.dart';
import 'xdr_hash.dart';
import 'xdr_json_helper.dart';
import 'xdr_node_id.dart';
import 'xdr_uint256.dart';
import 'xdr_uint32.dart';

class XdrHello {
  XdrUint32 _ledgerVersion;
  XdrUint32 get ledgerVersion => this._ledgerVersion;
  set ledgerVersion(XdrUint32 value) => this._ledgerVersion = value;

  XdrUint32 _overlayVersion;
  XdrUint32 get overlayVersion => this._overlayVersion;
  set overlayVersion(XdrUint32 value) => this._overlayVersion = value;

  XdrUint32 _overlayMinVersion;
  XdrUint32 get overlayMinVersion => this._overlayMinVersion;
  set overlayMinVersion(XdrUint32 value) => this._overlayMinVersion = value;

  XdrHash _networkID;
  XdrHash get networkID => this._networkID;
  set networkID(XdrHash value) => this._networkID = value;

  String _versionStr;
  String get versionStr => this._versionStr;
  set versionStr(String value) => this._versionStr = value;

  int _listeningPort;
  int get listeningPort => this._listeningPort;
  set listeningPort(int value) => this._listeningPort = value;

  XdrNodeID _peerID;
  XdrNodeID get peerID => this._peerID;
  set peerID(XdrNodeID value) => this._peerID = value;

  XdrAuthCert _cert;
  XdrAuthCert get cert => this._cert;
  set cert(XdrAuthCert value) => this._cert = value;

  XdrUint256 _nonce;
  XdrUint256 get nonce => this._nonce;
  set nonce(XdrUint256 value) => this._nonce = value;

  XdrHello(
    this._ledgerVersion,
    this._overlayVersion,
    this._overlayMinVersion,
    this._networkID,
    this._versionStr,
    this._listeningPort,
    this._peerID,
    this._cert,
    this._nonce,
  );

  static void encode(XdrDataOutputStream stream, XdrHello encodedHello) {
    XdrUint32.encode(stream, encodedHello.ledgerVersion);
    XdrUint32.encode(stream, encodedHello.overlayVersion);
    XdrUint32.encode(stream, encodedHello.overlayMinVersion);
    XdrHash.encode(stream, encodedHello.networkID);
    stream.writeString(encodedHello.versionStr);
    stream.writeInt(encodedHello.listeningPort);
    XdrNodeID.encode(stream, encodedHello.peerID);
    XdrAuthCert.encode(stream, encodedHello.cert);
    XdrUint256.encode(stream, encodedHello.nonce);
  }

  static XdrHello decode(XdrDataInputStream stream) {
    XdrUint32 ledgerVersion = XdrUint32.decode(stream);
    XdrUint32 overlayVersion = XdrUint32.decode(stream);
    XdrUint32 overlayMinVersion = XdrUint32.decode(stream);
    XdrHash networkID = XdrHash.decode(stream);
    String versionStr = stream.readString();
    int listeningPort = stream.readInt();
    XdrNodeID peerID = XdrNodeID.decode(stream);
    XdrAuthCert cert = XdrAuthCert.decode(stream);
    XdrUint256 nonce = XdrUint256.decode(stream);
    return XdrHello(
      ledgerVersion,
      overlayVersion,
      overlayMinVersion,
      networkID,
      versionStr,
      listeningPort,
      peerID,
      cert,
      nonce,
    );
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrHello.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrHello fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrHello.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrHello');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrHello.
  static XdrHello fromXdrJson(String json) =>
      fromXdrJsonValue(XdrJsonHelper.decodeDocument(json, type: 'XdrHello'));

  /// Returns the SEP-0051 rendering of this XdrHello.
  Object? toXdrJsonValue() => <String, Object?>{
    'ledger_version': _ledgerVersion.toXdrJsonValue(),
    'overlay_version': _overlayVersion.toXdrJsonValue(),
    'overlay_min_version': _overlayMinVersion.toXdrJsonValue(),
    'network_id': _networkID.toXdrJsonValue(),
    'version_str': XdrJsonHelper.escapedString(
      _versionStr,
      type: 'XdrHello',
      key: 'version_str',
      maxBytes: 100,
    ),
    'listening_port': XdrJsonHelper.int32(
      _listeningPort,
      type: 'XdrHello',
      key: 'listening_port',
    ),
    'peer_id': _peerID.toXdrJsonValue(),
    'cert': _cert.toXdrJsonValue(),
    'nonce': _nonce.toXdrJsonValue(),
  };

  /// Reads a XdrHello from its SEP-0051 rendering.
  static XdrHello fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrHello',
      allowedKeys: const <String>{
        'ledger_version',
        'overlay_version',
        'overlay_min_version',
        'network_id',
        'version_str',
        'listening_port',
        'peer_id',
        'cert',
        'nonce',
      },
    );
    final Object? jsonLedgerVersion = XdrJsonHelper.readField(
      object,
      'ledger_version',
      type: 'XdrHello',
    );
    final Object? jsonOverlayVersion = XdrJsonHelper.readField(
      object,
      'overlay_version',
      type: 'XdrHello',
    );
    final Object? jsonOverlayMinVersion = XdrJsonHelper.readField(
      object,
      'overlay_min_version',
      type: 'XdrHello',
    );
    final Object? jsonNetworkID = XdrJsonHelper.readField(
      object,
      'network_id',
      type: 'XdrHello',
    );
    final Object? jsonVersionStr = XdrJsonHelper.readField(
      object,
      'version_str',
      type: 'XdrHello',
    );
    final Object? jsonListeningPort = XdrJsonHelper.readField(
      object,
      'listening_port',
      type: 'XdrHello',
    );
    final Object? jsonPeerID = XdrJsonHelper.readField(
      object,
      'peer_id',
      type: 'XdrHello',
    );
    final Object? jsonCert = XdrJsonHelper.readField(
      object,
      'cert',
      type: 'XdrHello',
    );
    final Object? jsonNonce = XdrJsonHelper.readField(
      object,
      'nonce',
      type: 'XdrHello',
    );
    return XdrHello(
      XdrUint32.fromXdrJsonValue(jsonLedgerVersion),
      XdrUint32.fromXdrJsonValue(jsonOverlayVersion),
      XdrUint32.fromXdrJsonValue(jsonOverlayMinVersion),
      XdrHash.fromXdrJsonValue(jsonNetworkID),
      XdrJsonHelper.readEscapedString(
        jsonVersionStr,
        type: 'XdrHello',
        key: 'version_str',
        maxBytes: 100,
      ),
      XdrJsonHelper.readInt32(
        jsonListeningPort,
        type: 'XdrHello',
        key: 'listening_port',
      ),
      XdrNodeID.fromXdrJsonValue(jsonPeerID),
      XdrAuthCert.fromXdrJsonValue(jsonCert),
      XdrUint256.fromXdrJsonValue(jsonNonce),
    );
  }
}
