// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';

class XdrLedgerHeaderHistoryEntryExt {
  int _v;

  int get discriminant => this._v;
  set discriminant(int value) => this._v = value;

  /// Alias for [discriminant], the original XDR field name.
  int get v => this._v;
  set v(int value) => this._v = value;

  XdrLedgerHeaderHistoryEntryExt(this._v);

  static void encode(
    XdrDataOutputStream stream,
    XdrLedgerHeaderHistoryEntryExt encodedLedgerHeaderHistoryEntryExt,
  ) {
    stream.writeInt(encodedLedgerHeaderHistoryEntryExt.discriminant);
    switch (encodedLedgerHeaderHistoryEntryExt.discriminant) {
      case 0:
        break;
      default:
        break;
    }
  }

  static XdrLedgerHeaderHistoryEntryExt decode(XdrDataInputStream stream) {
    int discriminant = stream.readInt();
    XdrLedgerHeaderHistoryEntryExt decodedLedgerHeaderHistoryEntryExt =
        XdrLedgerHeaderHistoryEntryExt(discriminant);
    switch (decodedLedgerHeaderHistoryEntryExt.discriminant) {
      case 0:
        break;
      default:
        break;
    }
    return decodedLedgerHeaderHistoryEntryExt;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrLedgerHeaderHistoryEntryExt.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrLedgerHeaderHistoryEntryExt fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrLedgerHeaderHistoryEntryExt.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrLedgerHeaderHistoryEntryExt',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrLedgerHeaderHistoryEntryExt.
  static XdrLedgerHeaderHistoryEntryExt fromXdrJson(String json) =>
      fromXdrJsonValue(
        XdrJsonHelper.decodeDocument(
          json,
          type: 'XdrLedgerHeaderHistoryEntryExt',
        ),
      );

  /// Returns the SEP-0051 rendering of this XdrLedgerHeaderHistoryEntryExt.
  Object? toXdrJsonValue() {
    switch (discriminant) {
      case 0:
        return 'v0';
    }
    XdrJsonHelper.fail(
      'XdrLedgerHeaderHistoryEntryExt',
      'holds the unknown discriminant ${discriminant}',
    );
  }

  /// Reads a XdrLedgerHeaderHistoryEntryExt from its SEP-0051 rendering.
  static XdrLedgerHeaderHistoryEntryExt fromXdrJsonValue(Object? value) {
    if (value is String) {
      switch (value) {
        case 'v0':
          return XdrLedgerHeaderHistoryEntryExt(0);
      }
      XdrJsonHelper.fail(
        'XdrLedgerHeaderHistoryEntryExt',
        'has no arm named ${XdrJsonHelper.preview(value)}',
      );
    }
    XdrJsonHelper.fail(
      'XdrLedgerHeaderHistoryEntryExt',
      'expects one of its arm names but found ${XdrJsonHelper.preview(value)}',
    );
  }
}
