// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_transaction_history_entry_ext.dart';
import 'xdr_transaction_set.dart';
import 'xdr_uint32.dart';

class XdrTransactionHistoryEntry {

  XdrUint32 _ledgerSeq;
  XdrUint32 get ledgerSeq => this._ledgerSeq;
  set ledgerSeq(XdrUint32 value) => this._ledgerSeq = value;

  XdrTransactionSet _txSet;
  XdrTransactionSet get txSet => this._txSet;
  set txSet(XdrTransactionSet value) => this._txSet = value;

  XdrTransactionHistoryEntryExt _ext;
  XdrTransactionHistoryEntryExt get ext => this._ext;
  set ext(XdrTransactionHistoryEntryExt value) => this._ext = value;

  XdrTransactionHistoryEntry(this._ledgerSeq, this._txSet, this._ext);

  static void encode(XdrDataOutputStream stream, XdrTransactionHistoryEntry encodedTransactionHistoryEntry) {
    XdrUint32.encode(stream, encodedTransactionHistoryEntry.ledgerSeq);
    XdrTransactionSet.encode(stream, encodedTransactionHistoryEntry.txSet);
    XdrTransactionHistoryEntryExt.encode(stream, encodedTransactionHistoryEntry.ext);
  }

  static XdrTransactionHistoryEntry decode(XdrDataInputStream stream) {
    XdrUint32 ledgerSeq = XdrUint32.decode(stream);
    XdrTransactionSet txSet = XdrTransactionSet.decode(stream);
    XdrTransactionHistoryEntryExt ext = XdrTransactionHistoryEntryExt.decode(stream);
    return XdrTransactionHistoryEntry(ledgerSeq, txSet, ext);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrTransactionHistoryEntry.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrTransactionHistoryEntry fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrTransactionHistoryEntry.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _ledgerSeq.toTxRep('$prefix.ledgerSeq', lines);
    _txSet.toTxRep('$prefix.txSet', lines);
    _ext.toTxRep('$prefix.ext', lines);
  }

  static XdrTransactionHistoryEntry fromTxRep(Map<String, String> map, String prefix) {
    XdrUint32 ledgerSeq = XdrUint32.fromTxRep(map, '$prefix.ledgerSeq');
    XdrTransactionSet txSet = XdrTransactionSet.fromTxRep(map, '$prefix.txSet');
    XdrTransactionHistoryEntryExt ext = XdrTransactionHistoryEntryExt.fromTxRep(map, '$prefix.ext');
    return XdrTransactionHistoryEntry(ledgerSeq, txSet, ext);
  }
}
