// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_asset.dart';
import 'xdr_claimable_balance_entry_ext.dart';
import 'xdr_claimable_balance_id.dart';
import 'xdr_claimant.dart';
import 'xdr_data_io.dart';
import 'xdr_int64.dart';

class XdrClaimableBalanceEntry {
  XdrClaimableBalanceID _balanceID;
  XdrClaimableBalanceID get balanceID => this._balanceID;
  set balanceID(XdrClaimableBalanceID value) => this._balanceID = value;

  List<XdrClaimant> _claimants;
  List<XdrClaimant> get claimants => this._claimants;
  set claimants(List<XdrClaimant> value) => this._claimants = value;

  XdrAsset _asset;
  XdrAsset get asset => this._asset;
  set asset(XdrAsset value) => this._asset = value;

  XdrInt64 _amount;
  XdrInt64 get amount => this._amount;
  set amount(XdrInt64 value) => this._amount = value;

  XdrClaimableBalanceEntryExt _ext;
  XdrClaimableBalanceEntryExt get ext => this._ext;
  set ext(XdrClaimableBalanceEntryExt value) => this._ext = value;

  XdrClaimableBalanceEntry(
    this._balanceID,
    this._claimants,
    this._asset,
    this._amount,
    this._ext,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrClaimableBalanceEntry encodedClaimableBalanceEntry,
  ) {
    XdrClaimableBalanceID.encode(
      stream,
      encodedClaimableBalanceEntry.balanceID,
    );
    int claimantssize = encodedClaimableBalanceEntry.claimants.length;
    stream.writeInt(claimantssize);
    for (int i = 0; i < claimantssize; i++) {
      XdrClaimant.encode(stream, encodedClaimableBalanceEntry.claimants[i]);
    }
    XdrAsset.encode(stream, encodedClaimableBalanceEntry.asset);
    XdrInt64.encode(stream, encodedClaimableBalanceEntry.amount);
    XdrClaimableBalanceEntryExt.encode(
      stream,
      encodedClaimableBalanceEntry.ext,
    );
  }

  static XdrClaimableBalanceEntry decode(XdrDataInputStream stream) {
    XdrClaimableBalanceID balanceID = XdrClaimableBalanceID.decode(stream);
    int claimantssize = stream.readInt();
    List<XdrClaimant> claimants = List<XdrClaimant>.empty(growable: true);
    for (int i = 0; i < claimantssize; i++) {
      claimants.add(XdrClaimant.decode(stream));
    }
    XdrAsset asset = XdrAsset.decode(stream);
    XdrInt64 amount = XdrInt64.decode(stream);
    XdrClaimableBalanceEntryExt ext = XdrClaimableBalanceEntryExt.decode(
      stream,
    );
    return XdrClaimableBalanceEntry(balanceID, claimants, asset, amount, ext);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrClaimableBalanceEntry.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrClaimableBalanceEntry fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrClaimableBalanceEntry.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _balanceID.toTxRep('$prefix.balanceID', lines);
    lines.add('$prefix.claimants.len: ${_claimants.length}');
    for (int i = 0; i < _claimants.length; i++) {
      _claimants[i].toTxRep('$prefix.claimants[$i]', lines);
    }
    lines.add('$prefix.asset: ${TxRepHelper.formatAsset(_asset)}');
    _amount.toTxRep('$prefix.amount', lines);
    _ext.toTxRep('$prefix.ext', lines);
  }

  static XdrClaimableBalanceEntry fromTxRep(
    Map<String, String> map,
    String prefix,
  ) {
    XdrClaimableBalanceID balanceID = XdrClaimableBalanceID.fromTxRep(
      map,
      '$prefix.balanceID',
    );
    int claimantsLen = TxRepHelper.parseInt(
      TxRepHelper.getValue(map, '$prefix.claimants.len') ?? '0',
    );
    List<XdrClaimant> claimants = [];
    for (int i = 0; i < claimantsLen; i++) {
      claimants.add(XdrClaimant.fromTxRep(map, '$prefix.claimants[$i]'));
    }
    XdrAsset asset = TxRepHelper.parseAsset(
      TxRepHelper.getValue(map, '$prefix.asset') ?? '',
    );
    XdrInt64 amount = XdrInt64.fromTxRep(map, '$prefix.amount');
    XdrClaimableBalanceEntryExt ext = XdrClaimableBalanceEntryExt.fromTxRep(
      map,
      '$prefix.ext',
    );
    return XdrClaimableBalanceEntry(balanceID, claimants, asset, amount, ext);
  }
}
