// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';
import 'xdr_signature.dart';
import 'xdr_time_sliced_survey_request_message.dart';

class XdrSignedTimeSlicedSurveyRequestMessage {
  XdrSignature _requestSignature;
  XdrSignature get requestSignature => this._requestSignature;
  set requestSignature(XdrSignature value) => this._requestSignature = value;

  XdrTimeSlicedSurveyRequestMessage _request;
  XdrTimeSlicedSurveyRequestMessage get request => this._request;
  set request(XdrTimeSlicedSurveyRequestMessage value) => this._request = value;

  XdrSignedTimeSlicedSurveyRequestMessage(
    this._requestSignature,
    this._request,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrSignedTimeSlicedSurveyRequestMessage
    encodedSignedTimeSlicedSurveyRequestMessage,
  ) {
    XdrSignature.encode(
      stream,
      encodedSignedTimeSlicedSurveyRequestMessage.requestSignature,
    );
    XdrTimeSlicedSurveyRequestMessage.encode(
      stream,
      encodedSignedTimeSlicedSurveyRequestMessage.request,
    );
  }

  static XdrSignedTimeSlicedSurveyRequestMessage decode(
    XdrDataInputStream stream,
  ) {
    XdrSignature requestSignature = XdrSignature.decode(stream);
    XdrTimeSlicedSurveyRequestMessage request =
        XdrTimeSlicedSurveyRequestMessage.decode(stream);
    return XdrSignedTimeSlicedSurveyRequestMessage(requestSignature, request);
  }
}
