// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_uint32.dart';

class XdrSCSpecUDTErrorEnumCaseV0 {

  String _doc;
  String get doc => this._doc;
  set doc(String value) => this._doc = value;

  String _name;
  String get name => this._name;
  set name(String value) => this._name = value;

  XdrUint32 _value;
  XdrUint32 get value => this._value;
  set value(XdrUint32 value) => this._value = value;

  XdrSCSpecUDTErrorEnumCaseV0(this._doc, this._name, this._value);

  static void encode(XdrDataOutputStream stream, XdrSCSpecUDTErrorEnumCaseV0 encodedSCSpecUDTErrorEnumCaseV0) {
    stream.writeString(encodedSCSpecUDTErrorEnumCaseV0.doc);
    stream.writeString(encodedSCSpecUDTErrorEnumCaseV0.name);
    XdrUint32.encode(stream, encodedSCSpecUDTErrorEnumCaseV0.value);
  }

  static XdrSCSpecUDTErrorEnumCaseV0 decode(XdrDataInputStream stream) {
    String doc = stream.readString();
    String name = stream.readString();
    XdrUint32 value = XdrUint32.decode(stream);
    return XdrSCSpecUDTErrorEnumCaseV0(doc, name, value);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCSpecUDTErrorEnumCaseV0.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCSpecUDTErrorEnumCaseV0 fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCSpecUDTErrorEnumCaseV0.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.doc: ${TxRepHelper.escapeString(_doc)}');
    lines.add('$prefix.name: ${TxRepHelper.escapeString(_name)}');
    _value.toTxRep('$prefix.value', lines);
  }

  static XdrSCSpecUDTErrorEnumCaseV0 fromTxRep(Map<String, String> map, String prefix) {
    String doc = TxRepHelper.unescapeString(TxRepHelper.getValue(map, '$prefix.doc') ?? '');
    String name = TxRepHelper.unescapeString(TxRepHelper.getValue(map, '$prefix.name') ?? '');
    XdrUint32 value = XdrUint32.fromTxRep(map, '$prefix.value');
    return XdrSCSpecUDTErrorEnumCaseV0(doc, name, value);
  }
}
