// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_signer_key.dart';
import 'xdr_uint32.dart';

class XdrSigner {
  XdrSignerKey _key;
  XdrSignerKey get key => this._key;
  set key(XdrSignerKey value) => this._key = value;

  XdrUint32 _weight;
  XdrUint32 get weight => this._weight;
  set weight(XdrUint32 value) => this._weight = value;

  XdrSigner(this._key, this._weight);

  static void encode(XdrDataOutputStream stream, XdrSigner encodedSigner) {
    XdrSignerKey.encode(stream, encodedSigner.key);
    XdrUint32.encode(stream, encodedSigner.weight);
  }

  static XdrSigner decode(XdrDataInputStream stream) {
    XdrSignerKey key = XdrSignerKey.decode(stream);
    XdrUint32 weight = XdrUint32.decode(stream);
    return XdrSigner(key, weight);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSigner.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSigner fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSigner.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.key: ${TxRepHelper.formatSignerKey(_key)}');
    _weight.toTxRep('$prefix.weight', lines);
  }

  static XdrSigner fromTxRep(Map<String, String> map, String prefix) {
    XdrSignerKey key = TxRepHelper.parseSignerKey(
      TxRepHelper.getValue(map, '$prefix.key') ?? '',
    );
    XdrUint32 weight = XdrUint32.fromTxRep(map, '$prefix.weight');
    return XdrSigner(key, weight);
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrSigner');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrSigner.
  static XdrSigner fromXdrJson(String json) =>
      fromXdrJsonValue(XdrJsonHelper.decodeDocument(json, type: 'XdrSigner'));

  /// Returns the SEP-0051 rendering of this XdrSigner.
  Object? toXdrJsonValue() => <String, Object?>{
    'key': _key.toXdrJsonValue(),
    'weight': _weight.toXdrJsonValue(),
  };

  /// Reads a XdrSigner from its SEP-0051 rendering.
  static XdrSigner fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrSigner',
      allowedKeys: const <String>{'key', 'weight'},
    );
    final Object? jsonKey = XdrJsonHelper.readField(
      object,
      'key',
      type: 'XdrSigner',
    );
    final Object? jsonWeight = XdrJsonHelper.readField(
      object,
      'weight',
      type: 'XdrSigner',
    );
    return XdrSigner(
      XdrSignerKey.fromXdrJsonValue(jsonKey),
      XdrUint32.fromXdrJsonValue(jsonWeight),
    );
  }
}
