// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_extension_point.dart';

class XdrRestoreFootprintOp {
  XdrExtensionPoint _ext;
  XdrExtensionPoint get ext => this._ext;
  set ext(XdrExtensionPoint value) => this._ext = value;

  XdrRestoreFootprintOp(this._ext);

  static void encode(
    XdrDataOutputStream stream,
    XdrRestoreFootprintOp encodedRestoreFootprintOp,
  ) {
    XdrExtensionPoint.encode(stream, encodedRestoreFootprintOp.ext);
  }

  static XdrRestoreFootprintOp decode(XdrDataInputStream stream) {
    XdrExtensionPoint ext = XdrExtensionPoint.decode(stream);
    return XdrRestoreFootprintOp(ext);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrRestoreFootprintOp.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrRestoreFootprintOp fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrRestoreFootprintOp.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _ext.toTxRep('$prefix.ext', lines);
  }

  static XdrRestoreFootprintOp fromTxRep(
    Map<String, String> map,
    String prefix,
  ) {
    XdrExtensionPoint ext = XdrExtensionPoint.fromTxRep(map, '$prefix.ext');
    return XdrRestoreFootprintOp(ext);
  }
}
