// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_bucket_entry_type.dart';
import 'xdr_bucket_metadata.dart';
import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_ledger_entry.dart';
import 'xdr_ledger_key.dart';

class XdrBucketEntry {
  XdrBucketEntryType _type;

  XdrBucketEntryType get discriminant => this._type;

  set discriminant(XdrBucketEntryType value) => this._type = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrBucketEntryType get type => this._type;
  set type(XdrBucketEntryType value) => this._type = value;

  XdrLedgerEntry? _liveEntry;

  XdrLedgerEntry? get liveEntry => this._liveEntry;

  XdrLedgerKey? _deadEntry;

  XdrLedgerKey? get deadEntry => this._deadEntry;

  XdrBucketMetadata? _metaEntry;

  XdrBucketMetadata? get metaEntry => this._metaEntry;

  XdrBucketEntry(this._type);

  set liveEntry(XdrLedgerEntry? value) => this._liveEntry = value;

  set deadEntry(XdrLedgerKey? value) => this._deadEntry = value;

  set metaEntry(XdrBucketMetadata? value) => this._metaEntry = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrBucketEntry encodedBucketEntry,
  ) {
    stream.writeInt(encodedBucketEntry.discriminant.value);
    switch (encodedBucketEntry.discriminant) {
      case XdrBucketEntryType.LIVEENTRY:
      case XdrBucketEntryType.INITENTRY:
        XdrLedgerEntry.encode(stream, encodedBucketEntry._liveEntry!);
        break;
      case XdrBucketEntryType.DEADENTRY:
        XdrLedgerKey.encode(stream, encodedBucketEntry._deadEntry!);
        break;
      case XdrBucketEntryType.METAENTRY:
        XdrBucketMetadata.encode(stream, encodedBucketEntry._metaEntry!);
        break;
      default:
        break;
    }
  }

  static XdrBucketEntry decode(XdrDataInputStream stream) {
    XdrBucketEntry decodedBucketEntry = XdrBucketEntry(
      XdrBucketEntryType.decode(stream),
    );
    switch (decodedBucketEntry.discriminant) {
      case XdrBucketEntryType.LIVEENTRY:
      case XdrBucketEntryType.INITENTRY:
        decodedBucketEntry._liveEntry = XdrLedgerEntry.decode(stream);
        break;
      case XdrBucketEntryType.DEADENTRY:
        decodedBucketEntry._deadEntry = XdrLedgerKey.decode(stream);
        break;
      case XdrBucketEntryType.METAENTRY:
        decodedBucketEntry._metaEntry = XdrBucketMetadata.decode(stream);
        break;
      default:
        break;
    }
    return decodedBucketEntry;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrBucketEntry.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrBucketEntry fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrBucketEntry.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrBucketEntry');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrBucketEntry.
  static XdrBucketEntry fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrBucketEntry'),
  );

  /// Returns the SEP-0051 rendering of this XdrBucketEntry.
  Object? toXdrJsonValue() {
    switch (discriminant.value) {
      case 0:
        return <String, Object?>{'liveentry': _liveEntry!.toXdrJsonValue()};
      case 2:
        return <String, Object?>{'initentry': _liveEntry!.toXdrJsonValue()};
      case 1:
        return <String, Object?>{'deadentry': _deadEntry!.toXdrJsonValue()};
      case -1:
        return <String, Object?>{'metaentry': _metaEntry!.toXdrJsonValue()};
    }
    XdrJsonHelper.fail(
      'XdrBucketEntry',
      'holds the unknown discriminant ${discriminant.value}',
    );
  }

  /// Reads a XdrBucketEntry from its SEP-0051 rendering.
  static XdrBucketEntry fromXdrJsonValue(Object? value) {
    final MapEntry<String, Object?> arm = XdrJsonHelper.readSingleKeyObject(
      value,
      type: 'XdrBucketEntry',
    );
    switch (arm.key) {
      case 'liveentry':
        final XdrBucketEntry arm0 = XdrBucketEntry(
          XdrBucketEntryType.LIVEENTRY,
        );
        arm0.liveEntry = XdrLedgerEntry.fromXdrJsonValue(arm.value);
        return arm0;
      case 'initentry':
        final XdrBucketEntry arm1 = XdrBucketEntry(
          XdrBucketEntryType.INITENTRY,
        );
        arm1.liveEntry = XdrLedgerEntry.fromXdrJsonValue(arm.value);
        return arm1;
      case 'deadentry':
        final XdrBucketEntry arm2 = XdrBucketEntry(
          XdrBucketEntryType.DEADENTRY,
        );
        arm2.deadEntry = XdrLedgerKey.fromXdrJsonValue(arm.value);
        return arm2;
      case 'metaentry':
        final XdrBucketEntry arm3 = XdrBucketEntry(
          XdrBucketEntryType.METAENTRY,
        );
        arm3.metaEntry = XdrBucketMetadata.fromXdrJsonValue(arm.value);
        return arm3;
    }
    XdrJsonHelper.fail(
      'XdrBucketEntry',
      'has no arm named ${XdrJsonHelper.preview(arm.key)}',
    );
  }
}
