// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_json_helper.dart';
import 'xdr_sc_env_meta_entry_interface_version.dart';
import 'xdr_sc_env_meta_kind.dart';

class XdrSCEnvMetaEntry {
  XdrSCEnvMetaKind _kind;

  XdrSCEnvMetaKind get discriminant => this._kind;

  set discriminant(XdrSCEnvMetaKind value) => this._kind = value;

  /// Alias for [discriminant], the original XDR field name.
  XdrSCEnvMetaKind get kind => this._kind;
  set kind(XdrSCEnvMetaKind value) => this._kind = value;

  XdrSCEnvMetaEntryInterfaceVersion? _interfaceVersion;

  XdrSCEnvMetaEntryInterfaceVersion? get interfaceVersion =>
      this._interfaceVersion;

  XdrSCEnvMetaEntry(this._kind);

  set interfaceVersion(XdrSCEnvMetaEntryInterfaceVersion? value) =>
      this._interfaceVersion = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrSCEnvMetaEntry encodedSCEnvMetaEntry,
  ) {
    stream.writeInt(encodedSCEnvMetaEntry.discriminant.value);
    switch (encodedSCEnvMetaEntry.discriminant) {
      case XdrSCEnvMetaKind.SC_ENV_META_KIND_INTERFACE_VERSION:
        XdrSCEnvMetaEntryInterfaceVersion.encode(
          stream,
          encodedSCEnvMetaEntry._interfaceVersion!,
        );
        break;
      default:
        break;
    }
  }

  static XdrSCEnvMetaEntry decode(XdrDataInputStream stream) {
    XdrSCEnvMetaEntry decodedSCEnvMetaEntry = XdrSCEnvMetaEntry(
      XdrSCEnvMetaKind.decode(stream),
    );
    switch (decodedSCEnvMetaEntry.discriminant) {
      case XdrSCEnvMetaKind.SC_ENV_META_KIND_INTERFACE_VERSION:
        decodedSCEnvMetaEntry._interfaceVersion =
            XdrSCEnvMetaEntryInterfaceVersion.decode(stream);
        break;
      default:
        break;
    }
    return decodedSCEnvMetaEntry;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSCEnvMetaEntry.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSCEnvMetaEntry fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSCEnvMetaEntry.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrSCEnvMetaEntry');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrSCEnvMetaEntry.
  static XdrSCEnvMetaEntry fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrSCEnvMetaEntry'),
  );

  /// Returns the SEP-0051 rendering of this XdrSCEnvMetaEntry.
  Object? toXdrJsonValue() {
    switch (discriminant.value) {
      case 0:
        return <String, Object?>{
          'sc_env_meta_kind_interface_version': _interfaceVersion!
              .toXdrJsonValue(),
        };
    }
    XdrJsonHelper.fail(
      'XdrSCEnvMetaEntry',
      'holds the unknown discriminant ${discriminant.value}',
    );
  }

  /// Reads a XdrSCEnvMetaEntry from its SEP-0051 rendering.
  static XdrSCEnvMetaEntry fromXdrJsonValue(Object? value) {
    final MapEntry<String, Object?> arm = XdrJsonHelper.readSingleKeyObject(
      value,
      type: 'XdrSCEnvMetaEntry',
    );
    switch (arm.key) {
      case 'sc_env_meta_kind_interface_version':
        final XdrSCEnvMetaEntry arm0 = XdrSCEnvMetaEntry(
          XdrSCEnvMetaKind.SC_ENV_META_KIND_INTERFACE_VERSION,
        );
        arm0.interfaceVersion =
            XdrSCEnvMetaEntryInterfaceVersion.fromXdrJsonValue(arm.value);
        return arm0;
    }
    XdrJsonHelper.fail(
      'XdrSCEnvMetaEntry',
      'has no arm named ${XdrJsonHelper.preview(arm.key)}',
    );
  }
}
