// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_data_io.dart';
import 'xdr_hash.dart';

class XdrTxDemandVector {
  XdrTxDemandVector(this._txDemandVector);

  List<XdrHash> _txDemandVector;
  List<XdrHash> get txDemandVector => this._txDemandVector;
  set txDemandVector(List<XdrHash> value) => this._txDemandVector = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrTxDemandVector encodedTxDemandVector,
  ) {
    int size = encodedTxDemandVector.txDemandVector.length;
    stream.writeInt(size);
    for (int i = 0; i < size; i++) {
      XdrHash.encode(stream, encodedTxDemandVector.txDemandVector[i]);
    }
  }

  static XdrTxDemandVector decode(XdrDataInputStream stream) {
    int size = stream.readInt();
    List<XdrHash> items = List<XdrHash>.empty(growable: true);
    for (int i = 0; i < size; i++) {
      items.add(XdrHash.decode(stream));
    }
    return XdrTxDemandVector(items);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrTxDemandVector.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrTxDemandVector fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrTxDemandVector.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    lines.add('$prefix.len: ${_txDemandVector.length}');
    for (int i = 0; i < _txDemandVector.length; i++) {
      _txDemandVector[i].toTxRep('$prefix[$i]', lines);
    }
  }

  static XdrTxDemandVector fromTxRep(Map<String, String> map, String prefix) {
    int len = TxRepHelper.parseInt(
      TxRepHelper.getValue(map, '$prefix.len') ?? '0',
    );
    List<XdrHash> items = [];
    for (int i = 0; i < len; i++) {
      items.add(XdrHash.fromTxRep(map, '$prefix[$i]'));
    }
    return XdrTxDemandVector(items);
  }
}
