// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_extension_point.dart';
import 'xdr_int64.dart';
import 'xdr_json_helper.dart';

class XdrSorobanTransactionMetaExtV1 {
  XdrExtensionPoint _ext;
  XdrExtensionPoint get ext => this._ext;
  set ext(XdrExtensionPoint value) => this._ext = value;

  XdrInt64 _totalNonRefundableResourceFeeCharged;
  XdrInt64 get totalNonRefundableResourceFeeCharged =>
      this._totalNonRefundableResourceFeeCharged;
  set totalNonRefundableResourceFeeCharged(XdrInt64 value) =>
      this._totalNonRefundableResourceFeeCharged = value;

  XdrInt64 _totalRefundableResourceFeeCharged;
  XdrInt64 get totalRefundableResourceFeeCharged =>
      this._totalRefundableResourceFeeCharged;
  set totalRefundableResourceFeeCharged(XdrInt64 value) =>
      this._totalRefundableResourceFeeCharged = value;

  XdrInt64 _rentFeeCharged;
  XdrInt64 get rentFeeCharged => this._rentFeeCharged;
  set rentFeeCharged(XdrInt64 value) => this._rentFeeCharged = value;

  XdrSorobanTransactionMetaExtV1(
    this._ext,
    this._totalNonRefundableResourceFeeCharged,
    this._totalRefundableResourceFeeCharged,
    this._rentFeeCharged,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrSorobanTransactionMetaExtV1 encodedSorobanTransactionMetaExtV1,
  ) {
    XdrExtensionPoint.encode(stream, encodedSorobanTransactionMetaExtV1.ext);
    XdrInt64.encode(
      stream,
      encodedSorobanTransactionMetaExtV1.totalNonRefundableResourceFeeCharged,
    );
    XdrInt64.encode(
      stream,
      encodedSorobanTransactionMetaExtV1.totalRefundableResourceFeeCharged,
    );
    XdrInt64.encode(stream, encodedSorobanTransactionMetaExtV1.rentFeeCharged);
  }

  static XdrSorobanTransactionMetaExtV1 decode(XdrDataInputStream stream) {
    XdrExtensionPoint ext = XdrExtensionPoint.decode(stream);
    XdrInt64 totalNonRefundableResourceFeeCharged = XdrInt64.decode(stream);
    XdrInt64 totalRefundableResourceFeeCharged = XdrInt64.decode(stream);
    XdrInt64 rentFeeCharged = XdrInt64.decode(stream);
    return XdrSorobanTransactionMetaExtV1(
      ext,
      totalNonRefundableResourceFeeCharged,
      totalRefundableResourceFeeCharged,
      rentFeeCharged,
    );
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrSorobanTransactionMetaExtV1.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrSorobanTransactionMetaExtV1 fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrSorobanTransactionMetaExtV1.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() => XdrJsonHelper.encodeDocument(
    toXdrJsonValue(),
    type: 'XdrSorobanTransactionMetaExtV1',
  );

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrSorobanTransactionMetaExtV1.
  static XdrSorobanTransactionMetaExtV1 fromXdrJson(String json) =>
      fromXdrJsonValue(
        XdrJsonHelper.decodeDocument(
          json,
          type: 'XdrSorobanTransactionMetaExtV1',
        ),
      );

  /// Returns the SEP-0051 rendering of this XdrSorobanTransactionMetaExtV1.
  Object? toXdrJsonValue() => <String, Object?>{
    'ext': _ext.toXdrJsonValue(),
    'total_non_refundable_resource_fee_charged':
        _totalNonRefundableResourceFeeCharged.toXdrJsonValue(),
    'total_refundable_resource_fee_charged': _totalRefundableResourceFeeCharged
        .toXdrJsonValue(),
    'rent_fee_charged': _rentFeeCharged.toXdrJsonValue(),
  };

  /// Reads a XdrSorobanTransactionMetaExtV1 from its SEP-0051 rendering.
  static XdrSorobanTransactionMetaExtV1 fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrSorobanTransactionMetaExtV1',
      allowedKeys: const <String>{
        'ext',
        'total_non_refundable_resource_fee_charged',
        'total_refundable_resource_fee_charged',
        'rent_fee_charged',
      },
    );
    final Object? jsonExt = XdrJsonHelper.readField(
      object,
      'ext',
      type: 'XdrSorobanTransactionMetaExtV1',
    );
    final Object? jsonTotalNonRefundableResourceFeeCharged =
        XdrJsonHelper.readField(
          object,
          'total_non_refundable_resource_fee_charged',
          type: 'XdrSorobanTransactionMetaExtV1',
        );
    final Object? jsonTotalRefundableResourceFeeCharged =
        XdrJsonHelper.readField(
          object,
          'total_refundable_resource_fee_charged',
          type: 'XdrSorobanTransactionMetaExtV1',
        );
    final Object? jsonRentFeeCharged = XdrJsonHelper.readField(
      object,
      'rent_fee_charged',
      type: 'XdrSorobanTransactionMetaExtV1',
    );
    return XdrSorobanTransactionMetaExtV1(
      XdrExtensionPoint.fromXdrJsonValue(jsonExt),
      XdrInt64.fromXdrJsonValue(jsonTotalNonRefundableResourceFeeCharged),
      XdrInt64.fromXdrJsonValue(jsonTotalRefundableResourceFeeCharged),
      XdrInt64.fromXdrJsonValue(jsonRentFeeCharged),
    );
  }
}
