// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_ledger_entry.dart';
import 'xdr_ledger_entry_change_type.dart';
import 'xdr_ledger_key.dart';

class XdrLedgerEntryChange {
  XdrLedgerEntryChangeType _type;

  XdrLedgerEntryChangeType get discriminant => this._type;

  set discriminant(XdrLedgerEntryChangeType value) => this._type = value;

  XdrLedgerEntry? _created;

  XdrLedgerEntry? get created => this._created;

  XdrLedgerEntry? _updated;

  XdrLedgerEntry? get updated => this._updated;

  XdrLedgerKey? _removed;

  XdrLedgerKey? get removed => this._removed;

  XdrLedgerEntry? _state;

  XdrLedgerEntry? get state => this._state;

  XdrLedgerEntry? _restored;

  XdrLedgerEntry? get restored => this._restored;

  XdrLedgerEntryChange(this._type);

  set created(XdrLedgerEntry? value) => this._created = value;

  set updated(XdrLedgerEntry? value) => this._updated = value;

  set removed(XdrLedgerKey? value) => this._removed = value;

  set state(XdrLedgerEntry? value) => this._state = value;

  set restored(XdrLedgerEntry? value) => this._restored = value;

  static void encode(
    XdrDataOutputStream stream,
    XdrLedgerEntryChange encodedLedgerEntryChange,
  ) {
    stream.writeInt(encodedLedgerEntryChange.discriminant.value);
    switch (encodedLedgerEntryChange.discriminant) {
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_CREATED:
        XdrLedgerEntry.encode(stream, encodedLedgerEntryChange._created!);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_UPDATED:
        XdrLedgerEntry.encode(stream, encodedLedgerEntryChange._updated!);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_REMOVED:
        XdrLedgerKey.encode(stream, encodedLedgerEntryChange._removed!);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_STATE:
        XdrLedgerEntry.encode(stream, encodedLedgerEntryChange._state!);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_RESTORED:
        XdrLedgerEntry.encode(stream, encodedLedgerEntryChange._restored!);
        break;
      default:
        break;
    }
  }

  static XdrLedgerEntryChange decode(XdrDataInputStream stream) {
    XdrLedgerEntryChange decodedLedgerEntryChange = XdrLedgerEntryChange(
      XdrLedgerEntryChangeType.decode(stream),
    );
    switch (decodedLedgerEntryChange.discriminant) {
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_CREATED:
        decodedLedgerEntryChange._created = XdrLedgerEntry.decode(stream);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_UPDATED:
        decodedLedgerEntryChange._updated = XdrLedgerEntry.decode(stream);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_REMOVED:
        decodedLedgerEntryChange._removed = XdrLedgerKey.decode(stream);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_STATE:
        decodedLedgerEntryChange._state = XdrLedgerEntry.decode(stream);
        break;
      case XdrLedgerEntryChangeType.LEDGER_ENTRY_RESTORED:
        decodedLedgerEntryChange._restored = XdrLedgerEntry.decode(stream);
        break;
      default:
        break;
    }
    return decodedLedgerEntryChange;
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrLedgerEntryChange.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrLedgerEntryChange fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrLedgerEntryChange.decode(XdrDataInputStream(bytes));
  }
}
