// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'xdr_data_io.dart';
import 'xdr_hash.dart';
import 'xdr_ledger_close_value_signature.dart';
import 'xdr_uint32.dart';

class XdrStellarValueProposedValue {
  XdrHash _txSetHash;
  XdrHash get txSetHash => this._txSetHash;
  set txSetHash(XdrHash value) => this._txSetHash = value;

  XdrHash _previousLedgerHash;
  XdrHash get previousLedgerHash => this._previousLedgerHash;
  set previousLedgerHash(XdrHash value) => this._previousLedgerHash = value;

  XdrUint32 _previousLedgerVersion;
  XdrUint32 get previousLedgerVersion => this._previousLedgerVersion;
  set previousLedgerVersion(XdrUint32 value) =>
      this._previousLedgerVersion = value;

  XdrLedgerCloseValueSignature _lcValueSignature;
  XdrLedgerCloseValueSignature get lcValueSignature => this._lcValueSignature;
  set lcValueSignature(XdrLedgerCloseValueSignature value) =>
      this._lcValueSignature = value;

  XdrStellarValueProposedValue(
    this._txSetHash,
    this._previousLedgerHash,
    this._previousLedgerVersion,
    this._lcValueSignature,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrStellarValueProposedValue encodedStellarValueProposedValue,
  ) {
    XdrHash.encode(stream, encodedStellarValueProposedValue.txSetHash);
    XdrHash.encode(stream, encodedStellarValueProposedValue.previousLedgerHash);
    XdrUint32.encode(
      stream,
      encodedStellarValueProposedValue.previousLedgerVersion,
    );
    XdrLedgerCloseValueSignature.encode(
      stream,
      encodedStellarValueProposedValue.lcValueSignature,
    );
  }

  static XdrStellarValueProposedValue decode(XdrDataInputStream stream) {
    XdrHash txSetHash = XdrHash.decode(stream);
    XdrHash previousLedgerHash = XdrHash.decode(stream);
    XdrUint32 previousLedgerVersion = XdrUint32.decode(stream);
    XdrLedgerCloseValueSignature lcValueSignature =
        XdrLedgerCloseValueSignature.decode(stream);
    return XdrStellarValueProposedValue(
      txSetHash,
      previousLedgerHash,
      previousLedgerVersion,
      lcValueSignature,
    );
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrStellarValueProposedValue.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrStellarValueProposedValue fromBase64EncodedXdrString(
    String base64Encoded,
  ) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrStellarValueProposedValue.decode(XdrDataInputStream(bytes));
  }
}
