// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_asset.dart';
import 'xdr_data_io.dart';
import 'xdr_int32.dart';

class XdrLiquidityPoolConstantProductParameters {
  XdrAsset _assetA;
  XdrAsset get assetA => this._assetA;
  set assetA(XdrAsset value) => this._assetA = value;

  XdrAsset _assetB;
  XdrAsset get assetB => this._assetB;
  set assetB(XdrAsset value) => this._assetB = value;

  XdrInt32 _fee;
  XdrInt32 get fee => this._fee;
  set fee(XdrInt32 value) => this._fee = value;

  XdrLiquidityPoolConstantProductParameters(
    this._assetA,
    this._assetB,
    this._fee,
  );

  static void encode(
    XdrDataOutputStream stream,
    XdrLiquidityPoolConstantProductParameters
    encodedLiquidityPoolConstantProductParameters,
  ) {
    XdrAsset.encode(
      stream,
      encodedLiquidityPoolConstantProductParameters.assetA,
    );
    XdrAsset.encode(
      stream,
      encodedLiquidityPoolConstantProductParameters.assetB,
    );
    XdrInt32.encode(stream, encodedLiquidityPoolConstantProductParameters.fee);
  }

  static XdrLiquidityPoolConstantProductParameters decode(
    XdrDataInputStream stream,
  ) {
    XdrAsset assetA = XdrAsset.decode(stream);
    XdrAsset assetB = XdrAsset.decode(stream);
    XdrInt32 fee = XdrInt32.decode(stream);
    return XdrLiquidityPoolConstantProductParameters(assetA, assetB, fee);
  }
}
