// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'xdr_data_io.dart';

class XdrIPAddrType {
  final _value;
  const XdrIPAddrType._internal(this._value);
  toString() => 'IPAddrType.$_value';
  XdrIPAddrType(this._value);
  get value => this._value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XdrIPAddrType && _value == other._value;

  @override
  int get hashCode => _value.hashCode;

  static const IPv4 = const XdrIPAddrType._internal(0);
  static const IPv6 = const XdrIPAddrType._internal(1);

  static XdrIPAddrType decode(XdrDataInputStream stream) {
    int value = stream.readInt();
    switch (value) {
      case 0:
        return IPv4;
      case 1:
        return IPv6;
      default:
        throw Exception("Unknown enum value: $value");
    }
  }

  static void encode(XdrDataOutputStream stream, XdrIPAddrType value) {
    stream.writeInt(value.value);
  }
}
