// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import 'txrep_helper.dart';
import 'xdr_auth_cert.dart';
import 'xdr_data_io.dart';
import 'xdr_hash.dart';
import 'xdr_node_id.dart';
import 'xdr_uint256.dart';
import 'xdr_uint32.dart';

class XdrHello {

  XdrUint32 _ledgerVersion;
  XdrUint32 get ledgerVersion => this._ledgerVersion;
  set ledgerVersion(XdrUint32 value) => this._ledgerVersion = value;

  XdrUint32 _overlayVersion;
  XdrUint32 get overlayVersion => this._overlayVersion;
  set overlayVersion(XdrUint32 value) => this._overlayVersion = value;

  XdrUint32 _overlayMinVersion;
  XdrUint32 get overlayMinVersion => this._overlayMinVersion;
  set overlayMinVersion(XdrUint32 value) => this._overlayMinVersion = value;

  XdrHash _networkID;
  XdrHash get networkID => this._networkID;
  set networkID(XdrHash value) => this._networkID = value;

  String _versionStr;
  String get versionStr => this._versionStr;
  set versionStr(String value) => this._versionStr = value;

  int _listeningPort;
  int get listeningPort => this._listeningPort;
  set listeningPort(int value) => this._listeningPort = value;

  XdrNodeID _peerID;
  XdrNodeID get peerID => this._peerID;
  set peerID(XdrNodeID value) => this._peerID = value;

  XdrAuthCert _cert;
  XdrAuthCert get cert => this._cert;
  set cert(XdrAuthCert value) => this._cert = value;

  XdrUint256 _nonce;
  XdrUint256 get nonce => this._nonce;
  set nonce(XdrUint256 value) => this._nonce = value;

  XdrHello(this._ledgerVersion, this._overlayVersion, this._overlayMinVersion, this._networkID, this._versionStr, this._listeningPort, this._peerID, this._cert, this._nonce);

  static void encode(XdrDataOutputStream stream, XdrHello encodedHello) {
    XdrUint32.encode(stream, encodedHello.ledgerVersion);
    XdrUint32.encode(stream, encodedHello.overlayVersion);
    XdrUint32.encode(stream, encodedHello.overlayMinVersion);
    XdrHash.encode(stream, encodedHello.networkID);
    stream.writeString(encodedHello.versionStr);
    stream.writeInt(encodedHello.listeningPort);
    XdrNodeID.encode(stream, encodedHello.peerID);
    XdrAuthCert.encode(stream, encodedHello.cert);
    XdrUint256.encode(stream, encodedHello.nonce);
  }

  static XdrHello decode(XdrDataInputStream stream) {
    XdrUint32 ledgerVersion = XdrUint32.decode(stream);
    XdrUint32 overlayVersion = XdrUint32.decode(stream);
    XdrUint32 overlayMinVersion = XdrUint32.decode(stream);
    XdrHash networkID = XdrHash.decode(stream);
    String versionStr = stream.readString();
    int listeningPort = stream.readInt();
    XdrNodeID peerID = XdrNodeID.decode(stream);
    XdrAuthCert cert = XdrAuthCert.decode(stream);
    XdrUint256 nonce = XdrUint256.decode(stream);
    return XdrHello(ledgerVersion, overlayVersion, overlayMinVersion, networkID, versionStr, listeningPort, peerID, cert, nonce);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrHello.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrHello fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrHello.decode(XdrDataInputStream(bytes));
  }

  void toTxRep(String prefix, List<String> lines) {
    _ledgerVersion.toTxRep('$prefix.ledgerVersion', lines);
    _overlayVersion.toTxRep('$prefix.overlayVersion', lines);
    _overlayMinVersion.toTxRep('$prefix.overlayMinVersion', lines);
    _networkID.toTxRep('$prefix.networkID', lines);
    lines.add('$prefix.versionStr: ${TxRepHelper.escapeString(_versionStr)}');
    lines.add('$prefix.listeningPort: $_listeningPort');
    _peerID.toTxRep('$prefix.peerID', lines);
    _cert.toTxRep('$prefix.cert', lines);
    _nonce.toTxRep('$prefix.nonce', lines);
  }

  static XdrHello fromTxRep(Map<String, String> map, String prefix) {
    XdrUint32 ledgerVersion = XdrUint32.fromTxRep(map, '$prefix.ledgerVersion');
    XdrUint32 overlayVersion = XdrUint32.fromTxRep(map, '$prefix.overlayVersion');
    XdrUint32 overlayMinVersion = XdrUint32.fromTxRep(map, '$prefix.overlayMinVersion');
    XdrHash networkID = XdrHash.fromTxRep(map, '$prefix.networkID');
    String versionStr = TxRepHelper.unescapeString(TxRepHelper.getValue(map, '$prefix.versionStr') ?? '');
    int listeningPort = TxRepHelper.parseInt(TxRepHelper.getValue(map, '$prefix.listeningPort') ?? '0');
    XdrNodeID peerID = XdrNodeID.fromTxRep(map, '$prefix.peerID');
    XdrAuthCert cert = XdrAuthCert.fromTxRep(map, '$prefix.cert');
    XdrUint256 nonce = XdrUint256.fromTxRep(map, '$prefix.nonce');
    return XdrHello(ledgerVersion, overlayVersion, overlayMinVersion, networkID, versionStr, listeningPort, peerID, cert, nonce);
  }
}
