// Copyright 2026 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.
// This file is automatically generated by xdrgen. Do not edit manually.

import 'dart:convert';
import 'dart:typed_data';

import '../key_pair.dart';
import 'xdr_contract_event_body.dart';
import 'xdr_contract_event_type.dart';
import 'xdr_data_io.dart';
import 'xdr_extension_point.dart';
import 'xdr_hash.dart';
import 'xdr_json_helper.dart';

class XdrContractEvent {
  XdrExtensionPoint _ext;
  XdrExtensionPoint get ext => this._ext;
  set ext(XdrExtensionPoint value) => this._ext = value;

  XdrHash? _hash;
  XdrHash? get hash => this._hash;
  set hash(XdrHash? value) => this._hash = value;

  XdrContractEventType _type;
  XdrContractEventType get type => this._type;
  set type(XdrContractEventType value) => this._type = value;

  XdrContractEventBody _body;
  XdrContractEventBody get body => this._body;
  set body(XdrContractEventBody value) => this._body = value;

  XdrContractEvent(this._ext, this._hash, this._type, this._body);

  static void encode(
    XdrDataOutputStream stream,
    XdrContractEvent encodedContractEvent,
  ) {
    XdrExtensionPoint.encode(stream, encodedContractEvent.ext);
    if (encodedContractEvent.hash != null) {
      stream.writeInt(1);
      XdrHash.encode(stream, encodedContractEvent.hash!);
    } else {
      stream.writeInt(0);
    }
    XdrContractEventType.encode(stream, encodedContractEvent.type);
    XdrContractEventBody.encode(stream, encodedContractEvent.body);
  }

  static XdrContractEvent decode(XdrDataInputStream stream) {
    XdrExtensionPoint ext = XdrExtensionPoint.decode(stream);
    XdrHash? hash;
    int hashPresent = stream.readInt();
    if (hashPresent != 0) {
      hash = XdrHash.decode(stream);
    }
    XdrContractEventType type = XdrContractEventType.decode(stream);
    XdrContractEventBody body = XdrContractEventBody.decode(stream);
    return XdrContractEvent(ext, hash, type, body);
  }

  String toBase64EncodedXdrString() {
    XdrDataOutputStream xdrOutputStream = XdrDataOutputStream();
    XdrContractEvent.encode(xdrOutputStream, this);
    return base64Encode(xdrOutputStream.bytes);
  }

  static XdrContractEvent fromBase64EncodedXdrString(String base64Encoded) {
    Uint8List bytes = base64Decode(base64Encoded);
    return XdrContractEvent.decode(XdrDataInputStream(bytes));
  }

  /// Returns the SEP-0051 XDR-JSON rendering of this value.
  String toXdrJson() =>
      XdrJsonHelper.encodeDocument(toXdrJsonValue(), type: 'XdrContractEvent');

  /// Parses the SEP-0051 XDR-JSON rendering of a XdrContractEvent.
  static XdrContractEvent fromXdrJson(String json) => fromXdrJsonValue(
    XdrJsonHelper.decodeDocument(json, type: 'XdrContractEvent'),
  );

  /// Returns the SEP-0051 rendering of this XdrContractEvent.
  Object? toXdrJsonValue() => <String, Object?>{
    'ext': _ext.toXdrJsonValue(),
    'contract_id': _hash == null ? null : StrKey.encodeContractId(_hash!.hash),
    'type': _type.toXdrJsonValue(),
    'body': _body.toXdrJsonValue(),
  };

  /// Reads a XdrContractEvent from its SEP-0051 rendering.
  static XdrContractEvent fromXdrJsonValue(Object? value) {
    final Map<String, dynamic> object = XdrJsonHelper.readObject(
      value,
      type: 'XdrContractEvent',
      allowedKeys: const <String>{
        'ext',
        'contract_id',
        'type',
        'type_',
        'body',
      },
    );
    final Object? jsonExt = XdrJsonHelper.readField(
      object,
      'ext',
      type: 'XdrContractEvent',
    );
    final Object? jsonHash = XdrJsonHelper.readField(
      object,
      'contract_id',
      type: 'XdrContractEvent',
    );
    final Object? jsonType = XdrJsonHelper.readField(
      object,
      'type',
      type: 'XdrContractEvent',
      alias: 'type_',
    );
    final Object? jsonBody = XdrJsonHelper.readField(
      object,
      'body',
      type: 'XdrContractEvent',
    );
    return XdrContractEvent(
      XdrExtensionPoint.fromXdrJsonValue(jsonExt),
      jsonHash == null
          ? null
          : XdrHash(
              XdrJsonHelper.readStrKey(
                jsonHash,
                type: 'XdrContractEvent',
                key: 'contract_id',
                decode: StrKey.decodeContractId,
                expectedLength: 32,
              ),
            ),
      XdrContractEventType.fromXdrJsonValue(jsonType),
      XdrContractEventBody.fromXdrJsonValue(jsonBody),
    );
  }
}
