"""Hand-authored seeds for the SEP-0051 (XDR-JSON) conformance corpus.

Each seed is a dict:

  type        Reference CLI type name (ScVal), the spelling `stellar-xdr` uses.
  dart_type   SDK class name (XdrSCVal). Resolved from
              ../sep-51-oracle/type_map.json, which is keyed on the .x
              identifier because the SDK's NAME_OVERRIDES is many-to-one.
  json        The value written in the reference's own XDR-JSON form. The
              corpus generator encodes it with the reference CLI, so a document
              that is not valid XDR-JSON for that type fails the build.
  note        One sentence naming the shape the seed pins.
  oracle      Optional. "incomparable" marks a rendering where the SDK follows
              SEP-0051 and the reference does not; such a seed also carries
              spec_form and spec_form_paths.
  spec_form   Optional. Names the transformation the generator applies to the
              reference's output to derive what the SDK must emit:
              "integer_string" or "opaque_hex".
  spec_form_paths
              Required on every incomparable seed, including one carrying no
              transform, where it is the empty list. Lists the exact locations
              the transformation is expected to rewrite: dotted object keys,
              "[n]" for an array index, and "" for the whole value. The
              generator records what it actually rewrote and fails when the two
              sets differ in either direction, so a value-addressed transform
              can neither miss a location nor reach one it was not meant to.
  reason      Required on an incomparable seed carrying no spec_form, where
              there is no transformation to take the explanation from. It
              records why the reference's output is not what the SDK emits, and
              is written into the entry exactly as a transform's own reason is.

Seeds cover the renderings that are not mechanical: every arm of the unions
whose JSON form is a strkey or a bare name, the integer types rendered as
strings, the SEP-0051 escape ladder over bytes-typed and string-typed fields,
empty and populated variable-length data, optionals in both states, and the
name rules that a pin bump could disturb.

Every seed names a type the SDK exposes as a class carrying the four SEP-0051
members. Where the .x declares a typedef the SDK collapses into its container
-- AssetCode4, AssetCode12, PoolID, SCVec, SCMap, SCString, SCSymbol -- the
rendering is pinned at the containing type instead, which is the only site the
SDK has for it.

A SignerKeyEd25519SignedPayload with a zero-length payload is deliberately
absent: the reference decodes it to a strkey it then refuses to encode, and the
SDK refuses it in both directions, so no JSON text exists for the corpus to
pin. The generator asserts the reference still behaves that way and records the
exclusion in the corpus metadata; the input itself is pinned by a hand-written
negative test.

A document carrying $schema is likewise absent. SEP-0051 requires objects to
accept the property; the reference rejects it outright, and the SDK strips it
and never emits it, so no emitted text differs and there is nothing for an
entry to pin. The generator asserts the reference still rejects it and records
that exclusion in the metadata too.
"""

# --- Reusable values ---------------------------------------------------------

G1 = "GAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSABOV"
G2 = "GAAQCAIBAEAQCAIBAEAQCAIBAEAQCAIBAEAQCAIBAEAQCAIBAEAQDZ7H"
G3 = "GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H"
C1 = "CAQCCIRDEQSSMJZIFEVCWLBNFYXTAMJSGM2DKNRXHA4TUOZ4HU7D7V6Z"
M_ZERO_ID = "MAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAAAAAAAAAA54K"
M1 = "MAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAAAAAAAE2LAOE"
M_MAX_ID = "MAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSB7777777777777NGG"
T1 = "TBAECQSDIRCUMR2IJFFEWTCNJZHVAUKSKNKFKVSXLBMVUW24LVPF7EOJ"
X1 = "XBQGCYTDMRSWMZ3INFVGW3DNNZXXA4LSON2HK5TXPB4XU634PV7H7YJH"
P_SHORT = "PAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAACACAQDATYOS"
P_FULL = (
    "PAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAAQACAQDAQCQ"
    "MBYIBEFAWDANBYHRAEISCMKBKFQXDAMRUGY4DUPB6IHX7Q"
)
B1 = "BAAACAQDAQCQMBYIBEFAWDANBYHRAEISCMKBKFQXDAMRUGY4DUPB6IHRSE"
L1 = "LCAIDAUDQSCYNB4IRGFIXDENR2HZBEMSSOKJLFUXTCMZVG44TWPJ744M"

HASH1 = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
HASH_ZERO = "00" * 32

INT64_MIN = "-9223372036854775808"
INT64_MAX = "9223372036854775807"
UINT64_MAX = "18446744073709551615"
INT128_MIN = "-170141183460469231731687303715884105728"
INT128_MAX = "170141183460469231731687303715884105727"
UINT128_MAX = "340282366920938463463374607431768211455"
INT256_MIN = (
    "-578960446186580977117854925043439539266"
    "34992332820282019728792003956564819968"
)
INT256_MAX = (
    "578960446186580977117854925043439539266"
    "34992332820282019728792003956564819967"
)
UINT256_MAX = (
    "115792089237316195423570985008687907853"
    "269984665640564039457584007913129639935"
)

ALPHANUM4 = {"asset_code": "USD", "issuer": G1}
ALPHANUM12 = {"asset_code": "LONGASSET", "issuer": G1}
ASSET_A4 = {"credit_alphanum4": ALPHANUM4}
ASSET_A12 = {"credit_alphanum12": ALPHANUM12}

BYTES_32 = list(range(1, 33))
BYTES_16 = list(range(1, 17))
BYTES_32_ZERO = [0] * 32

IPV4_LOOPBACK = [127, 0, 0, 1]
IPV6_DOCUMENTATION = [32, 1, 13, 184, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


def _seed(type_name, dart_type, json_value, note, oracle=None, spec_form=None,
          spec_form_paths=None, reason=None):
    seed = {
        "type": type_name,
        "dart_type": dart_type,
        "json": json_value,
        "note": note,
    }
    if oracle is not None:
        seed["oracle"] = oracle
    if spec_form is not None:
        seed["spec_form"] = spec_form
    if spec_form_paths is not None:
        seed["spec_form_paths"] = list(spec_form_paths)
    if reason is not None:
        seed["reason"] = reason
    return seed


SEEDS = [
    # --- SCAddress: one strkey prefix per arm -------------------------------
    _seed("ScAddress", "XdrSCAddress", G1,
          "Account arm renders as a G strkey."),
    _seed("ScAddress", "XdrSCAddress", C1,
          "Contract arm renders as a C strkey."),
    _seed("ScAddress", "XdrSCAddress", M1,
          "Muxed account arm renders as an M strkey carrying the id."),
    _seed("ScAddress", "XdrSCAddress", M_ZERO_ID,
          "Muxed account arm with id zero keeps the M form."),
    _seed("ScAddress", "XdrSCAddress", B1,
          "Claimable balance arm renders as a B strkey."),
    _seed("ScAddress", "XdrSCAddress", L1,
          "Liquidity pool arm renders as an L strkey."),

    # --- SignerKey: one strkey prefix per arm -------------------------------
    _seed("SignerKey", "XdrSignerKey", G1,
          "Ed25519 signer renders as a G strkey."),
    _seed("SignerKey", "XdrSignerKey", T1,
          "Pre-authorized transaction signer renders as a T strkey."),
    _seed("SignerKey", "XdrSignerKey", X1,
          "Hash-x signer renders as an X strkey."),
    _seed("SignerKey", "XdrSignerKey", P_SHORT,
          "Signed payload signer with a four-byte payload renders as a P strkey."),
    _seed("SignerKey", "XdrSignerKey", P_FULL,
          "Signed payload signer at the 32-byte payload limit renders as a P strkey."),

    # --- MuxedAccount, PublicKey, ClaimableBalanceID ------------------------
    _seed("MuxedAccount", "XdrMuxedAccount", G1,
          "Unmuxed arm renders as a G strkey."),
    _seed("MuxedAccount", "XdrMuxedAccount", M1,
          "Muxed arm folds the id into an M strkey."),
    _seed("MuxedAccount", "XdrMuxedAccount", M_MAX_ID,
          "Muxed arm carries the maximum 64-bit id."),
    _seed("PublicKey", "XdrPublicKey", G1,
          "Sole public key arm renders as a G strkey, not an object."),
    _seed("AccountId", "XdrAccountID", G1,
          "Account id typedef renders as the wrapped public key."),
    _seed("NodeId", "XdrNodeID", G1,
          "Node id typedef renders as the wrapped public key."),
    _seed("ClaimableBalanceId", "XdrClaimableBalanceID", B1,
          "Sole claimable balance id arm renders as a B strkey."),
    _seed("LedgerKeyLiquidityPool", "XdrLedgerKeyLiquidityPool",
          {"liquidity_pool_id": L1},
          "Pool id field renders as an L strkey, not as the hash it wraps. PoolID has no Dart class of its own, so its rendering is pinned here."),

    # --- AssetCode: the union renders as a bare string ----------------------
    _seed("AssetCode", "XdrAllowTrustOpAsset", "USD",
          "Four-byte arm of the asset code union renders as a bare string."),
    _seed("AssetCode", "XdrAllowTrustOpAsset", "LONGASSET",
          "Twelve-byte arm of the asset code union renders as a bare string."),

    # --- AssetCode4 and AssetCode12: the escape ladder over raw bytes -------
    # AssetCode4 and AssetCode12 collapse into their container in this SDK, so
    # the ladder is pinned at AlphaNum4 and AlphaNum12, which is the only site
    # the SDK renders them from.
    _seed("AlphaNum4", "XdrAssetAlphaNum4", {"asset_code": "A", "issuer": G1},
          "One-character asset code drops its three padding bytes. AssetCode4 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum4", "XdrAssetAlphaNum4", {"asset_code": "ABC", "issuer": G1},
          "Three-character asset code drops its single padding byte. AssetCode4 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum4", "XdrAssetAlphaNum4", {"asset_code": "ABCD", "issuer": G1},
          "Four-character asset code fills the field exactly. AssetCode4 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum4", "XdrAssetAlphaNum4",
          {"asset_code": "\\xc3", "issuer": G1},
          "Asset code holding a non-ASCII byte escapes it as \\xNN. AssetCode4 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum4", "XdrAssetAlphaNum4",
          {"asset_code": "a\\\\b", "issuer": G1},
          "Backslash inside a four-byte asset code doubles. AssetCode4 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum12", "XdrAssetAlphaNum12",
          {"asset_code": "ABC", "issuer": G1},
          "Three-character twelve-byte asset code pads back to five bytes. AssetCode12 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum12", "XdrAssetAlphaNum12",
          {"asset_code": "ABCDE", "issuer": G1},
          "Five-character asset code sits at the twelve-byte floor. AssetCode12 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum12", "XdrAssetAlphaNum12",
          {"asset_code": "ABCDEFGH", "issuer": G1},
          "Eight-character twelve-byte asset code drops four padding bytes. AssetCode12 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum12", "XdrAssetAlphaNum12",
          {"asset_code": "ABCDEFGHIJKL", "issuer": G1},
          "Twelve-character asset code fills the field exactly. AssetCode12 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum12", "XdrAssetAlphaNum12",
          {"asset_code": "\\0\\0\\0\\0\\0", "issuer": G1},
          "All-NUL twelve-byte asset code renders as five escaped NULs. AssetCode12 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum12", "XdrAssetAlphaNum12",
          {"asset_code": "hello\\xc3world", "issuer": G1},
          "Twelve-byte asset code holding a non-ASCII byte escapes it as \\xNN. AssetCode12 has no Dart class of its own, so its rendering is pinned here."),
    _seed("AlphaNum12", "XdrAssetAlphaNum12",
          {"asset_code": "tab\\there", "issuer": G1},
          "Tab inside a twelve-byte asset code takes its short escape. AssetCode12 has no Dart class of its own, so its rendering is pinned here."),

    # --- Asset, TrustLineAsset, ChangeTrustAsset ----------------------------
    _seed("Asset", "XdrAsset", "native",
          "Native arm renders as a bare name."),
    _seed("Asset", "XdrAsset", ASSET_A4,
          "AlphaNum4 arm nests the code and issuer."),
    _seed("Asset", "XdrAsset", ASSET_A12,
          "AlphaNum12 arm nests the code and issuer."),
    _seed("TrustLineAsset", "XdrTrustlineAsset", "native",
          "Native arm of the trustline asset union renders as a bare name."),
    _seed("TrustLineAsset", "XdrTrustlineAsset", ASSET_A4,
          "AlphaNum4 arm of the trustline asset union."),
    _seed("TrustLineAsset", "XdrTrustlineAsset", ASSET_A12,
          "AlphaNum12 arm of the trustline asset union."),
    _seed("TrustLineAsset", "XdrTrustlineAsset", {"pool_share": L1},
          "Pool share arm of the trustline asset union carries a pool id."),
    _seed("ChangeTrustAsset", "XdrChangeTrustAsset", "native",
          "Native arm of the change trust asset union renders as a bare name."),
    _seed("ChangeTrustAsset", "XdrChangeTrustAsset", ASSET_A4,
          "AlphaNum4 arm of the change trust asset union."),
    _seed("ChangeTrustAsset", "XdrChangeTrustAsset", ASSET_A12,
          "AlphaNum12 arm of the change trust asset union."),
    _seed("ChangeTrustAsset", "XdrChangeTrustAsset",
          {"pool_share": {"liquidity_pool_constant_product": {
              "asset_a": "native", "asset_b": ASSET_A4, "fee": 30}}},
          "Pool share arm of the change trust asset union carries pool parameters."),
    _seed("LiquidityPoolParameters", "XdrLiquidityPoolParameters",
          {"liquidity_pool_constant_product": {
              "asset_a": "native", "asset_b": ASSET_A12, "fee": 30}},
          "Sole arm of the liquidity pool parameters union."),

    # --- 128- and 256-bit integer parts render as decimal strings ----------
    _seed("Int128Parts", "XdrInt128Parts", "0",
          "Signed 128-bit zero renders as a decimal string, not an object."),
    _seed("Int128Parts", "XdrInt128Parts", "1",
          "Signed 128-bit one renders as a decimal string."),
    _seed("Int128Parts", "XdrInt128Parts", "-1",
          "Signed 128-bit minus one crosses both halves of the struct."),
    _seed("Int128Parts", "XdrInt128Parts", INT128_MIN,
          "Signed 128-bit minimum renders as a decimal string."),
    _seed("Int128Parts", "XdrInt128Parts", INT128_MAX,
          "Signed 128-bit maximum renders as a decimal string."),
    _seed("UInt128Parts", "XdrUInt128Parts", "0",
          "Unsigned 128-bit zero renders as a decimal string."),
    _seed("UInt128Parts", "XdrUInt128Parts", "1",
          "Unsigned 128-bit one renders as a decimal string."),
    _seed("UInt128Parts", "XdrUInt128Parts", UINT128_MAX,
          "Unsigned 128-bit maximum renders as a decimal string."),
    _seed("Int256Parts", "XdrInt256Parts", "0",
          "Signed 256-bit zero renders as a decimal string."),
    _seed("Int256Parts", "XdrInt256Parts", "1",
          "Signed 256-bit one renders as a decimal string."),
    _seed("Int256Parts", "XdrInt256Parts", "-1",
          "Signed 256-bit minus one crosses all four quarters of the struct."),
    _seed("Int256Parts", "XdrInt256Parts", INT256_MIN,
          "Signed 256-bit minimum renders as a decimal string."),
    _seed("Int256Parts", "XdrInt256Parts", INT256_MAX,
          "Signed 256-bit maximum renders as a decimal string."),
    _seed("UInt256Parts", "XdrUInt256Parts", "0",
          "Unsigned 256-bit zero renders as a decimal string."),
    _seed("UInt256Parts", "XdrUInt256Parts", "1",
          "Unsigned 256-bit one renders as a decimal string."),
    _seed("UInt256Parts", "XdrUInt256Parts", UINT256_MAX,
          "Unsigned 256-bit maximum renders as a decimal string."),

    # --- 64-bit values inside structs render as strings ---------------------
    _seed("TimeBounds", "XdrTimeBounds", {"min_time": "0", "max_time": "0"},
          "Time bounds at zero render both endpoints as strings."),
    _seed("TimeBounds", "XdrTimeBounds",
          {"min_time": "1", "max_time": UINT64_MAX},
          "Time bounds at the unsigned 64-bit maximum stay strings."),
    _seed("Liabilities", "XdrLiabilities", {"buying": "0", "selling": "0"},
          "Liabilities at zero render as strings."),
    _seed("Liabilities", "XdrLiabilities",
          {"buying": INT64_MAX, "selling": INT64_MIN},
          "Liabilities at both signed 64-bit extremes stay strings."),
    _seed("SequenceNumber", "XdrSequenceNumber", "0",
          "Sequence number zero renders as a string."),
    _seed("SequenceNumber", "XdrSequenceNumber", INT64_MAX,
          "Sequence number at the signed 64-bit maximum renders as a string."),
    _seed("SequenceNumber", "XdrSequenceNumber", INT64_MIN,
          "Sequence number at the signed 64-bit minimum renders as a string."),
    _seed("TimePoint", "XdrUint64", "0",
          "Time point zero renders as a string."),
    _seed("TimePoint", "XdrUint64", UINT64_MAX,
          "Time point at the unsigned 64-bit maximum renders as a string."),
    _seed("Duration", "XdrUint64", "0",
          "Duration zero renders as a string."),
    _seed("Duration", "XdrUint64", UINT64_MAX,
          "Duration at the unsigned 64-bit maximum renders as a string."),

    # --- Fixed and variable opaque -----------------------------------------
    _seed("Hash", "XdrHash", HASH1,
          "Fixed 32-byte hash renders as lowercase hex."),
    _seed("Hash", "XdrHash", HASH_ZERO,
          "All-zero hash renders as 64 hex zeros, never as an empty string."),
    _seed("Uint256", "XdrUint256", HASH1,
          "Fixed 32-byte unsigned value renders as lowercase hex."),
    _seed("DataValue", "XdrDataValue", "",
          "Empty variable opaque renders as an empty string."),
    _seed("DataValue", "XdrDataValue", "00",
          "Single zero byte of variable opaque renders as two hex digits."),
    _seed("DataValue", "XdrDataValue", "deadbeef",
          "Variable opaque renders as lowercase hex."),
    _seed("DataValue", "XdrDataValue", "ff" * 64,
          "Variable opaque at its declared 64-byte limit."),

    # --- Memo ---------------------------------------------------------------
    _seed("Memo", "XdrMemo", "none",
          "Void memo arm renders as a bare name."),
    _seed("Memo", "XdrMemo", {"text": "hello"},
          "Text memo arm carries an escaped string."),
    _seed("Memo", "XdrMemo", {"text": ""},
          "Empty text memo arm renders as an empty string."),
    _seed("Memo", "XdrMemo", {"text": "tab\\there"},
          "Text memo arm applies the short escape for tab."),
    _seed("Memo", "XdrMemo", {"id": "0"},
          "Id memo arm renders its 64-bit value as a string."),
    _seed("Memo", "XdrMemo", {"id": UINT64_MAX},
          "Id memo arm at the unsigned 64-bit maximum stays a string."),
    _seed("Memo", "XdrMemo", {"hash": HASH1},
          "Hash memo arm renders as lowercase hex."),
    _seed("Memo", "XdrMemo", {"return": HASH1},
          "Return-hash memo arm keys on the reserved word return."),

    # --- ClaimPredicate, including nesting and the optional arm ------------
    _seed("ClaimPredicate", "XdrClaimPredicate", "unconditional",
          "Unconditional predicate arm renders as a bare name."),
    _seed("ClaimPredicate", "XdrClaimPredicate", {"and": []},
          "And predicate arm with an empty array."),
    _seed("ClaimPredicate", "XdrClaimPredicate",
          {"and": ["unconditional", {"before_relative_time": "60"}]},
          "And predicate arm at its two-element limit."),
    _seed("ClaimPredicate", "XdrClaimPredicate",
          {"or": ["unconditional", "unconditional"]},
          "Or predicate arm at its two-element limit."),
    _seed("ClaimPredicate", "XdrClaimPredicate", {"not": None},
          "Not predicate arm with the optional unset renders as null."),
    _seed("ClaimPredicate", "XdrClaimPredicate", {"not": "unconditional"},
          "Not predicate arm with the optional set nests a predicate."),
    _seed("ClaimPredicate", "XdrClaimPredicate", {"before_absolute_time": "0"},
          "Absolute time predicate renders its 64-bit bound as a string."),
    _seed("ClaimPredicate", "XdrClaimPredicate",
          {"before_relative_time": INT64_MAX},
          "Relative time predicate at the signed 64-bit maximum."),
    _seed("Claimant", "XdrClaimant",
          {"claimant_type_v0": {"destination": G1, "predicate": "unconditional"}},
          "Sole claimant arm keys on its enum member name."),

    # --- LedgerKey: every arm ----------------------------------------------
    _seed("LedgerKey", "XdrLedgerKey", {"account": {"account_id": G1}},
          "Account ledger key arm."),
    _seed("LedgerKey", "XdrLedgerKey",
          {"trustline": {"account_id": G1, "asset": "native"}},
          "Trustline ledger key arm keys on the stripped member name."),
    _seed("LedgerKey", "XdrLedgerKey",
          {"trustline": {"account_id": G1, "asset": {"pool_share": L1}}},
          "Trustline ledger key arm holding a pool share asset."),
    _seed("LedgerKey", "XdrLedgerKey",
          {"offer": {"seller_id": G1, "offer_id": "12"}},
          "Offer ledger key arm renders its offer id as a string."),
    _seed("LedgerKey", "XdrLedgerKey",
          {"data": {"account_id": G1, "data_name": "config"}},
          "Data ledger key arm carries an escaped string name."),
    _seed("LedgerKey", "XdrLedgerKey", {"claimable_balance": {"balance_id": B1}},
          "Claimable balance ledger key arm."),
    _seed("LedgerKey", "XdrLedgerKey", {"liquidity_pool": {"liquidity_pool_id": L1}},
          "Liquidity pool ledger key arm."),
    _seed("LedgerKey", "XdrLedgerKey",
          {"contract_data": {"contract": C1, "key": "void",
                             "durability": "persistent"}},
          "Contract data ledger key arm with persistent durability."),
    _seed("LedgerKey", "XdrLedgerKey",
          {"contract_data": {"contract": G1, "key": {"symbol": "k"},
                             "durability": "temporary"}},
          "Contract data ledger key arm with temporary durability."),
    _seed("LedgerKey", "XdrLedgerKey", {"contract_code": {"hash": HASH1}},
          "Contract code ledger key arm."),
    _seed("LedgerKey", "XdrLedgerKey",
          {"config_setting": {"config_setting_id": "contract_max_size_bytes"}},
          "Config setting ledger key arm keys on an enum member name."),
    _seed("LedgerKey", "XdrLedgerKey", {"ttl": {"key_hash": HASH1}},
          "TTL ledger key arm keys on the fully stripped member name."),

    # --- ScVal: every arm ---------------------------------------------------
    _seed("ScVal", "XdrSCVal", {"bool": True},
          "Boolean arm renders a JSON boolean."),
    _seed("ScVal", "XdrSCVal", {"bool": False},
          "Boolean arm at false."),
    _seed("ScVal", "XdrSCVal", "void",
          "Void arm renders as a bare name."),
    _seed("ScVal", "XdrSCVal", {"error": {"contract": 7}},
          "Error arm carrying a contract error code."),
    _seed("ScVal", "XdrSCVal", {"error": {"wasm_vm": "internal_error"}},
          "Error arm carrying a host error enum member."),
    _seed("ScVal", "XdrSCVal", {"u32": 0},
          "Unsigned 32-bit arm renders a JSON number."),
    _seed("ScVal", "XdrSCVal", {"u32": 4294967295},
          "Unsigned 32-bit arm at its maximum stays a JSON number."),
    _seed("ScVal", "XdrSCVal", {"i32": -2147483648},
          "Signed 32-bit arm at its minimum stays a JSON number."),
    _seed("ScVal", "XdrSCVal", {"u64": "0"},
          "Unsigned 64-bit arm renders as a string."),
    _seed("ScVal", "XdrSCVal", {"u64": UINT64_MAX},
          "Unsigned 64-bit arm at its maximum renders as a string."),
    _seed("ScVal", "XdrSCVal", {"i64": INT64_MIN},
          "Signed 64-bit arm at its minimum renders as a string."),
    _seed("ScVal", "XdrSCVal", {"i64": INT64_MAX},
          "Signed 64-bit arm at its maximum renders as a string."),
    _seed("ScVal", "XdrSCVal", {"timepoint": "1735689600"},
          "Timepoint arm renders as a string."),
    _seed("ScVal", "XdrSCVal", {"duration": "0"},
          "Duration arm renders as a string."),
    _seed("ScVal", "XdrSCVal", {"u128": UINT128_MAX},
          "Unsigned 128-bit arm at its maximum."),
    _seed("ScVal", "XdrSCVal", {"i128": "-1"},
          "Signed 128-bit arm at minus one."),
    _seed("ScVal", "XdrSCVal", {"i128": INT128_MIN},
          "Signed 128-bit arm at its minimum."),
    _seed("ScVal", "XdrSCVal", {"u256": UINT256_MAX},
          "Unsigned 256-bit arm at its maximum."),
    _seed("ScVal", "XdrSCVal", {"i256": INT256_MIN},
          "Signed 256-bit arm at its minimum."),
    _seed("ScVal", "XdrSCVal", {"bytes": "00ff"},
          "Bytes arm renders as lowercase hex."),
    _seed("ScVal", "XdrSCVal", {"string": ""},
          "String arm with no content."),
    _seed("ScVal", "XdrSCVal", {"string": "a\\\\b"},
          "String arm doubles an embedded backslash."),
    _seed("ScVal", "XdrSCVal", {"symbol": "transfer"},
          "Symbol arm renders as an escaped string."),
    _seed("ScVal", "XdrSCVal", {"vec": None},
          "Vector arm with the optional unset renders as null."),
    _seed("ScVal", "XdrSCVal", {"vec": []},
          "Vector arm with an empty array."),
    _seed("ScVal", "XdrSCVal", {"vec": [{"u32": 1}, "void"]},
          "Vector arm nesting two values."),
    _seed("ScVal", "XdrSCVal", {"map": None},
          "Map arm with the optional unset renders as null."),
    _seed("ScVal", "XdrSCVal", {"map": []},
          "Map arm with an empty array."),
    _seed("ScVal", "XdrSCVal",
          {"map": [{"key": {"symbol": "k"}, "val": {"u32": 1}}]},
          "Map arm with one entry."),
    _seed("ScVal", "XdrSCVal", {"address": G1},
          "Address arm carrying an account address."),
    _seed("ScVal", "XdrSCVal", {"address": C1},
          "Address arm carrying a contract address."),
    _seed("ScVal", "XdrSCVal", "ledger_key_contract_instance",
          "Ledger key contract instance arm renders as a bare name."),
    _seed("ScVal", "XdrSCVal", {"ledger_key_nonce": {"nonce": "5"}},
          "Ledger key nonce arm renders its nonce as a string."),
    _seed("ScVal", "XdrSCVal",
          {"contract_instance": {"executable": "stellar_asset", "storage": None}},
          "Contract instance arm with unset storage."),
    _seed("ScVal", "XdrSCVal",
          {"contract_instance": {"executable": {"wasm": HASH1}, "storage": []}},
          "Contract instance arm with empty storage."),
    _seed("ScVal", "XdrSCVal", {"executable_tag": "tag"},
          "Executable tag arm renders as an escaped string."),

    # --- Soroban value containers -------------------------------------------
    # SCVec, SCMap, SCString and SCSymbol collapse into their containers in this
    # SDK, so each is pinned at a container that renders it: a struct field for
    # SCVec, SCMap and SCSymbol, a union arm for SCString.
    _seed("InvokeContractArgs", "XdrInvokeContractArgs",
          {"contract_address": C1, "function_name": "sym", "args": []},
          "Vector-typed struct field with no elements renders as an empty array. SCVec has no Dart class of its own, so its rendering is pinned here."),
    _seed("InvokeContractArgs", "XdrInvokeContractArgs",
          {"contract_address": C1, "function_name": "sym",
           "args": [{"u32": 1}, {"i32": -1}]},
          "Vector-typed struct field carrying two values. SCVec has no Dart class of its own, so its rendering is pinned here."),
    _seed("InvokeContractArgs", "XdrInvokeContractArgs",
          {"contract_address": C1, "function_name": "a_b9", "args": []},
          "Symbol-typed struct field renders as an escaped string. SCSymbol has no Dart class of its own, so its rendering is pinned here."),
    _seed("ScContractInstance", "XdrSCContractInstance",
          {"executable": "stellar_asset", "storage": []},
          "Map-typed struct field with no entries renders as an empty array. SCMap has no Dart class of its own, so its rendering is pinned here."),
    _seed("ScMapEntry", "XdrSCMapEntry",
          {"key": {"symbol": "k"}, "val": {"bool": True}},
          "Map entry keys its two fields in declaration order."),
    _seed("ScBytes", "XdrSCBytes", "",
          "Empty bytes typedef renders as an empty string."),
    _seed("ScBytes", "XdrSCBytes", "0a0b0c",
          "Bytes typedef renders as lowercase hex."),
    _seed("ScVal", "XdrSCVal", {"string": "hello"},
          "String-typed union arm renders as an escaped string. SCString has no Dart class of its own, so its rendering is pinned here."),
    _seed("ScNonceKey", "XdrSCNonceKey", {"nonce": INT64_MIN},
          "Nonce key renders its 64-bit field as a string."),
    _seed("ScContractInstance", "XdrSCContractInstance",
          {"executable": "stellar_asset",
           "storage": [{"key": {"symbol": "k"}, "val": "void"}]},
          "Contract instance with populated storage."),

    # --- SCError: every arm -------------------------------------------------
    _seed("ScError", "XdrSCError", {"contract": 0},
          "Contract error arm carries a bare 32-bit code."),
    _seed("ScError", "XdrSCError", {"contract": 4294967295},
          "Contract error arm at the unsigned 32-bit maximum."),
    _seed("ScError", "XdrSCError", {"wasm_vm": "arith_domain"},
          "WASM VM error arm keyed on an error code member."),
    _seed("ScError", "XdrSCError", {"context": "index_bounds"},
          "Context error arm."),
    _seed("ScError", "XdrSCError", {"storage": "invalid_input"},
          "Storage error arm."),
    _seed("ScError", "XdrSCError", {"object": "missing_value"},
          "Object error arm."),
    _seed("ScError", "XdrSCError", {"crypto": "existing_value"},
          "Crypto error arm."),
    _seed("ScError", "XdrSCError", {"events": "exceeded_limit"},
          "Events error arm."),
    _seed("ScError", "XdrSCError", {"budget": "invalid_action"},
          "Budget error arm."),
    _seed("ScError", "XdrSCError", {"value": "internal_error"},
          "Value error arm."),
    _seed("ScError", "XdrSCError", {"auth": "unexpected_type"},
          "Auth error arm."),

    # --- Operations ---------------------------------------------------------
    _seed("Operation", "XdrOperation",
          {"source_account": None,
           "body": {"create_account": {"destination": G1,
                                       "starting_balance": "100"}}},
          "Operation with the optional source account unset."),
    _seed("Operation", "XdrOperation",
          {"source_account": G1,
           "body": {"payment": {"destination": G1, "asset": "native",
                                "amount": "1"}}},
          "Operation with the optional source account set."),
    _seed("Operation", "XdrOperation",
          {"source_account": M1, "body": "inflation"},
          "Operation whose source account is muxed and whose body is void."),
    _seed("OperationBody", "XdrOperationBody",
          {"create_account": {"destination": G1, "starting_balance": "1"}},
          "Create account body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"payment": {"destination": M1, "asset": ASSET_A4, "amount": INT64_MAX}},
          "Payment body arm at the signed 64-bit maximum amount."),
    _seed("OperationBody", "XdrOperationBody",
          {"path_payment_strict_receive": {
              "send_asset": "native", "send_max": "10", "destination": G1,
              "dest_asset": ASSET_A4, "dest_amount": "5", "path": []}},
          "Path payment strict receive body arm with an empty path."),
    _seed("OperationBody", "XdrOperationBody",
          {"path_payment_strict_send": {
              "send_asset": ASSET_A12, "send_amount": "10", "destination": G1,
              "dest_asset": "native", "dest_min": "5",
              "path": ["native", ASSET_A4]}},
          "Path payment strict send body arm with a two-element path."),
    _seed("OperationBody", "XdrOperationBody",
          {"manage_sell_offer": {"selling": "native", "buying": ASSET_A4,
                                 "amount": "1", "price": {"n": 1, "d": 2},
                                 "offer_id": "0"}},
          "Manage sell offer body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"manage_buy_offer": {"selling": ASSET_A4, "buying": "native",
                                "buy_amount": "1", "price": {"n": 7, "d": 3},
                                "offer_id": "9"}},
          "Manage buy offer body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"create_passive_sell_offer": {"selling": "native", "buying": ASSET_A4,
                                         "amount": "1", "price": {"n": 1, "d": 1}}},
          "Create passive sell offer body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"set_options": {"inflation_dest": G1, "clear_flags": 1,
                           "set_flags": 2, "master_weight": 255,
                           "low_threshold": 0, "med_threshold": 1,
                           "high_threshold": 2, "home_domain": "example.com",
                           "signer": {"key": X1, "weight": 3}}},
          "Set options body arm with every optional set."),
    _seed("OperationBody", "XdrOperationBody",
          {"change_trust": {"line": ASSET_A4, "limit": INT64_MAX}},
          "Change trust body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"allow_trust": {"trustor": G1, "asset": "USD", "authorize": 1}},
          "Allow trust body arm carries an asset code union as a string."),
    _seed("OperationBody", "XdrOperationBody", {"account_merge": M1},
          "Account merge body arm carries a muxed account directly."),
    _seed("OperationBody", "XdrOperationBody", "inflation",
          "Inflation body arm renders as a bare name."),
    _seed("OperationBody", "XdrOperationBody",
          {"manage_data": {"data_name": "k", "data_value": None}},
          "Manage data body arm with the optional value unset."),
    _seed("OperationBody", "XdrOperationBody", {"bump_sequence": {"bump_to": "9"}},
          "Bump sequence body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"create_claimable_balance": {
              "asset": "native", "amount": "1",
              "claimants": [{"claimant_type_v0": {
                  "destination": G1, "predicate": "unconditional"}}]}},
          "Create claimable balance body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"claim_claimable_balance": {"balance_id": B1}},
          "Claim claimable balance body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"begin_sponsoring_future_reserves": {"sponsored_id": G1}},
          "Begin sponsoring future reserves body arm."),
    _seed("OperationBody", "XdrOperationBody", "end_sponsoring_future_reserves",
          "End sponsoring future reserves body arm renders as a bare name."),
    _seed("OperationBody", "XdrOperationBody",
          {"revoke_sponsorship": {"ledger_entry": {"account": {"account_id": G1}}}},
          "Revoke sponsorship body arm targeting a ledger entry."),
    _seed("OperationBody", "XdrOperationBody",
          {"revoke_sponsorship": {"signer": {"account_id": G1, "signer_key": T1}}},
          "Revoke sponsorship body arm targeting a signer."),
    _seed("OperationBody", "XdrOperationBody",
          {"clawback": {"asset": ASSET_A4, "from": M1, "amount": "1"}},
          "Clawback body arm keys on the reserved word from."),
    _seed("OperationBody", "XdrOperationBody",
          {"clawback_claimable_balance": {"balance_id": B1}},
          "Clawback claimable balance body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"set_trust_line_flags": {"trustor": G1, "asset": ASSET_A4,
                                    "clear_flags": 1, "set_flags": 2}},
          "Set trustline flags body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"liquidity_pool_deposit": {"liquidity_pool_id": L1, "max_amount_a": "1",
                                      "max_amount_b": "2",
                                      "min_price": {"n": 1, "d": 2},
                                      "max_price": {"n": 3, "d": 1}}},
          "Liquidity pool deposit body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"liquidity_pool_withdraw": {"liquidity_pool_id": L1, "amount": "1",
                                       "min_amount_a": "0", "min_amount_b": "0"}},
          "Liquidity pool withdraw body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"invoke_host_function": {
              "host_function": {"upload_contract_wasm": "0061736d"},
              "auth": []}},
          "Invoke host function body arm with no authorization entries."),
    _seed("OperationBody", "XdrOperationBody",
          {"extend_footprint_ttl": {"ext": "v0", "extend_to": 100}},
          "Extend footprint TTL body arm."),
    _seed("OperationBody", "XdrOperationBody",
          {"restore_footprint": {"ext": "v0"}},
          "Restore footprint body arm."),

    # --- Operation payloads that pin the escape ladder ---------------------
    _seed("ManageDataOp", "XdrManageDataOp",
          {"data_name": "plain-name_1", "data_value": "0102"},
          "Printable ASCII name survives the escape ladder unchanged."),
    _seed("ManageDataOp", "XdrManageDataOp",
          {"data_name": "a\\\\b", "data_value": None},
          "Backslash in a string field doubles."),
    _seed("ManageDataOp", "XdrManageDataOp",
          {"data_name": "a\\tb", "data_value": ""},
          "Tab in a string field takes its short escape."),
    _seed("ManageDataOp", "XdrManageDataOp",
          {"data_name": "a\\0b", "data_value": None},
          "NUL in a string field takes its short escape."),
    _seed("ManageDataOp", "XdrManageDataOp",
          {"data_name": "a\\x7fb", "data_value": None},
          "DEL in a string field escapes as \\x7f."),
    _seed("ManageDataOp", "XdrManageDataOp",
          {"data_name": "a\\nb\\rc", "data_value": None},
          "Newline and carriage return take their short escapes."),
    _seed("ManageDataOp", "XdrManageDataOp",
          {"data_name": " ~", "data_value": None},
          "Both ends of the printable range survive unescaped."),
    _seed("SetOptionsOp", "XdrSetOptionsOp",
          {"inflation_dest": None, "clear_flags": None, "set_flags": None,
           "master_weight": None, "low_threshold": None, "med_threshold": None,
           "high_threshold": None, "home_domain": None, "signer": None},
          "Every optional field unset renders as null."),
    _seed("SetOptionsOp", "XdrSetOptionsOp",
          {"inflation_dest": G1, "clear_flags": 0, "set_flags": 0,
           "master_weight": 0, "low_threshold": 0, "med_threshold": 0,
           "high_threshold": 0, "home_domain": "a\\\\b",
           "signer": {"key": P_SHORT, "weight": 255}},
          "Every optional field set, including an escaped home domain."),

    # --- Transaction envelopes and results ---------------------------------
    _seed("TransactionEnvelope", "XdrTransactionEnvelope",
          {"tx_v0": {"tx": {"source_account_ed25519": HASH1, "fee": 100,
                            "seq_num": "1", "time_bounds": None, "memo": "none",
                            "operations": [], "ext": "v0"},
                     "signatures": []}},
          "Version 0 transaction envelope arm."),
    _seed("TransactionEnvelope", "XdrTransactionEnvelope",
          {"tx": {"tx": {"source_account": G1, "fee": 100, "seq_num": "1",
                         "cond": "none", "memo": "none",
                         "operations": [{"source_account": None,
                                         "body": "inflation"}],
                         "ext": "v0"},
                  "signatures": [{"hint": "01020304", "signature": "0a0b"}]}},
          "Version 1 transaction envelope arm with one signature."),
    _seed("TransactionEnvelope", "XdrTransactionEnvelope",
          {"tx_fee_bump": {"tx": {"fee_source": M1, "fee": "200",
                                  "inner_tx": {"tx": {
                                      "tx": {"source_account": G1, "fee": 100,
                                             "seq_num": "1", "cond": "none",
                                             "memo": "none", "operations": [],
                                             "ext": "v0"},
                                      "signatures": []}},
                                  "ext": "v0"},
                           "signatures": []}},
          "Fee bump transaction envelope arm wrapping a version 1 envelope."),
    _seed("Preconditions", "XdrPreconditions", "none",
          "Void preconditions arm renders as a bare name."),
    _seed("Preconditions", "XdrPreconditions",
          {"time": {"min_time": "0", "max_time": "100"}},
          "Time preconditions arm."),
    _seed("Preconditions", "XdrPreconditions",
          {"v2": {"time_bounds": None, "ledger_bounds": None, "min_seq_num": None,
                  "min_seq_age": "0", "min_seq_ledger_gap": 0,
                  "extra_signers": []}},
          "Version 2 preconditions arm with every optional unset."),
    _seed("PreconditionsV2", "XdrPreconditionsV2",
          {"time_bounds": {"min_time": "1", "max_time": "2"},
           "ledger_bounds": {"min_ledger": 1, "max_ledger": 2},
           "min_seq_num": "7", "min_seq_age": "3", "min_seq_ledger_gap": 4,
           "extra_signers": [T1, X1]},
          "Version 2 preconditions with every optional set and two extra signers."),
    _seed("LedgerBounds", "XdrLedgerBounds", {"min_ledger": 0, "max_ledger": 4294967295},
          "Ledger bounds render both 32-bit endpoints as numbers."),
    _seed("TransactionResult", "XdrTransactionResult",
          {"fee_charged": "100",
           "result": {"tx_success": [{"op_inner": {"payment": "success"}}]},
           "ext": "v0"},
          "Successful transaction result nesting an inner operation result."),
    _seed("TransactionResult", "XdrTransactionResult",
          {"fee_charged": "0", "result": {"tx_failed": []}, "ext": "v0"},
          "Failed transaction result with an empty operation result array."),
    _seed("TransactionResult", "XdrTransactionResult",
          {"fee_charged": INT64_MAX,
           "result": {"tx_fee_bump_inner_success": {
               "transaction_hash": HASH1,
               "result": {"fee_charged": "1",
                          "result": {"tx_success": []},
                          "ext": "v0"}}},
           "ext": "v0"},
          "Fee bump inner success result nests a full inner result."),
    _seed("OperationResult", "XdrOperationResult", "op_bad_auth",
          "Operation result arm that carries nothing renders as a bare name."),
    _seed("OperationResult", "XdrOperationResult",
          {"op_inner": {"create_account": "success"}},
          "Inner operation result nests the per-operation union."),
    _seed("OperationResult", "XdrOperationResult",
          {"op_inner": {"payment": "malformed"}},
          "Inner operation result carrying a failure code."),
    _seed("OperationResult", "XdrOperationResult",
          {"op_inner": {"manage_sell_offer": {"success": {
              "offers_claimed": [], "offer": "deleted"}}}},
          "Inner operation result nesting a success payload."),
    _seed("OperationResult", "XdrOperationResult",
          {"op_inner": {"inflation": {"success": []}}},
          "Inner inflation result with an empty payout array."),

    # --- Ledger entries -----------------------------------------------------
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"account": {"account_id": G1, "balance": "10", "seq_num": "1",
                       "num_sub_entries": 0, "inflation_dest": None, "flags": 0,
                       "home_domain": "", "thresholds": "01000000", "signers": [],
                       "ext": "v0"}},
          "Account ledger entry arm with no signers."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"account": {"account_id": G1, "balance": "10", "seq_num": "1",
                       "num_sub_entries": 1, "inflation_dest": G1, "flags": 1,
                       "home_domain": "example.com", "thresholds": "01020304",
                       "signers": [{"key": G1, "weight": 1}],
                       "ext": {"v1": {"liabilities": {"buying": "1",
                                                      "selling": "2"},
                                      "ext": "v0"}}}},
          "Account ledger entry arm with an extension and one signer."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"trustline": {"account_id": G1, "asset": ASSET_A4, "balance": "5",
                         "limit": INT64_MAX, "flags": 1, "ext": "v0"}},
          "Trustline ledger entry arm."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"offer": {"seller_id": G1, "offer_id": "1", "selling": "native",
                     "buying": ASSET_A4, "amount": "1",
                     "price": {"n": 1, "d": 2}, "flags": 0, "ext": "v0"}},
          "Offer ledger entry arm."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"data": {"account_id": G1, "data_name": "k", "data_value": "",
                    "ext": "v0"}},
          "Data ledger entry arm with an empty value."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"claimable_balance": {"balance_id": B1, "claimants": [], "asset": "native",
                                 "amount": "1", "ext": "v0"}},
          "Claimable balance ledger entry arm."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"liquidity_pool": {"liquidity_pool_id": L1, "body": {
              "liquidity_pool_constant_product": {
                  "params": {"asset_a": "native", "asset_b": ASSET_A4, "fee": 30},
                  "reserve_a": "1", "reserve_b": "2", "total_pool_shares": "3",
                  "pool_shares_trust_line_count": "4"}}}},
          "Liquidity pool ledger entry arm."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"contract_data": {"ext": "v0", "contract": C1, "key": "void",
                             "durability": "persistent", "val": {"u32": 1}}},
          "Contract data ledger entry arm."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"contract_code": {"ext": "v0", "hash": HASH1, "code": "0061736d"}},
          "Contract code ledger entry arm."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"config_setting": {"contract_max_size_bytes": 100}},
          "Config setting ledger entry arm."),
    _seed("LedgerEntryData", "XdrLedgerEntryData",
          {"ttl": {"key_hash": HASH1, "live_until_ledger_seq": 7}},
          "TTL ledger entry arm."),
    _seed("LedgerEntry", "XdrLedgerEntry",
          {"last_modified_ledger_seq": 1,
           "data": {"ttl": {"key_hash": HASH1, "live_until_ledger_seq": 7}},
           "ext": "v0"},
          "Ledger entry wrapping a TTL entry with a void extension."),
    _seed("LedgerEntry", "XdrLedgerEntry",
          {"last_modified_ledger_seq": 4294967295,
           "data": {"ttl": {"key_hash": HASH_ZERO, "live_until_ledger_seq": 0}},
           "ext": {"v1": {"sponsoring_id": G1, "ext": "v0"}}},
          "Ledger entry with a populated extension."),
    _seed("LedgerEntryChange", "XdrLedgerEntryChange",
          {"created": {"last_modified_ledger_seq": 1,
                       "data": {"ttl": {"key_hash": HASH1,
                                        "live_until_ledger_seq": 7}},
                       "ext": "v0"}},
          "Created ledger entry change arm."),
    _seed("LedgerEntryChange", "XdrLedgerEntryChange",
          {"updated": {"last_modified_ledger_seq": 2,
                       "data": {"ttl": {"key_hash": HASH1,
                                        "live_until_ledger_seq": 8}},
                       "ext": "v0"}},
          "Updated ledger entry change arm."),
    _seed("LedgerEntryChange", "XdrLedgerEntryChange",
          {"removed": {"contract_code": {"hash": HASH1}}},
          "Removed ledger entry change arm carries a key, not an entry."),
    _seed("LedgerEntryChange", "XdrLedgerEntryChange",
          {"state": {"last_modified_ledger_seq": 3,
                     "data": {"ttl": {"key_hash": HASH1,
                                      "live_until_ledger_seq": 9}},
                     "ext": "v0"}},
          "State ledger entry change arm."),
    _seed("LedgerEntryChange", "XdrLedgerEntryChange",
          {"restored": {"last_modified_ledger_seq": 4,
                        "data": {"ttl": {"key_hash": HASH1,
                                         "live_until_ledger_seq": 10}},
                        "ext": "v0"}},
          "Restored ledger entry change arm."),
    _seed("LedgerEntryChanges", "XdrLedgerEntryChanges", [],
          "Empty change list renders as an empty array."),
    _seed("LedgerEntryChanges", "XdrLedgerEntryChanges",
          [{"state": {"last_modified_ledger_seq": 3,
                      "data": {"ttl": {"key_hash": HASH1,
                                       "live_until_ledger_seq": 9}},
                      "ext": "v0"}},
           {"updated": {"last_modified_ledger_seq": 4,
                        "data": {"ttl": {"key_hash": HASH1,
                                         "live_until_ledger_seq": 10}},
                        "ext": "v0"}},
           {"removed": {"contract_code": {"hash": HASH1}}}],
          "Populated change list keeps its elements in order and renders each "
          "as its own arm."),
    _seed("LedgerFootprint", "XdrLedgerFootprint",
          {"read_only": [], "read_write": []},
          "Footprint with both arrays empty."),
    _seed("LedgerFootprint", "XdrLedgerFootprint",
          {"read_only": [{"contract_code": {"hash": HASH1}}],
           "read_write": [{"ttl": {"key_hash": HASH_ZERO}}]},
          "Footprint with both arrays populated."),
    _seed("LedgerHeader", "XdrLedgerHeader",
          {"ledger_version": 23, "previous_ledger_hash": HASH1,
           "scp_value": {"tx_set_hash": HASH1, "close_time": "0",
                         "upgrades": [], "ext": "basic"},
           "tx_set_result_hash": HASH1, "bucket_list_hash": HASH1,
           "ledger_seq": 2, "total_coins": "1", "fee_pool": "0", "inflation_seq": 0,
           "id_pool": "0", "base_fee": 100, "base_reserve": 5000000,
           "max_tx_set_size": 100,
           "skip_list": [HASH1, HASH_ZERO, HASH1, HASH_ZERO], "ext": "v0"},
          "Ledger header renders its four-element fixed array of hashes."),

    # --- Soroban authorization ---------------------------------------------
    _seed("SorobanCredentials", "XdrSorobanCredentials", "source_account",
          "Source account credentials arm renders as a bare name."),
    _seed("SorobanCredentials", "XdrSorobanCredentials",
          {"address": {"address": C1, "nonce": "1",
                       "signature_expiration_ledger": 100, "signature": "void"}},
          "Address credentials arm."),
    _seed("SorobanAuthorizedInvocation", "XdrSorobanAuthorizedInvocation",
          {"function": {"contract_fn": {"contract_address": C1,
                                        "function_name": "transfer",
                                        "args": [{"u32": 1}]}},
           "sub_invocations": []},
          "Authorized invocation with no sub-invocations."),
    _seed("SorobanAuthorizationEntry", "XdrSorobanAuthorizationEntry",
          {"credentials": "source_account",
           "root_invocation": {
               "function": {"contract_fn": {"contract_address": C1,
                                            "function_name": "hello",
                                            "args": []}},
               "sub_invocations": []}},
          "Authorization entry with source account credentials."),
    _seed("SorobanAuthorizationEntry", "XdrSorobanAuthorizationEntry",
          {"credentials": {"address": {"address": G1, "nonce": INT64_MAX,
                                       "signature_expiration_ledger": 0,
                                       "signature": {"vec": []}}},
           "root_invocation": {
               "function": {"create_contract_host_fn": {
                   "contract_id_preimage": {"asset": "native"},
                   "executable": "stellar_asset"}},
               "sub_invocations": []}},
          "Authorization entry with address credentials and a create-contract root."),
    _seed("SorobanAuthorizationEntry", "XdrSorobanAuthorizationEntry",
          {"credentials": "source_account",
           "root_invocation": {
               "function": {"contract_fn": {"contract_address": C1,
                                            "function_name": "outer",
                                            "args": []}},
               "sub_invocations": [{
                   "function": {"contract_fn": {"contract_address": C1,
                                                "function_name": "inner",
                                                "args": []}},
                   "sub_invocations": []}]}},
          "Authorization entry with one level of sub-invocation nesting."),
    _seed("ContractIdPreimage", "XdrContractIDPreimage",
          {"address": {"address": C1, "salt": HASH1}},
          "Address contract id preimage arm."),
    _seed("ContractIdPreimage", "XdrContractIDPreimage", {"asset": ASSET_A4},
          "Asset contract id preimage arm."),
    _seed("ContractExecutable", "XdrContractExecutable", "stellar_asset",
          "Stellar asset executable arm renders as a bare name."),
    _seed("ContractExecutable", "XdrContractExecutable", {"wasm": HASH1},
          "WASM executable arm keys on the stripped member name."),
    _seed("ContractExecutable", "XdrContractExecutable",
          {"external_ref": {"executable_owner": C1, "tag": "ref"}},
          "External reference executable arm."),
    _seed("HostFunction", "XdrHostFunction",
          {"invoke_contract": {"contract_address": C1, "function_name": "hello",
                               "args": []}},
          "Invoke contract host function arm."),
    _seed("HostFunction", "XdrHostFunction",
          {"create_contract": {"contract_id_preimage": {"asset": "native"},
                               "executable": "stellar_asset"}},
          "Create contract host function arm."),
    _seed("HostFunction", "XdrHostFunction", {"upload_contract_wasm": ""},
          "Upload WASM host function arm with empty variable opaque."),
    _seed("HostFunction", "XdrHostFunction", {"upload_contract_wasm": "0061736d"},
          "Upload WASM host function arm with data."),
    _seed("HostFunction", "XdrHostFunction",
          {"create_contract_v2": {
              "contract_id_preimage": {"address": {"address": C1, "salt": HASH1}},
              "executable": {"wasm": HASH1},
              "constructor_args": [{"u32": 1}]}},
          "Create contract v2 host function arm with constructor arguments."),
    _seed("InvokeContractArgs", "XdrInvokeContractArgs",
          {"contract_address": C1, "function_name": "f", "args": []},
          "Invoke contract arguments with an empty argument array."),

    # --- Contract events and the six fields named type ---------------------
    _seed("ContractEvent", "XdrContractEvent",
          {"ext": "v0", "contract_id": None, "type": "system",
           "body": {"v0": {"topics": [], "data": "void"}}},
          "Contract event renders its discriminant field under the key type."),
    _seed("ContractEvent", "XdrContractEvent",
          {"ext": "v0", "contract_id": C1, "type": "contract",
           "body": {"v0": {"topics": [{"symbol": "transfer"}],
                           "data": {"u32": 1}}}},
          "Contract event with a contract id and one topic."),
    _seed("DiagnosticEvent", "XdrDiagnosticEvent",
          {"in_successful_contract_call": True,
           "event": {"ext": "v0", "contract_id": None, "type": "diagnostic",
                     "body": {"v0": {"topics": [], "data": "void"}}}},
          "Diagnostic event wrapping a contract event."),
    _seed("ScSpecEventParamV0", "XdrSCSpecEventParamV0",
          {"doc": "", "name": "p", "type": "u32",
           "location": "data"},
          "Event parameter renders its type field under the key type."),
    _seed("ScSpecFunctionInputV0", "XdrSCSpecFunctionInputV0",
          {"doc": "d", "name": "arg", "type": {"option": {"value_type": "bool"}}},
          "Function input renders its type field under the key type."),
    _seed("ScSpecUdtStructFieldV0", "XdrSCSpecUDTStructFieldV0",
          {"doc": "", "name": "field", "type": "i64"},
          "Struct field renders its type field under the key type."),
    _seed("ScSpecUdtUnionCaseTupleV0", "XdrSCSpecUDTUnionCaseTupleV0",
          {"doc": "", "name": "case", "type": ["u32", "bool"]},
          "Union case tuple renders its type array under the key type."),
    _seed("SerializedBinaryFuseFilter", "XdrSerializedBinaryFuseFilter",
          {"type": "b8_bit",
           "input_hash_seed": {"seed": BYTES_16},
           "filter_seed": {"seed": BYTES_16},
           "segment_length": 1, "segement_length_mask": 2, "segment_count": 3,
           "segment_count_length": 4, "fingerprint_length": 5,
           "fingerprints": "0102"},
          "Serialized filter renders its type field under the key type.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["input_hash_seed.seed", "filter_seed.seed"]),
    _seed("SerializedBinaryFuseFilter", "XdrSerializedBinaryFuseFilter",
          {"type": "b16_bit",
           "input_hash_seed": {"seed": [0] * 16},
           "filter_seed": {"seed": [255] * 16},
           "segment_length": 0, "segement_length_mask": 0, "segment_count": 0,
           "segment_count_length": 0, "fingerprint_length": 0,
           "fingerprints": ""},
          "Serialized filter with empty fingerprints and extreme seeds.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["input_hash_seed.seed", "filter_seed.seed"]),
    _seed("SerializedBinaryFuseFilter", "XdrSerializedBinaryFuseFilter",
          {"type": "b32_bit",
           "input_hash_seed": {"seed": BYTES_16},
           "filter_seed": {"seed": BYTES_16},
           "segment_length": 4294967295, "segement_length_mask": 4294967295,
           "segment_count": 4294967295, "segment_count_length": 4294967295,
           "fingerprint_length": 4294967295, "fingerprints": "ffff"},
          "Serialized filter at the 32-bit maximum in every counter.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["input_hash_seed.seed", "filter_seed.seed"]),
    _seed("BinaryFuseFilterType", "XdrBinaryFuseFilterType", "b8_bit",
          "Digit-leading enum member is prefixed with b."),
    _seed("BinaryFuseFilterType", "XdrBinaryFuseFilterType", "b16_bit",
          "Digit-leading enum member is prefixed with b."),
    _seed("BinaryFuseFilterType", "XdrBinaryFuseFilterType", "b32_bit",
          "Digit-leading enum member is prefixed with b."),

    # --- Contract specification --------------------------------------------
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", "val",
          "Val type renders as a bare name."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", "bool",
          "Bool type renders as a bare name."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", "u32",
          "Unsigned 32-bit type renders as a bare name."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", "i128",
          "Signed 128-bit type renders as a bare name."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", "address",
          "Address type renders as a bare name."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", "muxed_address",
          "Muxed address type renders as a bare name."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", {"option": {"value_type": "u32"}},
          "Option type nests its value type."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef",
          {"result": {"ok_type": "u32", "error_type": "error"}},
          "Result type nests both of its types."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", {"vec": {"element_type": "bool"}},
          "Vec type nests its element type."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef",
          {"map": {"key_type": "symbol", "value_type": "u64"}},
          "Map type nests both of its types."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", {"tuple": {"value_types": []}},
          "Tuple type with an empty value type array."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef",
          {"tuple": {"value_types": ["u32", "bool"]}},
          "Tuple type with two value types."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", {"bytes_n": {"n": 32}},
          "Fixed-length bytes type carries its length."),
    _seed("ScSpecTypeDef", "XdrSCSpecTypeDef", {"udt": {"name": "Account"}},
          "User-defined type carries its name."),
    _seed("ScSpecEntry", "XdrSCSpecEntry",
          {"function_v0": {"doc": "", "name": "hello", "inputs": [],
                           "outputs": []}},
          "Function spec entry arm with no inputs or outputs."),
    _seed("ScSpecEntry", "XdrSCSpecEntry",
          {"udt_struct_v0": {"doc": "", "lib": "", "name": "S",
                             "fields": [{"doc": "", "name": "f",
                                         "type": "u32"}]}},
          "Struct spec entry arm with one field."),
    _seed("ScSpecEntry", "XdrSCSpecEntry",
          {"udt_union_v0": {"doc": "", "lib": "", "name": "U",
                            "cases": [{"void_v0": {"doc": "", "name": "A"}},
                                      {"tuple_v0": {"doc": "", "name": "B",
                                                    "type": ["u32"]}}]}},
          "Union spec entry arm with both case shapes."),
    _seed("ScSpecEntry", "XdrSCSpecEntry",
          {"udt_enum_v0": {"doc": "", "lib": "", "name": "E",
                           "cases": [{"doc": "", "name": "A", "value": 1}]}},
          "Enum spec entry arm."),
    _seed("ScSpecEntry", "XdrSCSpecEntry",
          {"udt_error_enum_v0": {"doc": "", "lib": "", "name": "Err",
                                 "cases": [{"doc": "", "name": "Bad",
                                            "value": 2}]}},
          "Error enum spec entry arm."),
    _seed("ScSpecUdtUnionCaseV0", "XdrSCSpecUDTUnionCaseV0",
          {"void_v0": {"doc": "", "name": "A"}},
          "Void union case arm."),
    _seed("ScSpecUdtUnionCaseV0", "XdrSCSpecUDTUnionCaseV0",
          {"tuple_v0": {"doc": "", "name": "B", "type": ["bool"]}},
          "Tuple union case arm."),
    _seed("ScSpecFunctionV0", "XdrSCSpecFunctionV0",
          {"doc": "doc", "name": "f",
           "inputs": [{"doc": "", "name": "a", "type": "u32"}],
           "outputs": ["bool"]},
          "Function spec with one input and one output."),
    _seed("ScEnvMetaEntry", "XdrSCEnvMetaEntry",
          {"sc_env_meta_kind_interface_version": {"protocol": 23,
                                                  "pre_release": 0}},
          "Sole environment meta arm keys on the unstripped member name."),
    _seed("ScMetaEntry", "XdrSCMetaEntry", {"sc_meta_v0": {"key": "k", "val": "v"}},
          "Sole contract meta arm keys on the unstripped member name."),

    # --- Extension unions at v0 and beyond ---------------------------------
    _seed("ExtensionPoint", "XdrExtensionPoint", "v0",
          "Extension point at its only arm renders as a bare name."),
    _seed("AccountEntryExt", "XdrAccountEntryExt", "v0",
          "Account extension at v0 renders as a bare name."),
    _seed("AccountEntryExt", "XdrAccountEntryExt",
          {"v1": {"liabilities": {"buying": "1", "selling": "2"}, "ext": "v0"}},
          "Account extension at v1 nests liabilities."),
    _seed("AccountEntryExtensionV1Ext", "XdrAccountEntryV1Ext", "v0",
          "Account v1 extension at v0."),
    _seed("AccountEntryExtensionV1Ext", "XdrAccountEntryV1Ext",
          {"v2": {"num_sponsored": 1, "num_sponsoring": 2,
                  "signer_sponsoring_i_ds": [None, G1], "ext": "v0"}},
          "Account v1 extension at v2 with a mixed optional array."),

    # --- Sponsored signers: an array of optional AccountID -------------------
    # SponsorshipDescriptor is AccountID*, so every element carries a presence
    # flag and an absent element renders as null.
    _seed("AccountEntryExtensionV2", "XdrAccountEntryV2",
          {"num_sponsored": 0, "num_sponsoring": 0,
           "signer_sponsoring_i_ds": [], "ext": "v0"},
          "No sponsored signers renders as an empty array."),
    _seed("AccountEntryExtensionV2", "XdrAccountEntryV2",
          {"num_sponsored": 0, "num_sponsoring": 1,
           "signer_sponsoring_i_ds": [None], "ext": "v0"},
          "A single absent sponsoring id renders as null and writes a "
          "zero presence flag."),
    _seed("AccountEntryExtensionV2", "XdrAccountEntryV2",
          {"num_sponsored": 0, "num_sponsoring": 1,
           "signer_sponsoring_i_ds": [G2], "ext": "v0"},
          "A single present sponsoring id renders as a G strkey behind a "
          "one presence flag."),
    _seed("AccountEntryExtensionV2", "XdrAccountEntryV2",
          {"num_sponsored": 2, "num_sponsoring": 3,
           "signer_sponsoring_i_ds": [G2, None, G3], "ext": "v0"},
          "Present and absent sponsoring ids interleave without shifting."),
    _seed("LedgerEntryExt", "XdrLedgerEntryExt", "v0",
          "Ledger entry extension at v0."),
    _seed("LedgerEntryExt", "XdrLedgerEntryExt",
          {"v1": {"sponsoring_id": None, "ext": "v0"}},
          "Ledger entry extension at v1 with the sponsoring id unset."),
    _seed("TrustLineEntryExt", "XdrTrustLineEntryExt", "v0",
          "Trustline extension at v0."),
    _seed("TrustLineEntryExt", "XdrTrustLineEntryExt",
          {"v1": {"liabilities": {"buying": "0", "selling": "0"}, "ext": "v0"}},
          "Trustline extension at v1."),
    _seed("SorobanTransactionMetaExt", "XdrSorobanTransactionMetaExt", "v0",
          "Soroban transaction meta extension at v0."),
    _seed("SorobanTransactionMetaExt", "XdrSorobanTransactionMetaExt",
          {"v1": {"ext": "v0", "total_non_refundable_resource_fee_charged": "1",
                  "total_refundable_resource_fee_charged": "2",
                  "rent_fee_charged": "3"}},
          "Soroban transaction meta extension at v1."),
    _seed("TransactionPhase", "XdrTransactionPhase", {"v0": []},
          "Transaction phase at v0 with no components."),
    _seed("TransactionPhase", "XdrTransactionPhase",
          {"v1": {"base_fee": None, "execution_stages": []}},
          "Transaction phase at its non-zero int-cased arm."),
    _seed("TransactionMeta", "XdrTransactionMeta", {"v0": []},
          "Transaction meta at v0 with no operations."),
    _seed("TransactionMeta", "XdrTransactionMeta",
          {"v1": {"tx_changes": [], "operations": []}},
          "Transaction meta at v1."),
    _seed("LedgerCloseMetaExt", "XdrLedgerCloseMetaExt", "v0",
          "Ledger close meta extension at v0."),
    _seed("LedgerCloseMetaExt", "XdrLedgerCloseMetaExt",
          {"v1": {"ext": "v0", "soroban_fee_write1_kb": "1"}},
          "Ledger close meta extension at v1."),

    # --- Standalone 64-bit integers: SEP-0051 requires a string ------------
    _seed("Int64", "XdrInt64", 0,
          "Standalone signed 64-bit zero must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "XdrInt64", 1,
          "Standalone signed 64-bit one must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "XdrInt64", -1,
          "Standalone signed 64-bit minus one must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "XdrInt64", -9223372036854775808,
          "Standalone signed 64-bit minimum must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "XdrInt64", 9223372036854775807,
          "Standalone signed 64-bit maximum must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Uint64", "XdrUint64", 0,
          "Standalone unsigned 64-bit zero must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Uint64", "XdrUint64", 1,
          "Standalone unsigned 64-bit one must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Uint64", "XdrUint64", 18446744073709551615,
          "Standalone unsigned 64-bit maximum must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),

    # --- Inline fixed opaque: SEP-0051 requires lowercase hex --------------
    _seed("Curve25519Secret", "XdrCurve25519Secret", {"key": BYTES_32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("Curve25519Secret", "XdrCurve25519Secret", {"key": BYTES_32_ZERO},
          "All-zero inline fixed opaque must render as 64 hex zeros.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("Curve25519Public", "XdrCurve25519Public", {"key": BYTES_32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("HmacSha256Key", "XdrHmacSha256Key", {"key": BYTES_32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("HmacSha256Mac", "XdrHmacSha256Mac", {"mac": [255] * 32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["mac"]),
    _seed("ShortHashSeed", "XdrShortHashSeed", {"seed": BYTES_16},
          "Inline 16-byte fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["seed"]),
    # PeerAddress declares its opaque inline in the union arms rather than
    # through a named typedef, so both arms take the same divergence, and the
    # 32-bit counters beside them must survive the rewrite untouched.
    _seed("PeerAddress", "XdrPeerAddress",
          {"ip": {"i_pv4": IPV4_LOOPBACK}, "port": 11625, "num_failures": 3},
          "Inline fixed opaque in the four-byte address arm must render as "
          "lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["ip.i_pv4"]),
    _seed("PeerAddress", "XdrPeerAddress",
          {"ip": {"i_pv6": IPV6_DOCUMENTATION}, "port": 0,
           "num_failures": 4294967295},
          "Inline fixed opaque in the sixteen-byte address arm must render as "
          "lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["ip.i_pv6"]),

    # --- Misc scalars and small structs ------------------------------------
    _seed("Price", "XdrPrice", {"n": -2147483648, "d": 2147483647},
          "Price at both signed 32-bit extremes."),
    _seed("Int32", "XdrInt32", -2147483648,
          "Standalone signed 32-bit minimum renders as a number."),
    _seed("Uint32", "XdrUint32", 4294967295,
          "Standalone unsigned 32-bit maximum renders as a number."),
    _seed("DecoratedSignature", "XdrDecoratedSignature",
          {"hint": "01020304", "signature": ""},
          "Decorated signature with an empty variable opaque signature."),
    _seed("DecoratedSignature", "XdrDecoratedSignature",
          {"hint": "ffffffff", "signature": "aabb"},
          "Decorated signature with data."),
    _seed("ContractCostParams", "XdrContractCostParams", [],
          "Empty variable array typedef renders as an empty array."),
    _seed("ContractCostParams", "XdrContractCostParams",
          [{"ext": "v0", "const_term": "1", "linear_term": "2"}],
          "Variable array typedef with one entry."),
    _seed("ConfigSettingEntry", "XdrConfigSettingEntry",
          {"contract_max_size_bytes": 100},
          "Config setting entry arm carrying a 32-bit value."),
    _seed("ConfigSettingEntry", "XdrConfigSettingEntry",
          {"contract_compute_v0": {"ledger_max_instructions": "1",
                                   "tx_max_instructions": "2",
                                   "fee_rate_per_instructions_increment": "3",
                                   "tx_memory_limit": 4}},
          "Config setting entry arm carrying a struct."),
    _seed("DontHave", "XdrDontHave", {"type": "dont_have", "req_hash": HASH1},
          "Overlay message renders its type field under the key type."),
    _seed("ThresholdIndexes", "XdrThresholdIndexes", "master_weight",
          "Threshold index enum member is stripped of its shared prefix."),
    _seed("EnvelopeType", "XdrEnvelopeType", "tx",
          "Envelope type enum member is stripped of its shared prefix."),
    _seed("EnvelopeType", "XdrEnvelopeType", "soroban_authorization",
          "Multi-word envelope type enum member."),
    _seed("ContractCostType", "XdrContractCostType", "wasm_insn_exec",
          "Contract cost type enum member."),
    _seed("ClaimAtom", "XdrClaimAtom",
          {"v0": {"seller_ed25519": HASH1, "offer_id": "1",
                  "asset_sold": "native", "amount_sold": "1",
                  "asset_bought": ASSET_A4, "amount_bought": "2"}},
          "Claim atom at its version 0 arm."),
    _seed("ClaimAtom", "XdrClaimAtom",
          {"liquidity_pool": {"liquidity_pool_id": L1, "asset_sold": "native",
                              "amount_sold": "1", "asset_bought": ASSET_A4,
                              "amount_bought": "2"}},
          "Claim atom at its liquidity pool arm."),
    _seed("RevokeSponsorshipOp", "XdrRevokeSponsorshipOp",
          {"ledger_entry": {"offer": {"seller_id": G1, "offer_id": "3"}}},
          "Revoke sponsorship targeting a ledger entry key."),
    _seed("RevokeSponsorshipOp", "XdrRevokeSponsorshipOp",
          {"signer": {"account_id": G1, "signer_key": P_SHORT}},
          "Revoke sponsorship targeting a signed payload signer."),
    _seed("BucketEntry", "XdrBucketEntry",
          {"metaentry": {"ledger_version": 23, "ext": "v0"}},
          "Bucket metadata entry arm keeps its unsplit member name."),
    _seed("BucketEntry", "XdrBucketEntry",
          {"deadentry": {"contract_code": {"hash": HASH1}}},
          "Bucket dead entry arm carries a ledger key."),
    _seed("HotArchiveBucketEntry", "XdrHotArchiveBucketEntry",
          {"archived": {"last_modified_ledger_seq": 1,
                        "data": {"ttl": {"key_hash": HASH1,
                                         "live_until_ledger_seq": 2}},
                        "ext": "v0"}},
          "Hot archive archived entry arm."),
    _seed("HotArchiveBucketEntry", "XdrHotArchiveBucketEntry",
          {"live": {"contract_code": {"hash": HASH1}}},
          "Hot archive live entry arm carries a ledger key."),
    _seed("TtlEntry", "XdrTTLEntry",
          {"key_hash": HASH1, "live_until_ledger_seq": 0},
          "TTL entry renders its hash as hex and its sequence as a number."),
    _seed("ContractDataEntry", "XdrContractDataEntry",
          {"ext": "v0", "contract": C1, "key": {"symbol": "k"},
           "durability": "temporary", "val": "void"},
          "Contract data entry keys its fields in declaration order."),
]
