# Type resolution overrides for the Dart XDR generator.
#
# TYPE_OVERRIDES: Maps typedef-resolved class names to the actual Dart types
# the SDK uses. Applied in dart_type_for_typespec() when resolving Simple types.
#
# BASE_WRAPPER_TYPES: Types that generate *_base.dart files (union types get
# decodeAs<T>, struct types get plain decode). The wrapper file extends the base.
#
# SELF_REFERENCING_BASE_TYPES: Base types that reference their own wrapper type
# in field declarations (e.g., XdrSCValBase has List<XdrSCVal> fields).
#
# SKIP_TYPES: Types the generator must NOT produce. Initially all types;
# shrink by removing batches as generation is verified.

# Maps generated typedef names to the types the SDK actually uses.
TYPE_OVERRIDES = {
  # SequenceNumber is typedef int64 -> Dart wraps as XdrBigInt64
  # but the SDK uses XdrSequenceNumber directly (no override needed)

  # Duration/TimePoint are typedef uint64 but SDK has no separate classes.
  # Map to XdrUint64 which is the wrapper the SDK uses in struct fields.
  "XdrTimePoint" => "XdrUint64",
  "XdrDuration" => "XdrUint64",

  # Fixed-opaque typedefs that the SDK uses as raw Uint8List (no wrapper class).
  # AssetCode4/AssetCode12 are typedef opaque[4]/opaque[12]; the hand-written SDK
  # uses Uint8List directly in AllowTrustOpAsset union arms and struct fields.
  "XdrAssetCode4" => "Uint8List",
  "XdrAssetCode12" => "Uint8List",
}.freeze

# The 32 types whose generator output goes to *_base.dart files.
# The hand-maintained wrapper files extend these base classes.
BASE_WRAPPER_TYPES = %w[
  XdrAccountID
  XdrChangeTrustAsset
  XdrClaimableBalanceID
  XdrContractEvent
  XdrContractExecutable
  XdrContractIDPreimage
  XdrDiagnosticEvent
  XdrHostFunction
  XdrInt128Parts
  XdrInt256Parts
  XdrLedgerEntry
  XdrLedgerEntryChanges
  XdrLedgerEntryData
  XdrLedgerFootprint
  XdrLedgerKey
  XdrLedgerKeyData
  XdrLedgerKeyOffer
  XdrMuxedAccountMed25519
  XdrPublicKey
  XdrSCAddress
  XdrSCSpecTypeDef
  XdrSCVal
  XdrSorobanAuthorizedFunction
  XdrSorobanCredentials
  XdrSorobanTransactionData
  XdrTransactionEnvelope
  XdrTransactionEvent
  XdrTransactionMeta
  XdrTransactionResult
  XdrTrustlineAsset
  XdrUInt128Parts
  XdrUInt256Parts
].freeze

# Base types that import their own wrapper (circular dependency).
# XdrSCValBase has List<XdrSCVal> fields, so it imports xdr_sc_val.dart.
SELF_REFERENCING_BASE_TYPES = %w[
  XdrSCVal
].freeze

# Types the generator must NOT produce yet. Remove batches after verifying.
SKIP_TYPES = %w[
  TrustLineEntryExtensionV2
  TrustLineEntryExtensionV2Ext
  XdrAccountEntryV1
  XdrAccountEntryV1Ext
  XdrAccountEntryV2
  XdrAccountEntryV2Ext
  XdrAccountEntryV3
  XdrAccountID
  XdrAsset
  XdrAssetAlphaNum12
  XdrAssetAlphaNum4
  XdrAuth
  XdrAuthCert
  XdrAuthenticatedMessage
  XdrAuthenticatedMessageV0
  XdrBigInt64
  XdrBucketEntry
  XdrBucketMetadata
  XdrBucketMetadataExt
  XdrChangeTrustAsset
  XdrClaimLiquidityAtom
  XdrClaimOfferAtom
  XdrClaimOfferAtomV0
  XdrClaimableBalanceEntry
  XdrClaimableBalanceEntryExt
  XdrClaimableBalanceEntryExtV1
  XdrClaimableBalanceEntryExtV1Ext
  XdrClaimableBalanceID
  XdrConfigSettingContractBandwidthV0
  XdrConfigSettingContractComputeV0
  XdrConfigSettingContractEventsV0
  XdrConfigSettingContractExecutionLanesV0
  XdrConfigSettingContractHistoricalDataV0
  XdrConfigSettingContractLedgerCostExtV0
  XdrConfigSettingContractLedgerCostV0
  XdrConfigSettingContractParallelComputeV0
  XdrConfigSettingEntry
  XdrConfigSettingSCPTiming
  XdrConfigUpgradeSet
  XdrConfigUpgradeSetKey
  XdrConstantProduct
  XdrContractCodeCostInputs
  XdrContractCodeEntry
  XdrContractCodeEntryExt
  XdrContractCodeEntryExtV1
  XdrContractCodeEntryV1
  XdrContractCostParamEntry
  XdrContractCostParams
  XdrContractDataEntry
  XdrContractEvent
  XdrContractEventBody
  XdrContractEventBodyV0
  XdrContractEventV0
  XdrContractExecutable
  XdrContractID
  XdrContractIDPreimage
  XdrContractIDPreimageFromAddress
  XdrCreateContractArgs
  XdrCreateContractArgsV2
  XdrCurve25519Secret
  XdrDataEntry
  XdrDataEntryExt
  XdrDependentTxCluster
  XdrDiagnosticEvent
  XdrDontHave
  XdrDuration
  XdrEncryptedBody
  XdrError
  XdrEvictionIterator
  XdrExtendFootprintTTLOp
  XdrExtendFootprintTTLResult
  XdrFeeBumpTransaction
  XdrFeeBumpTransactionEnvelope
  XdrFeeBumpTransactionExt
  XdrFeeBumpTransactionInnerTx
  XdrFloodAdvert
  XdrFloodDemand
  XdrGeneralizedTransactionSet
  XdrHashIDPreimage
  XdrHashIDPreimageContractID
  XdrHashIDPreimageOperationID
  XdrHashIDPreimageRevokeID
  XdrHashIDPreimageSorobanAuthorization
  XdrHello
  XdrHmacSha256Key
  XdrHmacSha256Mac
  XdrHostFunction
  XdrHotArchiveBucketEntry
  XdrInnerTransactionResult
  XdrInnerTransactionResultExt
  XdrInnerTransactionResultPair
  XdrInnerTransactionResultResult
  XdrInt128Parts
  XdrInt256Parts
  XdrInvokeContractArgs
  XdrInvokeHostFunctionOp
  XdrInvokeHostFunctionResult
  XdrInvokeHostFunctionSuccessPreImage
  XdrLedgerCloseMeta
  XdrLedgerCloseMetaBatch
  XdrLedgerCloseMetaExt
  XdrLedgerCloseMetaExtV1
  XdrLedgerCloseMetaV0
  XdrLedgerCloseMetaV1
  XdrLedgerCloseMetaV2
  XdrLedgerCloseValueSignature
  XdrLedgerEntry
  XdrLedgerEntryChange
  XdrLedgerEntryChanges
  XdrLedgerEntryData
  XdrLedgerEntryExt
  XdrLedgerEntryV1
  XdrLedgerEntryV1Ext
  XdrLedgerFootprint
  XdrLedgerHeader
  XdrLedgerHeaderExt
  XdrLedgerHeaderExtensionV1
  XdrLedgerHeaderExtensionV1Ext
  XdrLedgerHeaderHistoryEntry
  XdrLedgerHeaderHistoryEntryExt
  XdrLedgerKey
  XdrLedgerKeyAccount
  XdrLedgerKeyClaimableBalance
  XdrLedgerKeyConfigSetting
  XdrLedgerKeyContractCode
  XdrLedgerKeyContractData
  XdrLedgerKeyData
  XdrLedgerKeyLiquidityPool
  XdrLedgerKeyOffer
  XdrLedgerKeyTTL
  XdrLedgerKeyTrustLine
  XdrLedgerSCPMessages
  XdrLedgerUpgrade
  XdrLiquidityPoolBody
  XdrLiquidityPoolConstantProductParameters
  XdrLiquidityPoolDepositOp
  XdrLiquidityPoolDepositResult
  XdrLiquidityPoolEntry
  XdrLiquidityPoolEntryConstantProduct
  XdrLiquidityPoolParameters
  XdrLiquidityPoolWithdrawOp
  XdrLiquidityPoolWithdrawResult
  XdrManageOfferResult
  XdrManageOfferSuccessResult
  XdrManageOfferSuccessResultOffer
  XdrMuxedAccountMed25519
  XdrOfferEntryExt
  XdrOperation
  XdrOperationBody
  XdrOperationMeta
  XdrOperationMetaV2
  XdrOperationResult
  XdrOperationResultTr
  XdrParallelTxExecutionStage
  XdrParallelTxsComponent
  XdrPathPaymentResultSuccess
  XdrPathPaymentStrictReceiveOp
  XdrPathPaymentStrictReceiveResult
  XdrPathPaymentStrictSendOp
  XdrPathPaymentStrictSendResult
  XdrPeerAddress
  XdrPeerAddressIp
  XdrPeerStats
  XdrPersistedSCPState
  XdrPersistedSCPStateV0
  XdrPersistedSCPStateV1
  XdrPoolID
  XdrPreconditions
  XdrPreconditionsV2
  XdrRestoreFootprintOp
  XdrRestoreFootprintResult
  XdrRevokeSponsorshipOp
  XdrRevokeSponsorshipResult
  XdrRevokeSponsorshipSigner
  XdrSCAddress
  XdrSCBytes
  XdrSCContractInstance
  XdrSCEnvMetaEntry
  XdrSCEnvMetaEntryInterfaceVersion
  XdrSCError
  XdrSCMap
  XdrSCMapEntry
  XdrSCMetaEntry
  XdrSCMetaV0
  XdrSCNonceKey
  XdrSCPEnvelope
  XdrSCPHistoryEntry
  XdrSCPHistoryEntryV0
  XdrSCPNomination
  XdrSCPQuorumSet
  XdrSCPStatement
  XdrSCPStatementConfirm
  XdrSCPStatementExternalize
  XdrSCPStatementPledges
  XdrSCPStatementPrepare
  XdrSCSpecEntry
  XdrSCSpecEventParamV0
  XdrSCSpecEventV0
  XdrSCSpecFunctionInputV0
  XdrSCSpecFunctionV0
  XdrSCSpecTypeBytesN
  XdrSCSpecTypeDef
  XdrSCSpecTypeMap
  XdrSCSpecTypeOption
  XdrSCSpecTypeResult
  XdrSCSpecTypeTuple
  XdrSCSpecTypeUDT
  XdrSCSpecTypeVec
  XdrSCSpecUDTEnumCaseV0
  XdrSCSpecUDTEnumV0
  XdrSCSpecUDTErrorEnumCaseV0
  XdrSCSpecUDTErrorEnumV0
  XdrSCSpecUDTStructFieldV0
  XdrSCSpecUDTStructV0
  XdrSCSpecUDTUnionCaseTupleV0
  XdrSCSpecUDTUnionCaseV0
  XdrSCSpecUDTUnionCaseVoidV0
  XdrSCSpecUDTUnionV0
  XdrSCString
  XdrSCSymbol
  XdrSCVal
  XdrSCVec
  XdrSendMore
  XdrSendMoreExtended
  XdrSequenceNumber
  XdrSerializedBinaryFuseFilter
  XdrSetTrustLineFlagsOp
  XdrSetTrustLineFlagsResult
  XdrShortHashSeed
  XdrSignatureHint
  XdrSignedPayload
  XdrSignedTimeSlicedSurveyRequestMessage
  XdrSignedTimeSlicedSurveyResponseMessage
  XdrSignedTimeSlicedSurveyStartCollectingMessage
  XdrSignedTimeSlicedSurveyStopCollectingMessage
  XdrSimplePaymentResult
  XdrSorobanAddressCredentials
  XdrSorobanAuthorizationEntries
  XdrSorobanAuthorizationEntry
  XdrSorobanAuthorizedFunction
  XdrSorobanAuthorizedInvocation
  XdrSorobanCredentials
  XdrSorobanResources
  XdrSorobanResourcesExtV0
  XdrSorobanTransactionData
  XdrSorobanTransactionDataExt
  XdrSorobanTransactionMeta
  XdrSorobanTransactionMetaExt
  XdrSorobanTransactionMetaExtV1
  XdrSorobanTransactionMetaV2
  XdrSponsorshipDescriptor
  XdrStateArchivalSettings
  XdrStellar
  XdrStellarMessage
  XdrStellarValue
  XdrStellarValueExt
  XdrStoredDebugTransactionSet
  XdrStoredTransactionSet
  XdrSurveyRequestMessage
  XdrSurveyResponseBody
  XdrSurveyResponseMessage
  XdrTTLEntry
  XdrThresholds
  XdrTimePoint
  XdrTimeSlicedNodeData
  XdrTimeSlicedPeerData
  XdrTimeSlicedPeerDataList
  XdrTimeSlicedSurveyRequestMessage
  XdrTimeSlicedSurveyResponseMessage
  XdrTimeSlicedSurveyStartCollectingMessage
  XdrTimeSlicedSurveyStopCollectingMessage
  XdrTopologyResponseBodyV2
  XdrTransaction
  XdrTransactionEnvelope
  XdrTransactionEvent
  XdrTransactionExt
  XdrTransactionHistoryEntry
  XdrTransactionHistoryEntryExt
  XdrTransactionHistoryResultEntry
  XdrTransactionHistoryResultEntryExt
  XdrTransactionMeta
  XdrTransactionMetaV1
  XdrTransactionMetaV2
  XdrTransactionMetaV3
  XdrTransactionMetaV4
  XdrTransactionPhase
  XdrTransactionResult
  XdrTransactionResultExt
  XdrTransactionResultMeta
  XdrTransactionResultMetaV1
  XdrTransactionResultPair
  XdrTransactionResultResult
  XdrTransactionResultSet
  XdrTransactionSet
  XdrTransactionSetV1
  XdrTransactionSignaturePayload
  XdrTransactionSignaturePayloadTaggedTransaction
  XdrTransactionV0
  XdrTransactionV0Envelope
  XdrTransactionV0Ext
  XdrTransactionV1Envelope
  XdrTrustLineEntry
  XdrTrustLineEntryExt
  XdrTrustLineEntryV1
  XdrTrustLineEntryV1Ext
  XdrTrustlineAsset
  XdrTxAdvertVector
  XdrTxDemandVector
  XdrTxSetComponent
  XdrTxSetComponentTxsMaybeDiscountedFee
  XdrUInt128Parts
  XdrUInt256Parts
  XdrUpgradeEntryMeta
  XdrUpgradeType
  XdrValue
].freeze
