// Copyright 2020 The Stellar Flutter SDK Authors. All rights reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

import '../response.dart';
import 'account_effects_responses.dart';
import 'signer_effects_responses.dart';
import 'trustline_effects_responses.dart';
import 'trade_effects_responses.dart';
import 'data_effects_responses.dart';
import 'misc_effects_responses.dart';
import 'claimable_balances_effects.dart';
import 'sponsorship_effects_responses.dart';
import 'liquidity_pools_effects_responses.dart';
import 'soroban_effects_responses.dart';
import '../../assets.dart';

/// Abstract base class for all effect responses from Horizon.
///
/// Effects represent the actual changes to the Stellar ledger state resulting from operations.
/// While operations represent the intentions or actions requested by accounts, effects show
/// the concrete state changes that occurred when those operations were applied.
///
/// Key concepts:
/// - Every operation can trigger multiple effects
/// - Effects are generated by Horizon, not submitted by users
/// - Effects provide a detailed audit trail of ledger changes
/// - Multiple effects can result from a single operation
///
/// Example:
/// ```dart
/// // Query effects for an account
/// final effects = await sdk.effects.forAccount('account_id').execute();
///
/// // Handle different effect types
/// for (var effect in effects.records) {
///   print('Effect type: ${effect.type} at ${effect.createdAt}');
///
///   if (effect is AccountCreditedEffectResponse) {
///     print('Account credited: ${effect.amount}');
///   } else if (effect is AccountDebitedEffectResponse) {
///     print('Account debited: ${effect.amount}');
///   } else if (effect is TradeEffectResponse) {
///     print('Trade executed: ${effect.soldAmount} for ${effect.boughtAmount}');
///   }
/// }
/// ```
///
/// See also:
/// - [Stellar developer docs](https://developers.stellar.org)
abstract class EffectResponse extends Response {
  /// Unique identifier for this effect
  String id;

  /// Effect type as integer code
  int type_i;

  /// Human-readable effect type name
  String type;

  /// When this effect occurred in ISO 8601 format
  String createdAt;

  /// Cursor for pagination
  String pagingToken;

  /// Account ID affected by this effect
  String account;

  /// Muxed account address if the account is a muxed account
  String? accountMuxed;

  /// Muxed account sub-account ID if applicable
  String? accountMuxedId;

  /// Links to related resources
  EffectResponseLinks links;

  /// Creates an effect response with required fields from Horizon API.
  ///
  /// This constructor is typically called internally when deserializing effect
  /// records from Horizon API responses.
  ///
  /// Parameters:
  /// - [id] Unique identifier for this effect
  /// - [type_i] Effect type as integer code
  /// - [type] Human-readable effect type name
  /// - [createdAt] When this effect occurred in ISO 8601 format
  /// - [pagingToken] Cursor for pagination
  /// - [account] Account ID affected by this effect
  /// - [links] Links to related resources
  EffectResponse(this.id, this.type_i, this.type, this.createdAt,
      this.pagingToken, this.account, this.links);

  factory EffectResponse.fromJson(Map<String, dynamic> json) {
    int type = json["type_i"];
    switch (type) {
      // Account effects
      case 0:
        return AccountCreatedEffectResponse.fromJson(json);
      case 1:
        return AccountRemovedEffectResponse.fromJson(json);
      case 2:
        return AccountCreditedEffectResponse.fromJson(json);
      case 3:
        return AccountDebitedEffectResponse.fromJson(json);
      case 4:
        return AccountThresholdsUpdatedEffectResponse.fromJson(json);
      case 5:
        return AccountHomeDomainUpdatedEffectResponse.fromJson(json);
      case 6:
        return AccountFlagsUpdatedEffectResponse.fromJson(json);
      case 7:
        return AccountInflationDestinationUpdatedEffectResponse.fromJson(json);
      // Signer effects
      case 10:
        return SignerCreatedEffectResponse.fromJson(json);
      case 11:
        return SignerRemovedEffectResponse.fromJson(json);
      case 12:
        return SignerUpdatedEffectResponse.fromJson(json);
      // Trustline effects
      case 20:
        return TrustlineCreatedEffectResponse.fromJson(json);
      case 21:
        return TrustlineRemovedEffectResponse.fromJson(json);
      case 22:
        return TrustlineUpdatedEffectResponse.fromJson(json);
      case 23:
        return TrustlineAuthorizedEffectResponse.fromJson(json);
      case 24:
        return TrustlineDeauthorizedEffectResponse.fromJson(json);
      case 25:
        return TrustlineAuthorizedToMaintainLiabilitiesEffectResponse.fromJson(
            json);
      case 26:
        return TrustLineFlagsUpdatedEffectResponse.fromJson(json);
      // Trading effects
      case 30:
        return OfferCreatedEffectResponse.fromJson(json);
      case 31:
        return OfferRemovedEffectResponse.fromJson(json);
      case 32:
        return OfferUpdatedEffectResponse.fromJson(json);
      case 33:
        return TradeEffectResponse.fromJson(json);
      // Data effects
      case 40:
        return DataCreatedEffectResponse.fromJson(json);
      case 41:
        return DataRemovedEffectResponse.fromJson(json);
      case 42:
        return DataUpdatedEffectResponse.fromJson(json);
      // Bump Sequence effects
      case 43:
        return SequenceBumpedEffectResponse.fromJson(json);
      // Claimable Balance effects
      case 50:
        return ClaimableBalanceCreatedEffectResponse.fromJson(json);
      case 51:
        return ClaimableBalanceClaimantCreatedEffectResponse.fromJson(json);
      case 52:
        return ClaimableBalanceClaimedEffectResponse.fromJson(json);
      // Sponsorship
      case 60:
        return AccountSponsorshipCreatedEffectResponse.fromJson(json);
      case 61:
        return AccountSponsorshipUpdatedEffectResponse.fromJson(json);
      case 62:
        return AccountSponsorshipRemovedEffectResponse.fromJson(json);
      case 63:
        return TrustlineSponsorshipCreatedEffectResponse.fromJson(json);
      case 64:
        return TrustlineSponsorshipUpdatedEffectResponse.fromJson(json);
      case 65:
        return TrustlineSponsorshipRemovedEffectResponse.fromJson(json);
      case 66:
        return DataSponsorshipCreatedEffectResponse.fromJson(json);
      case 67:
        return DataSponsorshipUpdatedEffectResponse.fromJson(json);
      case 68:
        return DataSponsorshipRemovedEffectResponse.fromJson(json);
      case 69:
        return ClaimableBalanceSponsorshipCreatedEffectResponse.fromJson(json);
      case 70:
        return ClaimableBalanceSponsorshipUpdatedEffectResponse.fromJson(json);
      case 71:
        return ClaimableBalanceSponsorshipRemovedEffectResponse.fromJson(json);
      case 72:
        return SignerSponsorshipCreatedEffectResponse.fromJson(json);
      case 73:
        return SignerSponsorshipUpdatedEffectResponse.fromJson(json);
      case 74:
        return SignerSponsorshipRemovedEffectResponse.fromJson(json);
      case 80:
        return ClaimableBalanceClawedBackEffectResponse.fromJson(json);
      case 90:
        return LiquidityPoolDepositedEffectResponse.fromJson(json);
      case 91:
        return LiquidityPoolWithdrewEffectResponse.fromJson(json);
      case 92:
        return LiquidityPoolTradeEffectResponse.fromJson(json);
      case 93:
        return LiquidityPoolCreatedEffectResponse.fromJson(json);
      case 94:
        return LiquidityPoolRemovedEffectResponse.fromJson(json);
      case 95:
        return LiquidityPoolRevokedEffectResponse.fromJson(json);
      case 96:
        return ContractCreditedEffectResponse.fromJson(json);
      case 97:
        return ContractDebitedEffectResponse.fromJson(json);
      default:
        throw Exception("Unknown effect type $type in horizon response");
    }
  }
}

/// Links to related resources for an effect.
class EffectResponseLinks {
  /// Link to the operation that triggered this effect
  Link operation;

  /// Link to the effect that precedes this one
  Link precedes;

  /// Link to the effect that succeeds this one
  Link succeeds;

  /// Creates effect response links with navigation to related resources.
  ///
  /// Parameters:
  /// - [operation] Link to the operation that triggered this effect
  /// - [precedes] Link to the effect that precedes this one
  /// - [succeeds] Link to the effect that succeeds this one
  EffectResponseLinks(this.operation, this.precedes, this.succeeds);

  /// Creates effect response links from Horizon API JSON response.
  factory EffectResponseLinks.fromJson(Map<String, dynamic> json) {
    return EffectResponseLinks(
      Link.fromJson(json['operation']),
      Link.fromJson(json['precedes']),
      Link.fromJson(json['succeeds']),
    );
  }

  /// Converts these effect response links to a JSON map.
  ///
  /// Returns: A map containing operation, precedes, and succeeds link objects
  Map<String, dynamic> toJson() => <String, dynamic>{
        'operation': operation,
        'precedes': precedes,
        'succeeds': succeeds
      };
}

/// Represents an amount of a specific asset.
class AssetAmount {
  /// The amount as a string to preserve precision
  String amount;

  /// The asset type and details, may be null for failed transactions
  Asset? asset;

  /// Creates an asset amount with the specified amount and asset.
  ///
  /// Parameters:
  /// - [amount] The amount as a string to preserve precision
  /// - [asset] The asset type and details, may be null for failed transactions
  AssetAmount(this.amount, this.asset);

  /// Creates an asset amount from Horizon API JSON response.
  factory AssetAmount.fromJson(Map<String, dynamic> json) {
    String amount = json['amount'];
    Asset? asset = Asset.createFromCanonicalForm(json['asset']);
    return AssetAmount(amount, asset);
  }
}
